import { createContext, useContext, useEffect, useMemo, useState } from "react";

type Lang = "en" | "hi" | "mr" | "bn" | "ta" | "te" | "gu" | "kn" | "ml" | "pa" | "or" | "as";

type LanguageContextType = {
  lang: Lang;
  toggle: () => void;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
  getLanguageName: () => string;
  getAllLanguages: () => Array<{code: Lang, name: string, nativeName: string}>;
};

// English translations
const englishStrings: Record<string, string> = {
  // Core Navigation & Branding
  home: "Home",
  services: "Services",
  about: "About",
  contact: "Contact",
  findSchemes: "Find Schemes",
  appName: "Govt & Student Help",
  tagline: "One-stop assistance for students and citizens across India",
  heroTitle: "Find Government Schemes, Scholarships & Services",
  heroDesc: "Discover central and state government schemes, scholarships, and services for students and citizens across India.",
  
  // User Categories (NEW)
  forWhom: "Who is this for?",
  students: "Students",
  citizens: "Citizens",
  schemeApplicants: "Scheme Seekers",
  quickLinks: "Quick Links",
  madeFor: "Made for students and citizens",
  evolution: "Evolution of",
  
  // User Type Selection (NEW)
  selectUserType: "I am a...",
  studentDesc: "Looking for scholarships, education schemes, and student services",
  citizenDesc: "Looking for government services, welfare schemes, and citizen benefits",
  schemeApplicantDesc: "Looking to apply for specific government schemes and yojanas",
  schemeSeekers: "Scheme Seekers",
  schemeSeekerDesc: "Apply for specific government schemes and programs",
  
  // Index Page Specific
  govInitiative: "Government of India Initiative",
  govAndStudent: "Government & Student",
  helpPlatform: "Help Platform",
  oneStopAssistance: "One-stop assistance for students and citizens across India",
  governmentSchemesShort: "Government Schemes",
  statesAndUTs: "States & UTs",
  supportAvailable: "Support Available",
  freeServices: "Free Services",
  exploreAllSchemes: "Explore All Schemes",
  whoAreYou: "Who Are You?",
  chooseCategory: "Choose your category to find relevant government schemes and services",
  viewSchemes: "View Schemes",
  popularGovSchemes: "Popular Government Schemes",
  mostAccessedSchemes: "Most accessed schemes by citizens across India",
  viewAllSchemes: "View All Schemes",
  trustedByMillions: "Trusted by Millions",
  citizensHelped: "Citizens Helped",
  applicationsProcessed: "Applications Processed",
  governmentVerified: "Government Verified",
  freeService: "100% Free Service",

  // Location Selection
  selectState: "Select State",
  selectDistrict: "Select District",
  allIndia: "All India",
  search: "Search",
  
  // Categories
  categories: "Service Categories",
  health: "Health",
  education: "Education",
  agriculture: "Agriculture",
  revenue: "Revenue",
  publicWorks: "Public Works",
  more: "More",
  scholarship: "Scholarship",
  welfare: "Welfare",
  employment: "Employment",
  
  // Language Toggle
  lang: "हि/मर",

  // Schemes & Scholarships
  schemes: "Schemes",
  governmentSchemes: "Government Schemes & Scholarships",
  browseSchemes: "Browse schemes for students, citizens, and welfare beneficiaries",
  searchSchemes: "Search schemes...",
  showingNearbySchemes: "Showing schemes available in your area",
  emergencyHelplines: "Emergency Helplines",
  visitWebsite: "Visit Website",
  needHelpWithDocuments: "Need Help with Documents?",
  noSchemesFound: "No schemes found matching your criteria",
  scholarships: "Scholarships",
  studentSchemes: "Student Schemes",
  citizenSchemes: "Citizen Schemes",
  welfareSchemes: "Welfare Schemes",
  
  // Tags (NEW)
  tagStudent: "Student",
  tagCitizen: "Citizen",
  tagGovernment: "Government",
  tagScholarship: "Scholarship",
  tagWelfare: "Welfare",
  tagEducation: "Education",

  // Application & Tracking
  apply: "Apply",
  eligibility: "Eligibility",
  howToApply: "How to Apply",
  step1: "Step 1",
  step2: "Step 2",
  step3: "Step 3",
  step4: "Step 4",
  checkEligibility: "Check Eligibility",
  gatherDocuments: "Gather Documents",
  fillForm: "Fill Application Form",
  submitAndTrack: "Submit & Track",
  trackApplication: "Track Application",
  applicationStatus: "Application Status",
  pending: "Pending",
  approved: "Approved",
  rejected: "Rejected",
  
  // Admin Panel
  adminPanel: "Admin Panel",
  manageApplications: "Manage Applications and Schemes",
  totalApplications: "Total Applications",
  recentApplications: "Recent Applications",
  loading: "Loading...",
  noApplicationsYet: "No applications yet",
  review: "Review",
  approve: "Approve",
  reject: "Reject",

  // Contact & Support
  contactTitle: "Contact Us",
  name: "Name",
  message: "Message",
  submit: "Submit",
  support: "Support",
  supportPhone: "Phone: 1077 (24x7 Citizen Helpline)",
  supportEmail: "Email: support@govhelp.in",

  // Government Contacts
  govContacts: "Government Contacts",
  helpline1077: "National Citizen Helpline",
  helpline1077Phone: "Phone: 1077 (24x7 Free)",
  helpline1077Desc: "All government services helpline",
  
  // Emergency Services
  emergencyServices: "Emergency Services",
  police: "Police: 100",
  fire: "Fire: 101",
  ambulance: "Ambulance: 108",
  disasterMgmt: "Disaster Management: 1070",
  
  // About Page
  aboutTitle: "About Government & Student Help Platform",
  aboutBody: "This platform helps students and citizens across India find government schemes, scholarships, and services. Information is updated regularly from official sources like india.gov.in, scholarships.gov.in, and ministry websites.",
};


// Marathi translations
const marathiStrings: Record<string, string> = {
  // Core Navigation & Branding
  home: "मुख्य पृष्ठ",
  services: "सेवा",
  about: "माहिती",
  contact: "संपर्क",
  appName: "सरकारी व विद्यार्थी मदत",
  tagline: "विद्यार्थी आणि नागरिकांसाठी एकत्रित सहाय्य",
  heroTitle: "सरकारी सेवा, योजना आणि शिष्यवृत्ती शोधा",
  heroDesc: "जिल्हा आणि तालुका निवडून कार्यालये, योजना, शिष्यवृत्ती आणि सेवा शोधा.",
  
  // User Categories
  forWhom: "हे कोणासाठी आहे?",
  students: "विद्यार्थी",
  citizens: "नागरिक",
  schemeApplicants: "योजना अर्जदार",
  quickLinks: "द्रुत दुवे",
  madeFor: "विद्यार्थी आणि नागरिकांसाठी",
  evolution: "याचे उत्क्रांती",
  
  // User Type Selection
  selectUserType: "मी आहे...",
  studentDesc: "शिष्यवृत्ती, शिक्षण योजना आणि विद्यार्थी सेवा शोधत आहे",
  citizenDesc: "सरकारी सेवा, कल्याण योजना आणि नागरिक लाभ शोधत आहे",
  schemeApplicantDesc: "विशिष्ट सरकारी योजनांसाठी अर्ज करू इच्छितो",
  schemeSeekers: "योजना शोधक",
  schemeSeekerDesc: "विशिष्ट सरकारी योजना आणि कार्यक्रमांसाठी अर्ज करा",
  
  // Index Page Specific
  govInitiative: "भारत सरकारचा उपक्रम",
  govAndStudent: "सरकारी व विद्यार्थी",
  helpPlatform: "मदत प्लॅटफॉर्म",
  oneStopAssistance: "भारतभरातील विद्यार्थी आणि नागरिकांसाठी एकत्रित सहाय्य",
  governmentSchemesShort: "सरकारी योजना",
  statesAndUTs: "राज्य आणि केंद्रशासित प्रदेश",
  supportAvailable: "सहाय्य उपलब्ध",
  freeServices: "मोफत सेवा",
  exploreAllSchemes: "सर्व योजना पहा",
  whoAreYou: "तुम्ही कोण आहात?",
  chooseCategory: "संबंधित सरकारी योजना आणि सेवा शोधण्यासाठी तुमची श्रेणी निवडा",
  viewSchemes: "योजना पहा",
  popularGovSchemes: "लोकप्रिय सरकारी योजना",
  mostAccessedSchemes: "भारतभरातील नागरिकांद्वारे सर्वाधिक वापरल्या जाणाऱ्या योजना",
  viewAllSchemes: "सर्व योजना पहा",
  trustedByMillions: "लाखो लोकांचा विश्वास",
  citizensHelped: "नागरिकांना मदत",
  applicationsProcessed: "अर्ज प्रक्रिया",
  governmentVerified: "सरकार सत्यापित",
  freeService: "100% मोफत सेवा",
  
  // Location
  selectDistrict: "जिल्हा निवडा",
  selectTaluka: "तालुका निवडा",
  search: "शोधा",
  
  // Categories
  categories: "सेवा प्रकार",
  health: "आरोग्य",
  education: "शिक्षण",
  agriculture: "कृषी",
  revenue: "महसूल",
  publicWorks: "सार्वजनिक बांधकाम",
  more: "इतर",
  scholarship: "शिष्यवृत्ती",
  welfare: "कल्याण",
  employment: "रोजगार",

  // Filters & Results
  filters: "निवड",
  category: "विभाग",
  getDirections: "मार्गदर्शन",
  workingHours: "कामकाजाची वेळ",
  office: "कार्यालय",
  address: "पत्ता",
  phone: "फोन",
  email: "ईमेल",
  noResults: "तुमच्या निवडीसाठी सेवा सापडल्या नाहीत.",
  
  // About
  aboutTitle: "सरकारी व विद्यार्थी मदत प्लॅटफॉर्म बद्दल",
  aboutBody: "हे प्लॅटफॉर्म भारतभरातील विद्यार्थी आणि नागरिकांना सरकारी योजना, शिष्यवृत्ती आणि सेवा शोधण्यात मदत करते. माहिती data.gov.in, india.gov.in आणि scholarships.gov.in सारख्या अधिकृत स्रोतांमधून नियमितपणे अद्यतनित केली जाते.",
  
  // Contact
  contactTitle: "आमच्याशी संपर्क साधा",
  name: "नाव",
  message: "संदेश",
  submit: "सबमिट",
  support: "मदत",
  supportPhone: "फोन: 1800-111-555",
  supportEmail: "ईमेल: support@govhelpindia.in",
  
  // Government Contacts
  govContacts: "शासन संपर्क",
  cmOffice: "India.gov.in पोर्टल",
  cmPhone: "भारताचे राष्ट्रीय पोर्टल",
  cmEmail: "ईमेल: webmaster@nic.in",
  collectorate: "NSP हेल्पडेस्क",
  collectoratePhone: "फोन: 0120-4200200",
  collectorateEmail: "ईमेल: helpdesk@nsp.gov.in",
  helpline1077: "नागरिक हेल्पलाईन",
  helpline1077Phone: "फोन: 1800-111-555 (मोफत)",
  helpline1077Desc: "24x7 नागरिक सेवा हेल्पलाईन",
  
  // Emergency
  emergencyServices: "आपत्कालीन सेवा",
  police: "पोलीस: 100",
  fire: "अग्निशामक: 101",
  ambulance: "रुग्णवाहिका: 108",
  disasterMgmt: "आपत्ती व्यवस्थापन: 1070",
  
  // Online Services
  onlineServices: "ऑनलाईन सेवा",
  aaplePortal: "भारताचे राष्ट्रीय पोर्टल",
  aaplePortalDesc: "सरकारी सेवांसाठी एक-स्टॉप प्रवेश",
  aaplePortalUrl: "india.gov.in",
  rtcPortal: "राष्ट्रीय शिष्यवृत्ती पोर्टल",
  rtcPortalDesc: "ऑनलाइन शिष्यवृत्तीसाठी अर्ज करा",
  rtcPortalUrl: "scholarships.gov.in",
  
  lang: "हि",

  // Application Form
  applyService: "सेवेसाठी अर्ज करा",
  applicationForm: "अर्ज फॉर्म",
  personalInfo: "वैयक्तिक माहिती",
  fullName: "पूर्ण नाव",
  dateOfBirth: "जन्म तारीख",
  gender: "लिंग",
  male: "पुरुष",
  female: "स्त्री",
  other: "इतर",
  fatherName: "वडिलांचे नाव",
  motherName: "आईचे नाव",
  aadharNumber: "आधार क्रमांक",
  panNumber: "पॅन क्रमांक",
  contactInfo: "संपर्क माहिती",
  mobileNumber: "मोबाईल नंबर",
  alternateNumber: "पर्यायी नंबर",
  emailAddress: "ईमेल पत्ता",
  currentAddress: "सध्याचा पत्ता",
  permanentAddress: "कायमचा पत्ता",
  serviceDetails: "सेवा तपशील",
  serviceType: "सेवेचा प्रकार",
  hospitalService: "हॉस्पिटल सेवा",
  medicalIssue: "वैद्यकीय समस्या/गरज",
  urgencyLevel: "तातडीची पातळी",
  low: "कमी",
  medium: "मध्यम",
  high: "उच्च",
  emergency: "आपत्कालीन",
  preferredDate: "प्राधान्य तारीख",
  preferredTime: "प्राधान्य वेळ",
  documents: "कागदपत्रे",
  uploadDocuments: "आवश्यक कागदपत्रे अपलोड करा",
  idProof: "ओळखपत्र (आधार/पॅन/पासपोर्ट)",
  addressProof: "पत्ता पुरावा",
  incomeProof: "उत्पन्न पुरावा (लागू असल्यास)",
  medicalReports: "वैद्यकीय अहवाल (हॉस्पिटल सेवांसाठी)",
  otherDocuments: "इतर संबंधित कागदपत्रे",
  declaration: "घोषणा",
  declarationText: "मी घोषित करतो की वर दिलेली सर्व माहिती माझ्या माहितीनुसार खरी आणि योग्य आहे.",
  terms: "मी अटी व शर्तींशी सहमत आहे",
  submitApplication: "अर्ज सबमिट करा",
  applicationSuccess: "अर्ज यशस्वीरित्या सबमिट झाला!",
  applicationError: "अर्ज सबमिट करताना त्रुटी. कृपया पुन्हा प्रयत्न करा.",
  required: "आवश्यक",
  apply: "अर्ज करा",

  // Eligibility
  eligibility: "पात्रता",
  eligibilityCriteria: "पात्रता निकष",
  ageRequirement: "वय आवश्यकता",
  incomeRequirement: "उत्पन्न आवश्यकता",
  residenceRequirement: "निवास आवश्यकता",
  documentRequirement: "कागदपत्र आवश्यकता",
  allCitizens: "सर्व नागरिक",
  indianResidents: "भारतीय निवासी",
  districtResidents: "जिल्हा निवासी",
  belowPovertyLine: "दारिद्र्य रेषेखालील (बीपीएल)",
  seniorCitizens: "वृद्ध नागरिक (60+)",
  women: "महिला",
  children: "मुले",
  farmers: "शेतकरी",
  disabled: "दिव्यांग व्यक्ती",
  veterans: "लष्करी पूर्वसैनिक",
  widows: "विधवा",
  singleParents: "एकल पालक",
  unemployed: "बेरोजगार",
  migrantWorkers: "स्थलांतरित कामगार",
  tribalCommunities: "आदिवासी समुदाय",
  scheduledCastes: "अनुसूचित जाती",
  scheduledTribes: "अनुसूचित जमाती",
  otherBackwardClasses: "इतर मागास वर्ग",
  economicallyWeaker: "आर्थिकदृष्ट्या कमकुवत घटक",
  noAgeLimit: "वय मर्यादा नाही",
  yearsAndAbove: "वर्षे आणि वरील",
  yearsAndBelow: "वर्षे आणि खाली",
  betweenYears: "{min} आणि {max} वर्षे दरम्यान",
  annualIncome: "वार्षिक उत्पन्न",
  monthlyIncome: "मासिक उत्पन्न",
  familyIncome: "कौटुंबिक उत्पन्न",
  perCapitaIncome: "प्रति व्यक्ती उत्पन्न",
  lessThan: "पेक्षा कमी",
  moreThan: "पेक्षा जास्त",
  between: "दरम्यान",
  rupees: "रुपये",
  lakhs: "लक्ष",
  crores: "कोटी",
  thousand: "हजार",

  // Documents
  validAddress: "वैध पत्ता पुरावा",
  aadharCard: "आधार कार्ड",
  voterId: "मतदार ओळखपत्र",
  rationCard: "रेशन कार्ड",
  drivingLicense: "चालक परवाना",
  passport: "पासपोर्ट",
  birthCertificate: "जन्म दाखला",
  incomeCertificate: "उत्पन्न दाखला",
  casteCertificate: "जात दाखला",
  domicileCertificate: "मूळगाव दाखला",
  disabilityCertificate: "दिव्यांग दाखला",
  medicalCertificate: "वैद्यकीय दाखला",
  bankPassbook: "बँक पासबुक",
  utilityBill: "उपयोगिता बिल",
  propertyDocument: "मालमत्ता कागदपत्र",
  employmentCertificate: "रोजगार दाखला",
  studentCertificate: "विद्यार्थी दाखला",
  farmerCertificate: "शेतकरी दाखला",
  pensionCertificate: "पेन्शन दाखला",
  widowCertificate: "विधवा दाखला",
  singleParentCertificate: "एकल पालक दाखला",
  unemploymentCertificate: "बेरोजगारी दाखला",
  migrantWorkerCertificate: "स्थलांतरित कामगार दाखला",
  tribalCertificate: "आदिवासी दाखला",
  scStCertificate: "अनुसूचित जाती/जमाती दाखला",
  obcCertificate: "ओबीसी दाखला",
  ewsCertificate: "ईडब्ल्यूएस दाखला",
  and: "आणि",
  or: "किंवा",
  plus: "अधिक",
  additionalDocuments: "अतिरिक्त कागदपत्रे",
  asRequired: "आवश्यकतेनुसार",
  mayBeRequired: "आवश्यक असू शकतात",
  mustBeProvided: "दिले पाहिजेत",
  originalAndCopy: "मूळ आणि प्रत",
  attestedCopy: "प्रमाणित प्रत",
  selfAttested: "स्व-प्रमाणित",
  notarized: "नोटरीकृत",
  recentPhoto: "अलीकडील फोटो",
  passportSize: "पासपोर्ट आकार",
  stampSize: "शिक्का आकार",
  colorPhoto: "रंगीत फोटो",
  blackAndWhite: "काळा आणि पांढरा",
  digitalPhoto: "डिजिटल फोटो",
  physicalPhoto: "भौतिक फोटो",

  // Application Tracking
  trackApplication: "अर्ज ट्रॅक करा",
  trackingId: "ट्रॅकिंग आयडी",
  applicationStatus: "अर्ज स्थिती",
  submitted: "सबमिट केले",
  underReview: "पुनरावलोकनाखाली",
  documentsRequired: "कागदपत्रे आवश्यक",
  approved: "मंजूर",
  rejected: "नाकारले",
  completed: "पूर्ण",
  cancelled: "रद्द",
  applicantName: "अर्जदाराचे नाव",
  submittedDate: "सबमिट तारीख",
  estimatedCompletion: "अंदाजे पूर्णता",
  currentStatus: "सध्याची स्थिती",
  documentStatus: "कागदपत्र स्थिती",
  applicationTimeline: "अर्ज वेळरेषा",
  trackById: "आयडीने ट्रॅक करा",
  trackByContact: "संपर्काने ट्रॅक करा",
  findApplications: "अर्ज शोधा",
  noApplicationFound: "या ट्रॅकिंग आयडीशी कोणताही अर्ज सापडला नाही",
  noApplicationsFound: "दिलेल्या संपर्क माहितीशी कोणतेही अर्ज सापडले नाहीत",
  pleaseEnterTrackingId: "कृपया ट्रॅकिंग आयडी प्रविष्ट करा",
  pleaseEnterContactInfo: "कृपया एकतर ईमेल किंवा फोन नंबर प्रविष्ट करा",
  pending: "प्रलंबित",
  
  // Schemes & Scholarships
  schemes: "योजना",
  governmentSchemes: "सरकारी योजना आणि शिष्यवृत्ती",
  browseSchemes: "विद्यार्थी, नागरिक आणि कल्याण लाभार्थ्यांसाठी योजना पहा",
  searchSchemes: "योजना शोधा...",
  showingNearbySchemes: "तुमच्या क्षेत्रात उपलब्ध योजना दाखवत आहे",
  emergencyHelplines: "आपत्कालीन हेल्पलाइन",
  visitWebsite: "वेबसाइट भेट द्या",
  needHelpWithDocuments: "कागदपत्रांसाठी मदत हवी आहे?",
  noSchemesFound: "तुमच्या निकषांशी जुळणाऱ्या योजना सापडल्या नाहीत",
  scholarships: "शिष्यवृत्ती",
  studentSchemes: "विद्यार्थी योजना",
  citizenSchemes: "नागरिक योजना",
  welfareSchemes: "कल्याण योजना",
  
  // Tags
  tagStudent: "विद्यार्थी",
  tagCitizen: "नागरिक",
  tagGovernment: "सरकारी",
  tagScholarship: "शिष्यवृत्ती",
  tagWelfare: "कल्याण",
  tagEducation: "शिक्षण",

  // Document Helper
  documentHelper: "कागदपत्र सहाय्यक",
  documentHelperDesc: "सरकारी कागदपत्रे मिळविण्यासाठी चरण-दर-चरण मार्गदर्शक",
  stepByStepGuide: "चरण-दर-चरण मार्गदर्शक",
  requiredDocuments: "आवश्यक कागदपत्रे",
  processingTime: "प्रक्रिया वेळ",
  fees: "शुल्क",
  documentTip: "टीप: अनेक भेटी टाळण्यासाठी कार्यालयात जाण्यापूर्वी सर्व कागदपत्रे तयार ठेवा",
  
  // Admin Panel
  adminPanel: "प्रशासक पॅनेल",
  manageApplications: "अर्ज आणि योजना व्यवस्थापित करा",
  totalApplications: "एकूण अर्ज",
  recentApplications: "अलीकडील अर्ज",
  loading: "लोड करत आहे...",
  noApplicationsYet: "अद्याप कोणतेही अर्ज नाहीत",
  review: "पुनरावलोकन",
  approve: "मंजूर",
  reject: "नाकारा",
  
  // Document Assistance
  documentAssistance: "कागदपत्र सहाय्य",
  documentAssistanceDesc: "आम्ही तुम्हाला लहान शुल्कासाठी गहाळ कागदपत्रे मिळविण्यात मदत करू शकतो",
  documentAssistanceInfo: "तुम्हाला ज्या कागदपत्रांसाठी मदत हवी आहे ते निवडा.",
  missing: "गहाळ",
  needHelp: "मदत हवी आहे?",
  weCanHelp: "आम्ही तुम्हाला मदत करू शकतो!",
  viewSteps: "चरण-दर-चरण मार्गदर्शक पहा",
  feeSummary: "शुल्क सारांश",
  baseFee: "मूळ शुल्क",
  documentAssistanceFee: "कागदपत्र सहाय्य शुल्क",
  processingFee: "प्रक्रिया शुल्क",
  total: "एकूण",
  affordablePricing: "सर्व आवश्यक कागदपत्रे सहजपणे मिळविण्यासाठी परवडणारी किंमत",
  cancel: "रद्द करा",
  proceedToPayment: "पेमेंटसाठी पुढे जा",
  paymentSuccess: "पेमेंट यशस्वी!",
  paymentFailed: "पेमेंट अयशस्वी",
  applicationFee: "अर्ज शुल्क",
  payNow: "आता भरा",
  selectPaymentMethod: "पेमेंट पद्धत निवडा",
  upi: "यूपीआय",
  card: "क्रेडिट/डेबिट कार्ड",
  netBanking: "नेट बँकिंग",
  wallet: "वॉलेट",
  
  // How to Apply
  howToApply: "अर्ज कसा करावा",
  step1: "चरण 1",
  step2: "चरण 2",
  step3: "चरण 3",
  step4: "चरण 4",
  checkEligibility: "पात्रता तपासा",
  gatherDocuments: "कागदपत्रे गोळा करा",
  fillForm: "अर्ज फॉर्म भरा",
  submitAndTrack: "सबमिट करा आणि ट्रॅक करा",
  
  // Tooltips
  tooltipAadhar: "UIDAI द्वारे जारी केलेला 12-अंकी अद्वितीय ओळख क्रमांक",
  tooltipBPL: "दारिद्र्य रेषेखालील - वार्षिक उत्पन्न ₹1 लाखापेक्षा कमी असलेली कुटुंबे",
  tooltipOBC: "इतर मागास वर्ग - सामाजिक आणि शैक्षणिकदृष्ट्या मागास समुदाय",
  tooltipSC: "अनुसूचित जाती - संविधान (अनुसूचित जाती) आदेशात सूचीबद्ध समुदाय",
  tooltipST: "अनुसूचित जमाती - संविधानात सूचीबद्ध आदिवासी समुदाय",
  tooltipEWS: "आर्थिकदृष्ट्या कमकुवत घटक - वार्षिक उत्पन्न ₹8 लाखापेक्षा कमी असलेली कुटुंबे",
  tooltipDomicile: "तुम्ही महाराष्ट्राचे कायमचे रहिवासी आहात हे सिद्ध करणारे प्रमाणपत्र",
};


// Hindi translations (comprehensive)
const hindiStrings: Record<string, string> = {
  home: "होम",
  services: "सेवाएं",
  about: "के बारे में",
  contact: "संपर्क",
  appName: "सरकारी व छात्र सहायता",
  tagline: "छात्रों और नागरिकों के लिए एकीकृत सहायता",
  heroTitle: "सरकारी सेवाएं, योजनाएं और छात्रवृत्ति खोजें",
  heroDesc: "भारत भर के छात्रों और नागरिकों के लिए केंद्रीय और राज्य सरकार की योजनाएं, छात्रवृत्ति और सेवाएं खोजें।",
  forWhom: "यह किसके लिए है?",
  students: "छात्र",
  citizens: "नागरिक",
  schemeApplicants: "योजना आवेदक",
  quickLinks: "त्वरित लिंक",
  madeFor: "छात्रों और नागरिकों के लिए",
  evolution: "इसका विकास",
  selectUserType: "मैं हूं...",
  studentDesc: "छात्रवृत्ति, शिक्षा योजनाएं और छात्र सेवाएं खोज रहा हूं",
  citizenDesc: "सरकारी सेवाएं, कल्याण योजनाएं और नागरिक लाभ खोज रहा हूं",
  schemeApplicantDesc: "विशिष्ट सरकारी योजनाओं के लिए आवेदन करना चाहता हूं",
  schemeSeekers: "योजना आवेदक",
  schemeSeekerDesc: "विशिष्ट सरकारी योजनाओं और कार्यक्रमों के लिए आवेदन करें",
  
  // Index Page Specific
  govInitiative: "भारत सरकार की पहल",
  govAndStudent: "सरकारी व छात्र",
  helpPlatform: "सहायता प्लेटफॉर्म",
  oneStopAssistance: "भारत भर के छात्रों और नागरिकों के लिए एकीकृत सहायता",
  governmentSchemesShort: "सरकारी योजनाएं",
  statesAndUTs: "राज्य और केंद्र शासित प्रदेश",
  supportAvailable: "सहायता उपलब्ध",
  freeServices: "मुफ्त सेवाएं",
  exploreAllSchemes: "सभी योजनाएं देखें",
  whoAreYou: "आप कौन हैं?",
  chooseCategory: "संबंधित सरकारी योजनाओं और सेवाओं को खोजने के लिए अपनी श्रेणी चुनें",
  viewSchemes: "योजनाएं देखें",
  popularGovSchemes: "लोकप्रिय सरकारी योजनाएं",
  mostAccessedSchemes: "भारत भर के नागरिकों द्वारा सबसे अधिक उपयोग की जाने वाली योजनाएं",
  viewAllSchemes: "सभी योजनाएं देखें",
  trustedByMillions: "लाखों लोगों का भरोसा",
  citizensHelped: "नागरिकों की मदद",
  applicationsProcessed: "आवेदन प्रसंस्कृत",
  governmentVerified: "सरकार सत्यापित",
  freeService: "100% मुफ्त सेवा",
  selectState: "राज्य चुनें",
  selectDistrict: "जिला चुनें",
  allIndia: "अखिल भारत",
  search: "खोजें",
  categories: "सेवा श्रेणियां",
  health: "स्वास्थ्य",
  education: "शिक्षा",
  agriculture: "कृषि",
  revenue: "राजस्व",
  publicWorks: "लोक निर्माण",
  more: "और",
  scholarship: "छात्रवृत्ति",
  welfare: "कल्याण",
  employment: "रोजगार",
  lang: "EN/मर",
  schemes: "योजनाएं",
  governmentSchemes: "सरकारी योजनाएं और छात्रवृत्ति",
  browseSchemes: "छात्रों, नागरिकों और कल्याण लाभार्थियों के लिए योजनाएं देखें",
  searchSchemes: "योजनाएं खोजें...",
  showingNearbySchemes: "आपके क्षेत्र में उपलब्ध योजनाएं दिखा रहे हैं",
  emergencyHelplines: "आपातकालीन हेल्पलाइन",
  visitWebsite: "वेबसाइट पर जाएं",
  needHelpWithDocuments: "दस्तावेजों में मदद चाहिए?",
  noSchemesFound: "आपके मानदंडों से मेल खाने वाली कोई योजना नहीं मिली",
  scholarships: "छात्रवृत्ति",
  studentSchemes: "छात्र योजनाएं",
  citizenSchemes: "नागरिक योजनाएं",
  welfareSchemes: "कल्याण योजनाएं",
  tagStudent: "छात्र",
  tagCitizen: "नागरिक",
  tagGovernment: "सरकारी",
  tagScholarship: "छात्रवृत्ति",
  tagWelfare: "कल्याण",
  tagEducation: "शिक्षा",
  apply: "आवेदन करें",
  eligibility: "पात्रता",
  howToApply: "आवेदन कैसे करें",
  step1: "चरण 1",
  step2: "चरण 2",
  step3: "चरण 3",
  step4: "चरण 4",
  checkEligibility: "पात्रता जांचें",
  gatherDocuments: "दस्तावेज़ इकट्ठा करें",
  fillForm: "आवेदन पत्र भरें",
  submitAndTrack: "जमा करें और ट्रैक करें",
  trackApplication: "आवेदन ट्रैक करें",
  applicationStatus: "आवेदन स्थिति",
  pending: "लंबित",
  approved: "स्वीकृत",
  rejected: "अस्वीकृत",
  adminPanel: "प्रशासक पैनल",
  manageApplications: "आवेदन और योजनाओं का प्रबंधन करें",
  totalApplications: "कुल आवेदन",
  recentApplications: "हाल के आवेदन",
  loading: "लोड हो रहा है...",
  noApplicationsYet: "अभी तक कोई आवेदन नहीं",
  review: "समीक्षा",
  approve: "स्वीकृत करें",
  reject: "अस्वीकार करें",
  contactTitle: "हमसे संपर्क करें",
  name: "नाम",
  message: "संदेश",
  submit: "जमा करें",
  support: "सहायता",
  supportPhone: "फोन: 1077 (24x7 नागरिक हेल्पलाइन)",
  supportEmail: "ईमेल: support@govhelp.in",
  govContacts: "सरकारी संपर्क",
  helpline1077: "राष्ट्रीय नागरिक हेल्पलाइन",
  helpline1077Phone: "फोन: 1077 (24x7 मुफ्त)",
  helpline1077Desc: "सभी सरकारी सेवाओं की हेल्पलाइन",
  emergencyServices: "आपातकालीन सेवाएं",
  police: "पुलिस: 100",
  fire: "दमकल: 101",
  ambulance: "एम्बुलेंस: 108",
  disasterMgmt: "आपदा प्रबंधन: 1070",
  aboutTitle: "सरकारी व छात्र सहायता प्लेटफॉर्म के बारे में",
  aboutBody: "यह प्लेटफॉर्म भारत भर के छात्रों और नागरिकों को सरकारी योजनाएं, छात्रवृत्ति और सेवाएं खोजने में मदद करता है। जानकारी नियमित रूप से india.gov.in, scholarships.gov.in और मंत्रालय की वेबसाइटों जैसे आधिकारिक स्रोतों से अपडेट की जाती है।",
};

// Bengali translations (comprehensive)
const bengaliStrings: Record<string, string> = {
  home: "হোম",
  services: "সেবা",
  about: "সম্পর্কে",
  contact: "যোগাযোগ",
  findSchemes: "প্রকল্প খুঁজুন",
  appName: "সরকারি ও ছাত্র সহায়তা",
  tagline: "ছাত্র এবং নাগরিকদের জন্য একীভূত সহায়তা",
  heroTitle: "সরকারি প্রকল্প, বৃত্তি এবং সেবা খুঁজুন",
  heroDesc: "ভারত জুড়ে ছাত্র এবং নাগরিকদের জন্য কেন্দ্রীয় এবং রাজ্য সরকারের প্রকল্প, বৃত্তি এবং সেবা আবিষ্কার করুন।",
  
  forWhom: "এটি কার জন্য?",
  students: "ছাত্রছাত্রী",
  citizens: "নাগরিক",
  schemeApplicants: "প্রকল্প আবেদনকারী",
  quickLinks: "দ্রুত লিঙ্ক",
  madeFor: "ছাত্র এবং নাগরিকদের জন্য তৈরি",
  evolution: "বিবর্তন",
  
  selectUserType: "আমি একজন...",
  studentDesc: "বৃত্তি, শিক্ষা প্রকল্প এবং ছাত্র সেবা খুঁজছি",
  citizenDesc: "সরকারি সেবা, কল্যাণ প্রকল্প এবং নাগরিক সুবিধা খুঁজছি",
  schemeApplicantDesc: "নির্দিষ্ট সরকারি প্রকল্পের জন্য আবেদন করতে চাই",
  schemeSeekers: "প্রকল্প আবেদনকারী",
  schemeSeekerDesc: "নির্দিষ্ট সরকারি প্রকল্প এবং কর্মসূচির জন্য আবেদন করুন",
  
  govInitiative: "ভারত সরকারের উদ্যোগ",
  govAndStudent: "সরকারি ও ছাত্র",
  helpPlatform: "সহায়তা প্ল্যাটফর্ম",
  oneStopAssistance: "ভারত জুড়ে ছাত্র এবং নাগরিকদের জন্য একীভূত সহায়তা",
  governmentSchemesShort: "সরকারি প্রকল্প",
  statesAndUTs: "রাজ্য এবং কেন্দ্রশাসিত অঞ্চল",
  supportAvailable: "সহায়তা উপলব্ধ",
  freeServices: "বিনামূল্যে সেবা",
  exploreAllSchemes: "সমস্ত প্রকল্প দেখুন",
  whoAreYou: "আপনি কে?",
  chooseCategory: "প্রাসঙ্গিক সরকারি প্রকল্প এবং সেবা খুঁজতে আপনার বিভাগ চয়ন করুন",
  viewSchemes: "প্রকল্প দেখুন",
  popularGovSchemes: "জনপ্রিয় সরকারি প্রকল্প",
  mostAccessedSchemes: "ভারত জুড়ে নাগরিকদের দ্বারা সর্বাধিক ব্যবহৃত প্রকল্প",
  viewAllSchemes: "সমস্ত প্রকল্প দেখুন",
  trustedByMillions: "লক্ষ লক্ষ মানুষের বিশ্বাস",
  citizensHelped: "নাগরিকদের সাহায্য করা হয়েছে",
  applicationsProcessed: "আবেদন প্রক্রিয়াকৃত",
  governmentVerified: "সরকার যাচাইকৃত",
  freeService: "100% বিনামূল্যে সেবা",
  
  selectState: "রাজ্য নির্বাচন করুন",
  selectDistrict: "জেলা নির্বাচন করুন",
  allIndia: "সমগ্র ভারত",
  search: "অনুসন্ধান",
  
  categories: "সেবা বিভাগ",
  health: "স্বাস্থ্য",
  education: "শিক্ষা",
  agriculture: "কৃষি",
  revenue: "রাজস্ব",
  publicWorks: "জনকার্য",
  more: "আরও",
  scholarship: "বৃত্তি",
  welfare: "কল্যাণ",
  employment: "কর্মসংস্থান",
  
  lang: "EN/हि",
  
  schemes: "প্রকল্প",
  governmentSchemes: "সরকারি প্রকল্প এবং বৃত্তি",
  browseSchemes: "ছাত্র, নাগরিক এবং কল্যাণ সুবিধাভোগীদের জন্য প্রকল্প ব্রাউজ করুন",
  searchSchemes: "প্রকল্প খুঁজুন...",
  showingNearbySchemes: "আপনার এলাকায় উপলব্ধ প্রকল্প দেখানো হচ্ছে",
  emergencyHelplines: "জরুরি হেল্পলাইন",
  visitWebsite: "ওয়েবসাইট দেখুন",
  needHelpWithDocuments: "নথিতে সাহায্য প্রয়োজন?",
  noSchemesFound: "আপনার মানদণ্ডের সাথে মিলে এমন কোনো প্রকল্প পাওয়া যায়নি",
  scholarships: "বৃত্তি",
  studentSchemes: "ছাত্র প্রকল্প",
  citizenSchemes: "নাগরিক প্রকল্প",
  welfareSchemes: "কল্যাণ প্রকল্প",
  
  tagStudent: "ছাত্র",
  tagCitizen: "নাগরিক",
  tagGovernment: "সরকারি",
  tagScholarship: "বৃত্তি",
  tagWelfare: "কল্যাণ",
  tagEducation: "শিক্ষা",
  
  apply: "আবেদন করুন",
  eligibility: "যোগ্যতা",
  howToApply: "কীভাবে আবেদন করবেন",
  step1: "ধাপ 1",
  step2: "ধাপ 2",
  step3: "ধাপ 3",
  step4: "ধাপ 4",
  checkEligibility: "যোগ্যতা পরীক্ষা করুন",
  gatherDocuments: "নথি সংগ্রহ করুন",
  fillForm: "আবেদন ফর্ম পূরণ করুন",
  submitAndTrack: "জমা দিন এবং ট্র্যাক করুন",
  trackApplication: "আবেদন ট্র্যাক করুন",
  applicationStatus: "আবেদনের অবস্থা",
  pending: "অপেক্ষমাণ",
  approved: "অনুমোদিত",
  rejected: "প্রত্যাখ্যাত",
  
  adminPanel: "প্রশাসক প্যানেল",
  manageApplications: "আবেদন এবং প্রকল্প পরিচালনা করুন",
  totalApplications: "মোট আবেদন",
  recentApplications: "সাম্প্রতিক আবেদন",
  loading: "লোড হচ্ছে...",
  noApplicationsYet: "এখনও কোনো আবেদন নেই",
  review: "পর্যালোচনা",
  approve: "অনুমোদন করুন",
  reject: "প্রত্যাখ্যান করুন",
  
  contactTitle: "আমাদের সাথে যোগাযোগ করুন",
  name: "নাম",
  message: "বার্তা",
  submit: "জমা দিন",
  support: "সহায়তা",
  supportPhone: "ফোন: 1077 (24x7 নাগরিক হেল্পলাইন)",
  supportEmail: "ইমেল: support@govhelp.in",
  
  govContacts: "সরকারি যোগাযোগ",
  helpline1077: "জাতীয় নাগরিক হেল্পলাইন",
  helpline1077Phone: "ফোন: 1077 (24x7 বিনামূল্যে)",
  helpline1077Desc: "সমস্ত সরকারি সেবা হেল্পলাইন",
  
  emergencyServices: "জরুরি সেবা",
  police: "পুলিশ: 100",
  fire: "ফায়ার: 101",
  ambulance: "অ্যাম্বুলেন্স: 108",
  disasterMgmt: "দুর্যোগ ব্যবস্থাপনা: 1070",
  
  aboutTitle: "সরকারি ও ছাত্র সহায়তা প্ল্যাটফর্ম সম্পর্কে",
  aboutBody: "এই প্ল্যাটফর্মটি ভারত জুড়ে ছাত্র এবং নাগরিকদের সরকারি প্রকল্প, বৃত্তি এবং সেবা খুঁজে পেতে সাহায্য করে। তথ্য নিয়মিত india.gov.in, scholarships.gov.in এবং মন্ত্রণালয়ের ওয়েবসাইটের মতো সরকারি উৎস থেকে আপডেট করা হয়।",
};

// Tamil translations (comprehensive)
const tamilStrings: Record<string, string> = {
  ...englishStrings, // Start with English as base
  home: "முகப்பு",
  services: "சேவைகள்",
  about: "பற்றி",
  contact: "தொடர்பு",
  findSchemes: "திட்டங்களைக் கண்டறியவும்",
  appName: "அரசு மற்றும் மாணவர் உதவி",
  tagline: "மாணவர்கள் மற்றும் குடிமக்களுக்கான ஒருங்கிணைந்த உதவி",
  heroTitle: "அரசு திட்டங்கள், உதவித்தொகைகள் மற்றும் சேவைகளைக் கண்டறியவும்",
  heroDesc: "இந்தியா முழுவதும் உள்ள மாணவர்கள் மற்றும் குடிமக்களுக்கான மத்திய மற்றும் மாநில அரசு திட்டங்கள், உதவித்தொகைகள் மற்றும் சேவைகளைக் கண்டறியவும்।",
  forWhom: "இது யாருக்கானது?",
  students: "மாணவர்கள்",
  citizens: "குடிமக்கள்",
  schemeApplicants: "திட்ட விண்ணப்பதாரர்கள்",
  selectUserType: "நான் ஒரு...",
  studentDesc: "உதவித்தொகைகள், கல்வி திட்டங்கள் மற்றும் மாணவர் சேவைகளைத் தேடுகிறேன்",
  citizenDesc: "அரசு சேவைகள், நல்வாழ்வு திட்டங்கள் மற்றும் குடிமக்கள் நலன்களைத் தேடுகிறேன்",
  schemeApplicantDesc: "குறிப்பிட்ட அரசு திட்டங்களுக்கு விண்ணப்பிக்க விரும்புகிறேன்",
  schemeSeekers: "திட்ட விண்ணப்பதாரர்கள்",
  govInitiative: "இந்திய அரசின் முயற்சி",
  govAndStudent: "அரசு மற்றும் மாணவர்",
  helpPlatform: "உதவி தளம்",
  oneStopAssistance: "இந்தியா முழுவதும் உள்ள மாணவர்கள் மற்றும் குடிமக்களுக்கான ஒருங்கிணைந்த உதவி",
  governmentSchemesShort: "அரசு திட்டங்கள்",
  statesAndUTs: "மாநிலங்கள் மற்றும் யூனியன் பிரதேசங்கள்",
  exploreAllSchemes: "அனைத்து திட்டங்களையும் ஆராயுங்கள்",
  whoAreYou: "நீங்கள் யார்?",
  chooseCategory: "தொடர்புடைய அரசு திட்டங்கள் மற்றும் சேவைகளைக் கண்டறிய உங்கள் வகையைத் தேர்ந்தெடுக்கவும்",
  viewSchemes: "திட்டங்களைக் காண்க",
  popularGovSchemes: "பிரபலமான அரசு திட்டங்கள்",
  mostAccessedSchemes: "இந்தியா முழுவதும் உள்ள குடிமக்களால் அதிகம் பயன்படுத்தப்படும் திட்டங்கள்",
  viewAllSchemes: "அனைத்து திட்டங்களையும் காண்க",
  trustedByMillions: "மில்லியன் கணக்கானோரின் நம்பிக்கை",
  citizensHelped: "குடிமக்களுக்கு உதவியது",
  search: "தேடல்",
  health: "சுகாதாரம்",
  education: "கல்வி",
  agriculture: "விவசாயம்",
  scholarship: "உதவித்தொகை",
  welfare: "நலன்",
  employment: "வேலைவாய்ப்பு",
  schemes: "திட்டங்கள்",
  apply: "விண்ணப்பிக்கவும்",
  eligibility: "தகுதி",
  pending: "நிலுவையில்",
  approved: "அங்கீகரிக்கப்பட்டது",
  rejected: "நிராகரிக்கப்பட்டது",
  contactTitle: "எங்களை தொடர்பு கொள்ளுங்கள்",
  name: "பெயர்",
  message: "செய்தி",
  submit: "சமர்ப்பிக்கவும்",
  aboutTitle: "அரசு மற்றும் மாணவர் உதவி தளம் பற்றி",
  aboutBody: "இந்த தளம் இந்தியா முழுவதும் உள்ள மாணவர்கள் மற்றும் குடிமக்கள் அரசு திட்டங்கள், உதவித்தொகைகள் மற்றும் சேவைகளைக் கண்டறிய உதவுகிறது।",
};

// Telugu translations (comprehensive)
const teluguStrings: Record<string, string> = {
  ...englishStrings, // Start with English as base
  home: "హోమ్",
  services: "సేవలు",
  about: "గురించి",
  contact: "సంప్రదింపులు",
  appName: "ప్రభుత్వ మరియు విద్యార్థి సహాయం",
  tagline: "విద్యార్థులు మరియు పౌరులకు సమగ్ర సహాయం",
  heroTitle: "ప్రభుత్వ పథకాలు, స్కాలర్‌షిప్‌లు మరియు సేవలను కనుగొనండి",
  heroDesc: "భారతదేశం అంతటా విద్యార్థులు మరియు పౌరుల కోసం కేంద్ర మరియు రాష్ట్ర ప్రభుత్వ పథకాలు, స్కాలర్‌షిప్‌లు మరియు సేవలను కనుగొనండి।",
  students: "విద్యార్థులు",
  citizens: "పౌరులు",
  schemeApplicants: "పథకం దరఖాస్తుదారులు",
  govInitiative: "భారత ప్రభుత్వ చొరవ",
  govAndStudent: "ప్రభుత్వ మరియు విద్యార్థి",
  helpPlatform: "సహాయ వేదిక",
  oneStopAssistance: "భారతదేశం అంతటా విద్యార్థులు మరియు పౌరులకు సమగ్ర సహాయం",
  exploreAllSchemes: "అన్ని పథకాలను అన్వేషించండి",
  whoAreYou: "మీరు ఎవరు?",
  viewSchemes: "పథకాలను చూడండి",
  search: "వెతకండి",
  health: "ఆరోగ్యం",
  education: "విద్య",
  agriculture: "వ్యవసాయం",
  scholarship: "స్కాలర్‌షిప్",
  welfare: "సంక్షేమం",
  employment: "ఉపాధి",
  schemes: "పథకాలు",
  apply: "దరఖాస్తు చేయండి",
  eligibility: "అర్హత",
  pending: "పెండింగ్‌లో",
  approved: "ఆమోదించబడింది",
  rejected: "తిరస్కరించబడింది",
  contactTitle: "మమ్మల్ని సంప్రదించండి",
  name: "పేరు",
  message: "సందేశం",
  submit: "సమర్పించండి",
  aboutTitle: "ప్రభుత్వ మరియు విద్యార్థి సహాయ వేదిక గురించి",
  aboutBody: "ఈ వేదిక భారతదేశం అంతటా విద్యార్థులు మరియు పౌరులు ప్రభుత్వ పథకాలు, స్కాలర్‌షిప్‌లు మరియు సేవలను కనుగొనడంలో సహాయపడుతుంది।",
};

// Gujarati translations (comprehensive)
const gujaratiStrings: Record<string, string> = {
  ...englishStrings,
  home: "હોમ",
  services: "સેવાઓ",
  about: "વિશે",
  contact: "સંપર્ક",
  appName: "સરકારી અને વિદ્યાર્થી સહાય",
  tagline: "વિદ્યાર્થીઓ અને નાગરિકો માટે એકીકૃત સહાય",
  students: "વિદ્યાર્થીઓ",
  citizens: "નાગરિકો",
  schemeApplicants: "યોજના અરજદારો",
  govInitiative: "ભારત સરકારની પહેલ",
  govAndStudent: "સરકારી અને વિદ્યાર્થી",
  helpPlatform: "સહાય પ્લેટફોર્મ",
  oneStopAssistance: "ભારતભરના વિદ્યાર્થીઓ અને નાગરિકો માટે એકીકૃત સહાય",
  exploreAllSchemes: "બધી યોજનાઓ શોધો",
  whoAreYou: "તમે કોણ છો?",
  viewSchemes: "યોજનાઓ જુઓ",
  search: "શોધો",
  health: "આરોગ્ય",
  education: "શિક્ષણ",
  agriculture: "કૃષિ",
  scholarship: "શિષ્યવૃત્તિ",
  welfare: "કલ્યાણ",
  employment: "રોજગાર",
  schemes: "યોજનાઓ",
  apply: "અરજી કરો",
  eligibility: "પાત્રતા",
  pending: "બાકી",
  approved: "મંજૂર",
  rejected: "નકારવામાં આવ્યું",
  contactTitle: "અમારો સંપર્ક કરો",
  name: "નામ",
  message: "સંદેશ",
  submit: "સબમિટ કરો",
  aboutTitle: "સરકારી અને વિદ્યાર્થી સહાય પ્લેટફોર્મ વિશે",
  aboutBody: "આ પ્લેટફોર્મ ભારતભરના વિદ્યાર્થીઓ અને નાગરિકોને સરકારી યોજનાઓ, શિષ્યવૃત્તિઓ અને સેવાઓ શોધવામાં મદદ કરે છે।",
};

// Kannada translations (comprehensive)
const kannadaStrings: Record<string, string> = {
  ...englishStrings,
  home: "ಮುಖ್ಯ ಪುಟ",
  services: "ಸೇವೆಗಳು",
  about: "ಬಗ್ಗೆ",
  contact: "ಸಂಪರ್ಕ",
  appName: "ಸರ್ಕಾರಿ ಮತ್ತು ವಿದ್ಯಾರ್ಥಿ ಸಹಾಯ",
  tagline: "ವಿದ್ಯಾರ್ಥಿಗಳು ಮತ್ತು ನಾಗರಿಕರಿಗೆ ಏಕೀಕೃತ ಸಹಾಯ",
  students: "ವಿದ್ಯಾರ್ಥಿಗಳು",
  citizens: "ನಾಗರಿಕರು",
  schemeApplicants: "ಯೋಜನೆ ಅರ್ಜಿದಾರರು",
  govInitiative: "ಭಾರತ ಸರ್ಕಾರದ ಉಪಕ್ರಮ",
  govAndStudent: "ಸರ್ಕಾರಿ ಮತ್ತು ವಿದ್ಯಾರ್ಥಿ",
  helpPlatform: "ಸಹಾಯ ವೇದಿಕೆ",
  oneStopAssistance: "ಭಾರತದಾದ್ಯಂತ ವಿದ್ಯಾರ್ಥಿಗಳು ಮತ್ತು ನಾಗರಿಕರಿಗೆ ಏಕೀಕೃತ ಸಹಾಯ",
  exploreAllSchemes: "ಎಲ್ಲಾ ಯೋಜನೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ",
  whoAreYou: "ನೀವು ಯಾರು?",
  viewSchemes: "ಯೋಜನೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
  search: "ಹುಡುಕಿ",
  health: "ಆರೋಗ್ಯ",
  education: "ಶಿಕ್ಷಣ",
  agriculture: "ಕೃಷಿ",
  scholarship: "ವಿದ್ಯಾರ್ಥಿವೇತನ",
  welfare: "ಕಲ್ಯಾಣ",
  employment: "ಉದ್ಯೋಗ",
  schemes: "ಯೋಜನೆಗಳು",
  apply: "ಅರ್ಜಿ ಸಲ್ಲಿಸಿ",
  eligibility: "ಅರ್ಹತೆ",
  pending: "ಬಾಕಿ ಇದೆ",
  approved: "ಅನುಮೋದಿಸಲಾಗಿದೆ",
  rejected: "ತಿರಸ್ಕರಿಸಲಾಗಿದೆ",
  contactTitle: "ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ",
  name: "ಹೆಸರು",
  message: "ಸಂದೇಶ",
  submit: "ಸಲ್ಲಿಸಿ",
  aboutTitle: "ಸರ್ಕಾರಿ ಮತ್ತು ವಿದ್ಯಾರ್ಥಿ ಸಹಾಯ ವೇದಿಕೆಯ ಬಗ್ಗೆ",
  aboutBody: "ಈ ವೇದಿಕೆಯು ಭಾರತದಾದ್ಯಂತ ವಿದ್ಯಾರ್ಥಿಗಳು ಮತ್ತು ನಾಗರಿಕರು ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು, ವಿದ್ಯಾರ್ಥಿವೇತನಗಳು ಮತ್ತು ಸೇವೆಗಳನ್ನು ಕಂಡುಹಿಡಿಯಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ।",
};

// Malayalam translations (comprehensive)
const malayalamStrings: Record<string, string> = {
  ...englishStrings,
  home: "ഹോം",
  services: "സേവനങ്ങൾ",
  about: "കുറിച്ച്",
  contact: "ബന്ധപ്പെടുക",
  appName: "സർക്കാർ, വിദ്യാർത്ഥി സഹായം",
  tagline: "വിദ്യാർത്ഥികൾക്കും പൗരന്മാർക്കും സമഗ്ര സഹായം",
  students: "വിദ്യാർത്ഥികൾ",
  citizens: "പൗരന്മാർ",
  schemeApplicants: "പദ്ധതി അപേക്ഷകർ",
  govInitiative: "ഇന്ത്യാ ഗവൺമെന്റ് സംരംഭം",
  govAndStudent: "സർക്കാർ, വിദ്യാർത്ഥി",
  helpPlatform: "സഹായ പ്ലാറ്റ്ഫോം",
  oneStopAssistance: "ഇന്ത്യയിലുടനീളമുള്ള വിദ്യാർത്ഥികൾക്കും പൗരന്മാർക്കും സമഗ്ര സഹായം",
  exploreAllSchemes: "എല്ലാ പദ്ധതികളും പര്യവേക്ഷണം ചെയ്യുക",
  whoAreYou: "നിങ്ങൾ ആരാണ്?",
  viewSchemes: "പദ്ധതികൾ കാണുക",
  search: "തിരയുക",
  health: "ആരോഗ്യം",
  education: "വിദ്യാഭ്യാസം",
  agriculture: "കൃഷി",
  scholarship: "സ്കോളർഷിപ്പ്",
  welfare: "ക്ഷേമം",
  employment: "തൊഴിൽ",
  schemes: "പദ്ധതികൾ",
  apply: "അപേക്ഷിക്കുക",
  eligibility: "യോഗ്യത",
  pending: "തീർപ്പുകൽപ്പിക്കാത്ത",
  approved: "അംഗീകരിച്ചു",
  rejected: "നിരസിച്ചു",
  contactTitle: "ഞങ്ങളെ ബന്ധപ്പെടുക",
  name: "പേര്",
  message: "സന്ദേശം",
  submit: "സമർപ്പിക്കുക",
  aboutTitle: "സർക്കാർ, വിദ്യാർത്ഥി സഹായ പ്ലാറ്റ്ഫോമിനെ കുറിച്ച്",
  aboutBody: "ഈ പ്ലാറ്റ്ഫോം ഇന്ത്യയിലുടനീളമുള്ള വിദ്യാർത്ഥികളെയും പൗരന്മാരെയും സർക്കാർ പദ്ധതികൾ, സ്കോളർഷിപ്പുകൾ, സേവനങ്ങൾ എന്നിവ കണ്ടെത്താൻ സഹായിക്കുന്നു।",
};

// Punjabi translations (comprehensive)
const punjabiStrings: Record<string, string> = {
  ...englishStrings,
  home: "ਘਰ",
  services: "ਸੇਵਾਵਾਂ",
  about: "ਬਾਰੇ",
  contact: "ਸੰਪਰਕ",
  appName: "ਸਰਕਾਰੀ ਅਤੇ ਵਿਦਿਆਰਥੀ ਸਹਾਇਤਾ",
  tagline: "ਵਿਦਿਆਰਥੀਆਂ ਅਤੇ ਨਾਗਰਿਕਾਂ ਲਈ ਏਕੀਕ੍ਰਿਤ ਸਹਾਇਤਾ",
  students: "ਵਿਦਿਆਰਥੀ",
  citizens: "ਨਾਗਰਿਕ",
  schemeApplicants: "ਸਕੀਮ ਅਰਜ਼ੀਦਾਰ",
  govInitiative: "ਭਾਰਤ ਸਰਕਾਰ ਦੀ ਪਹਿਲਕਦਮੀ",
  govAndStudent: "ਸਰਕਾਰੀ ਅਤੇ ਵਿਦਿਆਰਥੀ",
  helpPlatform: "ਸਹਾਇਤਾ ਪਲੇਟਫਾਰਮ",
  oneStopAssistance: "ਭਾਰਤ ਭਰ ਦੇ ਵਿਦਿਆਰਥੀਆਂ ਅਤੇ ਨਾਗਰਿਕਾਂ ਲਈ ਏਕੀਕ੍ਰਿਤ ਸਹਾਇਤਾ",
  exploreAllSchemes: "ਸਾਰੀਆਂ ਸਕੀਮਾਂ ਦੀ ਪੜਚੋਲ ਕਰੋ",
  whoAreYou: "ਤੁਸੀਂ ਕੌਣ ਹੋ?",
  viewSchemes: "ਸਕੀਮਾਂ ਦੇਖੋ",
  search: "ਖੋਜੋ",
  health: "ਸਿਹਤ",
  education: "ਸਿੱਖਿਆ",
  agriculture: "ਖੇਤੀਬਾੜੀ",
  scholarship: "ਸਕਾਲਰਸ਼ਿਪ",
  welfare: "ਭਲਾਈ",
  employment: "ਰੁਜ਼ਗਾਰ",
  schemes: "ਸਕੀਮਾਂ",
  apply: "ਅਰਜ਼ੀ ਦਿਓ",
  eligibility: "ਯੋਗਤਾ",
  pending: "ਬਕਾਇਆ",
  approved: "ਮਨਜ਼ੂਰ",
  rejected: "ਰੱਦ",
  contactTitle: "ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੋ",
  name: "ਨਾਮ",
  message: "ਸੰਦੇਸ਼",
  submit: "ਜਮ੍ਹਾਂ ਕਰੋ",
  aboutTitle: "ਸਰਕਾਰੀ ਅਤੇ ਵਿਦਿਆਰਥੀ ਸਹਾਇਤਾ ਪਲੇਟਫਾਰਮ ਬਾਰੇ",
  aboutBody: "ਇਹ ਪਲੇਟਫਾਰਮ ਭਾਰਤ ਭਰ ਦੇ ਵਿਦਿਆਰਥੀਆਂ ਅਤੇ ਨਾਗਰਿਕਾਂ ਨੂੰ ਸਰਕਾਰੀ ਸਕੀਮਾਂ, ਸਕਾਲਰਸ਼ਿਪਾਂ ਅਤੇ ਸੇਵਾਵਾਂ ਲੱਭਣ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹੈ।",
};

// Odia translations (comprehensive)
const odiaStrings: Record<string, string> = {
  ...englishStrings,
  home: "ଘର",
  services: "ସେବାଗୁଡ଼ିକ",
  about: "ବିଷୟରେ",
  contact: "ଯୋଗାଯୋଗ",
  appName: "ସରକାରୀ ଓ ଛାତ୍ର ସହାୟତା",
  tagline: "ଛାତ୍ର ଏବଂ ନାଗରିକମାନଙ୍କ ପାଇଁ ଏକୀକୃତ ସହାୟତା",
  students: "ଛାତ୍ରଛାତ୍ରୀ",
  citizens: "ନାଗରିକ",
  schemeApplicants: "ଯୋଜନା ଆବେଦନକାରୀ",
  govInitiative: "ଭାରତ ସରକାରଙ୍କ ପଦକ୍ଷେପ",
  govAndStudent: "ସରକାରୀ ଓ ଛାତ୍ର",
  helpPlatform: "ସହାୟତା ପ୍ଲାଟଫର୍ମ",
  oneStopAssistance: "ଭାରତର ଛାତ୍ର ଏବଂ ନାଗରିକମାନଙ୍କ ପାଇଁ ଏକୀକୃତ ସହାୟତା",
  exploreAllSchemes: "ସମସ୍ତ ଯୋଜନା ଅନ୍ବେଷଣ କରନ୍ତୁ",
  whoAreYou: "ଆପଣ କିଏ?",
  viewSchemes: "ଯୋଜନାଗୁଡ଼ିକ ଦେଖନ୍ତୁ",
  search: "ଖୋଜନ୍ତୁ",
  health: "ସ୍ୱାସ୍ଥ୍ୟ",
  education: "ଶିକ୍ଷା",
  agriculture: "କୃଷି",
  scholarship: "ଛାତ୍ରବୃତ୍ତି",
  welfare: "କଲ୍ୟାଣ",
  employment: "ନିଯୁକ୍ତି",
  schemes: "ଯୋଜନାଗୁଡ଼ିକ",
  apply: "ଆବେଦନ କରନ୍ତୁ",
  eligibility: "ଯୋଗ୍ୟତା",
  pending: "ବିଚାରାଧୀନ",
  approved: "ଅନୁମୋଦିତ",
  rejected: "ପ୍ରତ୍ୟାଖ୍ୟାନ",
  contactTitle: "ଆମ ସହିତ ଯୋଗାଯୋଗ କରନ୍ତୁ",
  name: "ନାମ",
  message: "ବାର୍ତ୍ତା",
  submit: "ଦାଖଲ କରନ୍ତୁ",
  aboutTitle: "ସରକାରୀ ଓ ଛାତ୍ର ସହାୟତା ପ୍ଲାଟଫର୍ମ ବିଷୟରେ",
  aboutBody: "ଏହି ପ୍ଲାଟଫର୍ମ ଭାରତର ଛାତ୍ର ଏବଂ ନାଗରିକମାନଙ୍କୁ ସରକାରୀ ଯୋଜନା, ଛାତ୍ରବୃତ୍ତି ଏବଂ ସେବା ଖୋଜିବାରେ ସାହାଯ୍ୟ କରେ।",
};

// Assamese translations (comprehensive)
const assameseStrings: Record<string, string> = {
  ...englishStrings,
  home: "ঘৰ",
  services: "সেৱাসমূহ",
  about: "বিষয়ে",
  contact: "যোগাযোগ",
  appName: "চৰকাৰী আৰু ছাত্ৰ সহায়",
  tagline: "ছাত্ৰ আৰু নাগৰিকসকলৰ বাবে একীভূত সহায়",
  students: "ছাত্ৰ-ছাত্ৰী",
  citizens: "নাগৰিক",
  schemeApplicants: "আঁচনি আবেদনকাৰী",
  govInitiative: "ভাৰত চৰকাৰৰ পদক্ষেপ",
  govAndStudent: "চৰকাৰী আৰু ছাত্ৰ",
  helpPlatform: "সহায় মঞ্চ",
  oneStopAssistance: "ভাৰতৰ ছাত্ৰ আৰু নাগৰিকসকলৰ বাবে একীভূত সহায়",
  exploreAllSchemes: "সকলো আঁচনি অন্বেষণ কৰক",
  whoAreYou: "আপুনি কোন?",
  viewSchemes: "আঁচনিসমূহ চাওক",
  search: "বিচাৰক",
  health: "স্বাস্থ্য",
  education: "শিক্ষা",
  agriculture: "কৃষি",
  scholarship: "বৃত্তি",
  welfare: "কল্যাণ",
  employment: "নিয়োগ",
  schemes: "আঁচনিসমূহ",
  apply: "আবেদন কৰক",
  eligibility: "যোগ্যতা",
  pending: "বিচাৰাধীন",
  approved: "অনুমোদিত",
  rejected: "প্ৰত্যাখ্যান",
  contactTitle: "আমাৰ সৈতে যোগাযোগ কৰক",
  name: "নাম",
  message: "বাৰ্তা",
  submit: "দাখিল কৰক",
  aboutTitle: "চৰকাৰী আৰু ছাত্ৰ সহায় মঞ্চৰ বিষয়ে",
  aboutBody: "এই মঞ্চই ভাৰতৰ ছাত্ৰ আৰু নাগৰিকসকলক চৰকাৰী আঁচনি, বৃত্তি আৰু সেৱা বিচাৰি পোৱাত সহায় কৰে।",
};


// Combine all strings
const strings: Record<Lang, Record<string, string>> = {
  en: englishStrings,
  hi: hindiStrings,
  mr: marathiStrings,
  bn: bengaliStrings,
  ta: tamilStrings,
  te: teluguStrings,
  gu: gujaratiStrings,
  kn: kannadaStrings,
  ml: malayalamStrings,
  pa: punjabiStrings,
  or: odiaStrings,
  as: assameseStrings,
};

// Language metadata
const languageMetadata = [
  { code: 'en' as Lang, name: 'English', nativeName: 'English' },
  { code: 'hi' as Lang, name: 'Hindi', nativeName: 'हिंदी' },
  { code: 'mr' as Lang, name: 'Marathi', nativeName: 'मराठी' },
  { code: 'bn' as Lang, name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'ta' as Lang, name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te' as Lang, name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'gu' as Lang, name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'kn' as Lang, name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ml' as Lang, name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'pa' as Lang, name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'or' as Lang, name: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'as' as Lang, name: 'Assamese', nativeName: 'অসমীয়া' },
];

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const stored = localStorage.getItem("lang");
    return (stored as Lang) || "en";
  });

  useEffect(() => {
    localStorage.setItem("lang", lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const toggle = () => {
    setLangState((prev) => {
      if (prev === "en") return "hi";
      if (prev === "hi") return "mr";
      return "en";
    });
  };

  const setLang = (l: Lang) => setLangState(l);

  const getLanguageName = () => {
    const langData = languageMetadata.find(l => l.code === lang);
    return langData?.nativeName || 'English';
  };

  const getAllLanguages = () => languageMetadata;

  const t = useMemo(
    () => (key: string) => {
      // Try the requested language first
      if (strings[lang] && strings[lang][key]) {
        return strings[lang][key];
      }
      // Fall back to English
      if (strings.en && strings.en[key]) {
        return strings.en[key];
      }
      // Return the key itself as last resort
      return key;
    },
    [lang]
  );

  return (
    <LanguageContext.Provider value={{ lang, toggle, setLang, t, getLanguageName, getAllLanguages }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLang must be used within a LanguageProvider");
  }
  return context;
}
