import { createContext, useContext, useEffect, useMemo, useState } from "react";

type Lang = "en" | "mr" | "hi";

type LanguageContextType = {
  lang: Lang;
  toggle: () => void;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
};

const strings: Record<Lang, Record<string, string>> = {
  en: {
    home: "Home",
    services: "Services",
    about: "About",
    contact: "Contact",
    appName: "MahaHelp Desk",
    tagline: "Maharashtra's Benefits, One Click Away.",
    heroTitle: "Find Local Government Services in Your Taluka",
    heroDesc:
      "Search district and taluka to discover offices, contacts, and timings.",
    selectDistrict: "Select District",
    selectTaluka: "Select Taluka",
    search: "Search",
    categories: "Service Categories",
    health: "Health",
    education: "Education",
    agriculture: "Agriculture",
    revenue: "Revenue",
    publicWorks: "Public Works",
    more: "More",
    filters: "Filters",
    category: "Category",
    getDirections: "Get Directions",
    workingHours: "Working hours",
    office: "Office",
    address: "Address",
    phone: "Phone",
    email: "Email",
    noResults: "No services found for your selection.",
    aboutTitle: "About MahaHelp Desk",
    aboutBody:
      "MahaHelp Desk helps citizens in Maharashtra quickly find local government offices and services by district and taluka. This demo shows the UI prepared to connect with a backend API.",
    contactTitle: "Contact Us",
    name: "Name",
    message: "Message",
    submit: "Submit",
    support: "Support",
    supportPhone: "Phone: 022-1234-5678",
    supportEmail: "Email: support@mahahelp.in",
    govContacts: "Maharashtra Government Contacts",
    cmOffice: "Chief Minister's Office",
    cmPhone: "Phone: 022-2202-4200",
    cmEmail: "Email: cm@maharashtra.gov.in",
    collectorate: "District Collectorate",
    collectoratePhone: "Phone: 022-2266-0707",
    collectorateEmail: "Email: collector@maharashtra.gov.in",
    helpline1077: "Maharashtra Citizen Helpline",
    helpline1077Phone: "Phone: 1077 (Toll Free)",
    helpline1077Desc: "24x7 Citizen Services Helpline",
    emergencyServices: "Emergency Services",
    police: "Police: 100",
    fire: "Fire: 101",
    ambulance: "Ambulance: 108",
    disasterMgmt: "Disaster Management: 1070",
    onlineServices: "Online Services",
    aaplePortal: "Aple Sarkar Portal",
    aaplePortalDesc: "Online government services platform",
    aaplePortalUrl: "aaplesarkar.maharashtra.gov.in",
    rtcPortal: "Maharashtra RTC",
    rtcPortalDesc: "State transport services",
    rtcPortalUrl: "msrtc.maharashtra.gov.in",
    lang: "मराठी",
    // Apply page translations
    applyService: "Apply for Service",
    applicationForm: "Application Form",
    personalInfo: "Personal Information",
    fullName: "Full Name",
    dateOfBirth: "Date of Birth",
    gender: "Gender",
    male: "Male",
    female: "Female",
    other: "Other",
    fatherName: "Father's Name",
    motherName: "Mother's Name",
    aadharNumber: "Aadhar Number",
    panNumber: "PAN Number",
    contactInfo: "Contact Information",
    mobileNumber: "Mobile Number",
    alternateNumber: "Alternate Number",
    emailAddress: "Email Address",
    currentAddress: "Current Address",
    permanentAddress: "Permanent Address",
    serviceDetails: "Service Details",
    serviceType: "Service Type",
    hospitalService: "Hospital Service",
    medicalIssue: "Medical Issue/Requirement",
    urgencyLevel: "Urgency Level",
    low: "Low",
    medium: "Medium",
    high: "High",
    emergency: "Emergency",
    preferredDate: "Preferred Date",
    preferredTime: "Preferred Time",
    documents: "Documents",
    uploadDocuments: "Upload Required Documents",
    idProof: "ID Proof (Aadhar/PAN/Passport)",
    addressProof: "Address Proof",
    incomeProof: "Income Proof (if applicable)",
    medicalReports: "Medical Reports (for hospital services)",
    otherDocuments: "Other Relevant Documents",
    declaration: "Declaration",
    declarationText: "I hereby declare that all the information provided above is true and correct to the best of my knowledge.",
    terms: "I agree to the terms and conditions",
    submitApplication: "Submit Application",
    applicationSuccess: "Application submitted successfully!",
    applicationError: "Error submitting application. Please try again.",
    required: "Required",
    apply: "Apply",
    eligibility: "Eligibility",
    eligibilityCriteria: "Eligibility Criteria",
    ageRequirement: "Age Requirement",
    incomeRequirement: "Income Requirement",
    residenceRequirement: "Residence Requirement",
    documentRequirement: "Document Requirement",
    allCitizens: "All Citizens",
    maharashtraResidents: "Maharashtra Residents",
    districtResidents: "District Residents",
    belowPovertyLine: "Below Poverty Line (BPL)",
    seniorCitizens: "Senior Citizens (60+)",
    women: "Women",
    children: "Children",
    farmers: "Farmers",
    students: "Students",
    disabled: "Persons with Disabilities",
    veterans: "Veterans",
    widows: "Widows",
    singleParents: "Single Parents",
    unemployed: "Unemployed",
    migrantWorkers: "Migrant Workers",
    tribalCommunities: "Tribal Communities",
    scheduledCastes: "Scheduled Castes",
    scheduledTribes: "Scheduled Tribes",
    otherBackwardClasses: "Other Backward Classes",
    economicallyWeaker: "Economically Weaker Sections",
    noAgeLimit: "No Age Limit",
    yearsAndAbove: "years and above",
    yearsAndBelow: "years and below",
    betweenYears: "between {min} and {max} years",
    annualIncome: "Annual Income",
    monthlyIncome: "Monthly Income",
    familyIncome: "Family Income",
    perCapitaIncome: "Per Capita Income",
    lessThan: "Less than",
    moreThan: "More than",
    between: "Between",
    rupees: "Rupees",
    lakhs: "Lakhs",
    crores: "Crores",
    thousand: "Thousand",
    validAddress: "Valid Address Proof",
    aadharCard: "Aadhar Card",
    voterId: "Voter ID",
    rationCard: "Ration Card",
    drivingLicense: "Driving License",
    passport: "Passport",
    birthCertificate: "Birth Certificate",
    incomeCertificate: "Income Certificate",
    casteCertificate: "Caste Certificate",
    domicileCertificate: "Domicile Certificate",
    disabilityCertificate: "Disability Certificate",
    medicalCertificate: "Medical Certificate",
    bankPassbook: "Bank Passbook",
    utilityBill: "Utility Bill",
    propertyDocument: "Property Document",
    employmentCertificate: "Employment Certificate",
    studentCertificate: "Student Certificate",
    farmerCertificate: "Farmer Certificate",
    pensionCertificate: "Pension Certificate",
    widowCertificate: "Widow Certificate",
    singleParentCertificate: "Single Parent Certificate",
    unemploymentCertificate: "Unemployment Certificate",
    migrantWorkerCertificate: "Migrant Worker Certificate",
    tribalCertificate: "Tribal Certificate",
    scStCertificate: "SC/ST Certificate",
    obcCertificate: "OBC Certificate",
    ewsCertificate: "EWS Certificate",
    and: "and",
    or: "or",
    plus: "plus",
    additionalDocuments: "Additional Documents",
    asRequired: "as required",
    mayBeRequired: "may be required",
    mustBeProvided: "must be provided",
    originalAndCopy: "Original and copy",
    attestedCopy: "Attested copy",
    selfAttested: "Self-attested",
    notarized: "Notarized",
    recentPhoto: "Recent photograph",
    passportSize: "Passport size",
    stampSize: "Stamp size",
    colorPhoto: "Color photograph",
    blackAndWhite: "Black and white",
    digitalPhoto: "Digital photograph",
    physicalPhoto: "Physical photograph",
    trackApplication: "Track Application",
    trackingId: "Tracking ID",
    applicationStatus: "Application Status",
    submitted: "Submitted",
    underReview: "Under Review",
    documentsRequired: "Documents Required",
    approved: "Approved",
    rejected: "Rejected",
    completed: "Completed",
    cancelled: "Cancelled",
    applicantName: "Applicant Name",
    submittedDate: "Submitted Date",
    estimatedCompletion: "Estimated Completion",
    currentStatus: "Current Status",
    documentStatus: "Document Status",
    applicationTimeline: "Application Timeline",
    trackById: "Track by ID",
    trackByContact: "Track by Contact",
    findApplications: "Find Applications",
    noApplicationFound: "No application found with this tracking ID",
    noApplicationsFound: "No applications found with the provided contact information",
    pleaseEnterTrackingId: "Please enter a tracking ID",
    pleaseEnterContactInfo: "Please enter either email or phone number",
    // New translations
    schemes: "Schemes",
    governmentSchemes: "Government Schemes & Yojanas",
    browseSchemes: "Browse all Maharashtra government schemes and benefits",
    searchSchemes: "Search schemes...",
    showingNearbySchemes: "Showing schemes available in your area",
    emergencyHelplines: "Emergency Helplines",
    visitWebsite: "Visit Website",
    needHelpWithDocuments: "Need Help with Documents?",
    noSchemesFound: "No schemes found matching your criteria",
    documentHelper: "Document Helper",
    documentHelperDesc: "Step-by-step guides to obtain government documents",
    stepByStepGuide: "Step-by-Step Guide",
    requiredDocuments: "Required Documents",
    processingTime: "Processing Time",
    fees: "Fees",
    documentTip: "Tip: Keep all documents ready before visiting the office to avoid multiple visits",
    adminPanel: "Admin Panel",
    manageApplications: "Manage Applications and Schemes",
    totalApplications: "Total Applications",
    recentApplications: "Recent Applications",
    loading: "Loading...",
    noApplicationsYet: "No applications yet",
    review: "Review",
    approve: "Approve",
    reject: "Reject",
  },
  mr: {
    home: "मुख्य पृष्ठ",
    services: "सेवा",
    about: "माहिती",
    contact: "संपर्क",
    appName: "महा हेल्प डेस्क",
    tagline: "महाराष्ट्राचे लाभ, एका क्लिकवर.",
    heroTitle: "तुमच्या तालुक्यातील शासकीय सेवा शोधा",
    heroDesc:
      "जिल्हा आणि तालुका निवडा व कार्यालये, संपर्क आणि वेळा शोधा.",
    selectDistrict: "जिल्हा निवडा",
    selectTaluka: "तालुका निवडा",
    search: "शोधा",
    categories: "सेवा प्रकार",
    health: "आरोग्य",
    education: "शिक्षण",
    agriculture: "कृषी",
    revenue: "महसूल",
    publicWorks: "सार्वजनिक बांधकाम",
    more: "इतर",
    filters: "निवड",
    category: "विभाग",
    getDirections: "मार्गदर्शन",
    workingHours: "कामकाजाची वेळ",
    office: "कार्यालय",
    address: "पत्ता",
    phone: "फोन",
    email: "ईमेल",
    noResults: "तुमच्या निवडीसाठी सेवा सापडल्या नाहीत.",
    aboutTitle: "महा हेल्प डेस्क बद्दल",
    aboutBody:
      "महाराष्ट्रातील नागरिकांना जिल्हा आणि तालुक्यानुसार शासकीय कार्यालये आणि सेवा पटकन शोधण्यात मदत करते. ही डेमो आवृत्ती आहे जी पुढे बॅकएंड API शी जोडली जाऊ शकते.",
    contactTitle: "आमच्याशी संपर्क साधा",
    name: "नाव",
    message: "संदेश",
    submit: "सबमिट",
    support: "मदत",
    supportPhone: "फोन: 022-1234-5678",
    supportEmail: "ईमेल: support@mahahelp.in",
    govContacts: "महाराष्ट्र शासन संपर्क",
    cmOffice: "मुख्यमंत्री कार्यालय",
    cmPhone: "फोन: 022-2202-4200",
    cmEmail: "ईमेल: cm@maharashtra.gov.in",
    collectorate: "जिल्हाधिकारी कार्यालय",
    collectoratePhone: "फोन: 022-2266-0707",
    collectorateEmail: "ईमेल: collector@maharashtra.gov.in",
    helpline1077: "महाराष्ट्र नागरिक हेल्पलाईन",
    helpline1077Phone: "फोन: 1077 (मोफत)",
    helpline1077Desc: "24x7 नागरिक सेवा हेल्पलाईन",
    emergencyServices: "आपत्कालीन सेवा",
    police: "पोलीस: 100",
    fire: "अग्निशामक: 101",
    ambulance: "रुग्णवाहिका: 108",
    disasterMgmt: "आपत्ती व्यवस्थापन: 1070",
    onlineServices: "ऑनलाईन सेवा",
    aaplePortal: "आपले सरकार पोर्टल",
    aaplePortalDesc: "ऑनलाइन शासकीय सेवा प्लॅटफॉर्म",
    aaplePortalUrl: "aaplesarkar.maharashtra.gov.in",
    rtcPortal: "महाराष्ट्र आरटीसी",
    rtcPortalDesc: "राज्य परिवहन सेवा",
    rtcPortalUrl: "msrtc.maharashtra.gov.in",
    lang: "हि",
    // Apply page translations - Marathi
    applyService: "सेवेसाठी अर्ज करा",
    applicationForm: "अर्ज फॉर्म",
    personalInfo: "वैयक्तिक माहिती",
    fullName: "पूर्ण नाव",
    dateOfBirth: "जन्म तारीख",
    gender: "लिंग",
    male: "पुरुष",
    female: "स्त्री",
    other: "इतर",
    fatherName: "वडिलांचे नाव",
    motherName: "आईचे नाव",
    aadharNumber: "आधार क्रमांक",
    panNumber: "पॅन क्रमांक",
    contactInfo: "संपर्क माहिती",
    mobileNumber: "मोबाईल नंबर",
    alternateNumber: "पर्यायी नंबर",
    emailAddress: "ईमेल पत्ता",
    currentAddress: "सध्याचा पत्ता",
    permanentAddress: "कायमचा पत्ता",
    serviceDetails: "सेवा तपशील",
    serviceType: "सेवेचा प्रकार",
    hospitalService: "हॉस्पिटल सेवा",
    medicalIssue: "वैद्यकीय समस्या/गरज",
    urgencyLevel: "तातडीची पातळी",
    low: "कमी",
    medium: "मध्यम",
    high: "उच्च",
    emergency: "आपत्कालीन",
    preferredDate: "प्राधान्य तारीख",
    preferredTime: "प्राधान्य वेळ",
    documents: "कागदपत्रे",
    uploadDocuments: "आवश्यक कागदपत्रे अपलोड करा",
    idProof: "ओळखपत्र (आधार/पॅन/पासपोर्ट)",
    addressProof: "पत्ता पुरावा",
    incomeProof: "उत्पन्न पुरावा (लागू असल्यास)",
    medicalReports: "वैद्यकीय अहवाल (हॉस्पिटल सेवांसाठी)",
    otherDocuments: "इतर संबंधित कागदपत्रे",
    declaration: "घोषणा",
    declarationText: "मी घोषित करतो की वर दिलेली सर्व माहिती माझ्या माहितीनुसार खरी आणि योग्य आहे.",
    terms: "मी अटी व शर्तींशी सहमत आहे",
    submitApplication: "अर्ज सबमिट करा",
    applicationSuccess: "अर्ज यशस्वीरित्या सबमिट झाला!",
    applicationError: "अर्ज सबमिट करताना त्रुटी. कृपया पुन्हा प्रयत्न करा.",
    required: "आवश्यक",
    apply: "अर्ज करा",
    eligibility: "पात्रता",
    eligibilityCriteria: "पात्रता निकष",
    ageRequirement: "वय आवश्यकता",
    incomeRequirement: "उत्पन्न आवश्यकता",
    residenceRequirement: "निवास आवश्यकता",
    documentRequirement: "कागदपत्र आवश्यकता",
    allCitizens: "सर्व नागरिक",
    maharashtraResidents: "महाराष्ट्र निवासी",
    districtResidents: "जिल्हा निवासी",
    belowPovertyLine: "दारिद्र्य रेषेखालील (बीपीएल)",
    seniorCitizens: "वृद्ध नागरिक (60+)",
    women: "महिला",
    children: "मुले",
    farmers: "शेतकरी",
    students: "विद्यार्थी",
    disabled: "दिव्यांग व्यक्ती",
    veterans: "लष्करी पूर्वसैनिक",
    widows: "विधवा",
    singleParents: "एकल पालक",
    unemployed: "बेरोजगार",
    migrantWorkers: "स्थलांतरित कामगार",
    tribalCommunities: "आदिवासी समुदाय",
    scheduledCastes: "अनुसूचित जाती",
    scheduledTribes: "अनुसूचित जमाती",
    otherBackwardClasses: "इतर मागास वर्ग",
    economicallyWeaker: "आर्थिकदृष्ट्या कमकुवत घटक",
    noAgeLimit: "वय मर्यादा नाही",
    yearsAndAbove: "वर्षे आणि वरील",
    yearsAndBelow: "वर्षे आणि खाली",
    betweenYears: "{min} आणि {max} वर्षे दरम्यान",
    annualIncome: "वार्षिक उत्पन्न",
    monthlyIncome: "मासिक उत्पन्न",
    familyIncome: "कौटुंबिक उत्पन्न",
    perCapitaIncome: "प्रति व्यक्ती उत्पन्न",
    lessThan: "पेक्षा कमी",
    moreThan: "पेक्षा जास्त",
    between: "दरम्यान",
    rupees: "रुपये",
    lakhs: "लक्ष",
    crores: "कोटी",
    thousand: "हजार",
    validAddress: "वैध पत्ता पुरावा",
    aadharCard: "आधार कार्ड",
    voterId: "मतदार ओळखपत्र",
    rationCard: "रेशन कार्ड",
    drivingLicense: "चालक परवाना",
    passport: "पासपोर्ट",
    birthCertificate: "जन्म दाखला",
    incomeCertificate: "उत्पन्न दाखला",
    casteCertificate: "जात दाखला",
    domicileCertificate: "मूळगाव दाखला",
    disabilityCertificate: "दिव्यांग दाखला",
    medicalCertificate: "वैद्यकीय दाखला",
    bankPassbook: "बँक पासबुक",
    utilityBill: "उपयोगिता बिल",
    propertyDocument: "मालमत्ता कागदपत्र",
    employmentCertificate: "रोजगार दाखला",
    studentCertificate: "विद्यार्थी दाखला",
    farmerCertificate: "शेतकरी दाखला",
    pensionCertificate: "पेन्शन दाखला",
    widowCertificate: "विधवा दाखला",
    singleParentCertificate: "एकल पालक दाखला",
    unemploymentCertificate: "बेरोजगारी दाखला",
    migrantWorkerCertificate: "स्थलांतरित कामगार दाखला",
    tribalCertificate: "आदिवासी दाखला",
    scStCertificate: "अनुसूचित जाती/जमाती दाखला",
    obcCertificate: "ओबीसी दाखला",
    ewsCertificate: "ईडब्ल्यूएस दाखला",
    and: "आणि",
    or: "किंवा",
    plus: "अधिक",
    additionalDocuments: "अतिरिक्त कागदपत्रे",
    asRequired: "आवश्यकतेनुसार",
    mayBeRequired: "आवश्यक असू शकतात",
    mustBeProvided: "दिले पाहिजेत",
    originalAndCopy: "मूळ आणि प्रत",
    attestedCopy: "प्रमाणित प्रत",
    selfAttested: "स्व-प्रमाणित",
    notarized: "नोटरीकृत",
    recentPhoto: "अलीकडील फोटो",
    passportSize: "पासपोर्ट आकार",
    stampSize: "शिक्का आकार",
    colorPhoto: "रंगीत फोटो",
    blackAndWhite: "काळा आणि पांढरा",
    digitalPhoto: "डिजिटल फोटो",
    physicalPhoto: "भौतिक फोटो",
    trackApplication: "अर्ज ट्रॅक करा",
    trackingId: "ट्रॅकिंग आयडी",
    applicationStatus: "अर्ज स्थिती",
    submitted: "सबमिट केले",
    underReview: "पुनरावलोकनाखाली",
    documentsRequired: "कागदपत्रे आवश्यक",
    approved: "मंजूर",
    rejected: "नाकारले",
    completed: "पूर्ण",
    cancelled: "रद्द",
    applicantName: "अर्जदाराचे नाव",
    submittedDate: "सबमिट तारीख",
    estimatedCompletion: "अंदाजे पूर्णता",
    currentStatus: "सध्याची स्थिती",
    documentStatus: "कागदपत्र स्थिती",
    applicationTimeline: "अर्ज वेळरेषा",
    trackById: "आयडीने ट्रॅक करा",
    trackByContact: "संपर्काने ट्रॅक करा",
    findApplications: "अर्ज शोधा",
    noApplicationFound: "या ट्रॅकिंग आयडीशी कोणताही अर्ज सापडला नाही",
    noApplicationsFound: "दिलेल्या संपर्क माहितीशी कोणतेही अर्ज सापडले नाहीत",
    pleaseEnterTrackingId: "कृपया ट्रॅकिंग आयडी प्रविष्ट करा",
    pleaseEnterContactInfo: "कृपया एकतर ईमेल किंवा फोन नंबर प्रविष्ट करा",
    // New translations - Marathi
    schemes: "योजना",
    governmentSchemes: "सरकारी योजना आणि लाभ",
    browseSchemes: "सर्व महाराष्ट्र सरकारी योजना आणि लाभ पहा",
    searchSchemes: "योजना शोधा...",
    showingNearbySchemes: "तुमच्या क्षेत्रात उपलब्ध योजना दाखवत आहे",
    emergencyHelplines: "आपत्कालीन हेल्पलाइन",
    visitWebsite: "वेबसाइट भेट द्या",
    needHelpWithDocuments: "कागदपत्रांसाठी मदत हवी आहे?",
    noSchemesFound: "तुमच्या निकषांशी जुळणाऱ्या योजना सापडल्या नाहीत",
    documentHelper: "कागदपत्र सहाय्यक",
    documentHelperDesc: "सरकारी कागदपत्रे मिळविण्यासाठी चरण-दर-चरण मार्गदर्शक",
    stepByStepGuide: "चरण-दर-चरण मार्गदर्शक",
    requiredDocuments: "आवश्यक कागदपत्रे",
    processingTime: "प्रक्रिया वेळ",
    fees: "शुल्क",
    documentTip: "टीप: अनेक भेटी टाळण्यासाठी कार्यालयात जाण्यापूर्वी सर्व कागदपत्रे तयार ठेवा",
    adminPanel: "प्रशासक पॅनेल",
    manageApplications: "अर्ज आणि योजना व्यवस्थापित करा",
    totalApplications: "एकूण अर्ज",
    recentApplications: "अलीकडील अर्ज",
    loading: "लोड करत आहे...",
    noApplicationsYet: "अद्याप कोणतेही अर्ज नाहीत",
    review: "पुनरावलोकन",
    approve: "मंजूर",
    reject: "नाकारा",
    // Document assistance translations - Marathi
    documentAssistance: "कागदपत्र सहाय्य",
    documentAssistanceDesc: "आम्ही तुम्हाला लहान शुल्कासाठी गहाळ कागदपत्रे मिळविण्यात मदत करू शकतो",
    documentAssistanceInfo: "तुम्हाला ज्या कागदपत्रांसाठी मदत हवी आहे ते निवडा. आम्ही चरण-दर-चरण मार्गदर्शन प्रदान करतो.",
    missing: "गहाळ",
    needHelp: "मदत हवी आहे?",
    weCanHelp: "आम्ही तुम्हाला मदत करू शकतो!",
    viewSteps: "चरण-दर-चरण मार्गदर्शक पहा",
    feeSummary: "शुल्क सारांश",
    baseFee: "मूळ शुल्क",
    documentAssistanceFee: "कागदपत्र सहाय्य शुल्क",
    processingFee: "प्रक्रिया शुल्क",
    documents: "कागदपत्रे",
    total: "एकूण",
    affordablePricing: "सर्व आवश्यक कागदपत्रे सहजपणे मिळविण्यासाठी परवडणारी किंमत",
    cancel: "रद्द करा",
    proceedToPayment: "पेमेंटसाठी पुढे जा",
    paymentSuccess: "पेमेंट यशस्वी!",
    paymentFailed: "पेमेंट अयशस्वी",
    applicationFee: "अर्ज शुल्क",
    payNow: "आता भरा",
    selectPaymentMethod: "पेमेंट पद्धत निवडा",
    upi: "यूपीआय",
    card: "क्रेडिट/डेबिट कार्ड",
    netBanking: "नेट बँकिंग",
    wallet: "वॉलेट",
  },
  hi: {
    home: "होम",
    services: "सेवाएं",
    about: "के बारे में",
    contact: "संपर्क",
    appName: "महा हेल्प डेस्क",
    tagline: "महाराष्ट्र के लाभ, एक क्लिक दूर।",
    heroTitle: "अपनी तहसील में स्थानीय सरकारी सेवाएं खोजें",
    heroDesc:
      "कार्यालयों, संपर्कों और समयसारणी खोजने के लिए जिला और तहसील का चयन करें।",
    selectDistrict: "जिला चुनें",
    selectTaluka: "तहसील चुनें",
    search: "खोजें",
    categories: "सेवा श्रेणियां",
    health: "स्वास्थ्य",
    education: "शिक्षा",
    agriculture: "कृषि",
    revenue: "राजस्व",
    publicWorks: "लोक निर्माण",
    more: "और",
    filters: "फ़िल्टर",
    category: "श्रेणी",
    getDirections: "दिशा-निर्देश प्राप्त करें",
    workingHours: "कार्य समय",
    office: "कार्यालय",
    address: "पता",
    phone: "फोन",
    email: "ईमेल",
    noResults: "आपके चयन के लिए कोई सेवा नहीं मिली।",
    aboutTitle: "महा हेल्प डेस्क के बारे में",
    aboutBody:
      "महा हेल्प डेस्क महाराष्ट्र के नागरिकों को जिले और तहसील के अनुसार स्थानीय सरकारी कार्यालयों और सेवाओं को जल्दी खोजने में मदद करता है। यह डेमो दिखाता है कि UI बैकएंड API से जुड़ने के लिए तैयार है।",
    contactTitle: "हमसे संपर्क करें",
    name: "नाम",
    message: "संदेश",
    submit: "जमा करें",
    support: "सहायता",
    supportPhone: "फोन: 022-1234-5678",
    supportEmail: "ईमेल: support@mahahelp.in",
    govContacts: "महाराष्ट्र सरकार संपर्क",
    cmOffice: "मुख्यमंत्री कार्यालय",
    cmPhone: "फोन: 022-2202-4200",
    cmEmail: "ईमेल: cm@maharashtra.gov.in",
    collectorate: "जिला कलेक्टरेट",
    collectoratePhone: "फोन: 022-2266-0707",
    collectorateEmail: "ईमेल: collector@maharashtra.gov.in",
    helpline1077: "महाराष्ट्र नागरिक हेल्पलाइन",
    helpline1077Phone: "फोन: 1077 (टोल फ्री)",
    helpline1077Desc: "24x7 नागरिक सेवा हेल्पलाइन",
    emergencyServices: "आपातकालीन सेवाएं",
    police: "पुलिस: 100",
    fire: "दमकल: 101",
    ambulance: "एम्बुलेंस: 108",
    disasterMgmt: "आपदा प्रबंधन: 1070",
    onlineServices: "ऑनलाइन सेवाएं",
    aaplePortal: "आपले सरकार पोर्टल",
    aaplePortalDesc: "ऑनलाइन सरकारी सेवा प्लेटफॉर्म",
    aaplePortalUrl: "aaplesarkar.maharashtra.gov.in",
    rtcPortal: "महाराष्ट्र आरटीसी",
    rtcPortalDesc: "राज्य परिवहन सेवाएं",
    rtcPortalUrl: "msrtc.maharashtra.gov.in",
    lang: "EN",
    // Apply page translations - Hindi
    applyService: "सेवा के लिए आवेदन करें",
    applicationForm: "आवेदन पत्र",
    personalInfo: "व्यक्तिगत जानकारी",
    fullName: "पूरा नाम",
    dateOfBirth: "जन्म तिथि",
    gender: "लिंग",
    male: "पुरुष",
    female: "महिला",
    other: "अन्य",
    fatherName: "पिता का नाम",
    motherName: "माता का नाम",
    aadharNumber: "आधार संख्या",
    panNumber: "पैन संख्या",
    contactInfo: "संपर्क जानकारी",
    mobileNumber: "मोबाइल नंबर",
    alternateNumber: "वैकल्पिक नंबर",
    emailAddress: "ईमेल पता",
    currentAddress: "वर्तमान पता",
    permanentAddress: "स्थायी पता",
    serviceDetails: "सेवा विवरण",
    serviceType: "सेवा का प्रकार",
    hospitalService: "अस्पताल सेवा",
    medicalIssue: "चिकित्सा समस्या/आवश्यकता",
    urgencyLevel: "तात्कालिकता स्तर",
    low: "कम",
    medium: "मध्यम",
    high: "उच्च",
    emergency: "आपातकालीन",
    preferredDate: "पसंदीदा तारीख",
    preferredTime: "पसंदीदा समय",
    documents: "दस्तावेज़",
    uploadDocuments: "आवश्यक दस्तावेज़ अपलोड करें",
    idProof: "पहचान प्रमाण (आधार/पैन/पासपोर्ट)",
    addressProof: "पता प्रमाण",
    incomeProof: "आय प्रमाण (यदि लागू हो)",
    medicalReports: "चिकित्सा रिपोर्ट (अस्पताल सेवाओं के लिए)",
    otherDocuments: "अन्य प्रासंगिक दस्तावेज़",
    declaration: "घोषणा",
    declarationText: "मैं एतद्द्वारा घोषित करता हूं कि ऊपर दी गई सभी जानकारी मेरी जानकारी के अनुसार सत्य और सही है।",
    terms: "मैं नियमों और शर्तों से सहमत हूं",
    submitApplication: "आवेदन जमा करें",
    applicationSuccess: "आवेदन सफलतापूर्वक जमा किया गया!",
    applicationError: "आवेदन जमा करने में त्रुटि। कृपया पुनः प्रयास करें।",
    required: "आवश्यक",
    apply: "आवेदन करें",
    eligibility: "पात्रता",
    eligibilityCriteria: "पात्रता मापदंड",
    ageRequirement: "आयु आवश्यकता",
    incomeRequirement: "आय आवश्यकता",
    residenceRequirement: "निवास आवश्यकता",
    documentRequirement: "दस्तावेज़ आवश्यकता",
    allCitizens: "सभी नागरिक",
    maharashtraResidents: "महाराष्ट्र निवासी",
    districtResidents: "जिला निवासी",
    belowPovertyLine: "गरीबी रेखा से नीचे (बीपीएल)",
    seniorCitizens: "वरिष्ठ नागरिक (60+)",
    women: "महिलाएं",
    children: "बच्चे",
    farmers: "किसान",
    students: "छात्र",
    disabled: "दिव्यांग व्यक्ति",
    veterans: "सैन्य पूर्वसैनिक",
    widows: "विधवाएं",
    singleParents: "एकल अभिभावक",
    unemployed: "बेरोजगार",
    migrantWorkers: "प्रवासी श्रमिक",
    tribalCommunities: "आदिवासी समुदाय",
    scheduledCastes: "अनुसूचित जाति",
    scheduledTribes: "अनुसूचित जनजाति",
    otherBackwardClasses: "अन्य पिछड़ा वर्ग",
    economicallyWeaker: "आर्थिक रूप से कमजोर वर्ग",
    noAgeLimit: "कोई आयु सीमा नहीं",
    yearsAndAbove: "वर्ष और उससे ऊपर",
    yearsAndBelow: "वर्ष और उससे नीचे",
    betweenYears: "{min} और {max} वर्ष के बीच",
    annualIncome: "वार्षिक आय",
    monthlyIncome: "मासिक आय",
    familyIncome: "पारिवारिक आय",
    perCapitaIncome: "प्रति व्यक्ति आय",
    lessThan: "से कम",
    moreThan: "से अधिक",
    between: "के बीच",
    rupees: "रुपये",
    lakhs: "लाख",
    crores: "करोड़",
    thousand: "हजार",
    validAddress: "वैध पता प्रमाण",
    aadharCard: "आधार कार्ड",
    voterId: "मतदाता पहचान पत्र",
    rationCard: "राशन कार्ड",
    drivingLicense: "ड्राइविंग लाइसेंस",
    passport: "पासपोर्ट",
    birthCertificate: "जन्म प्रमाण पत्र",
    incomeCertificate: "आय प्रमाण पत्र",
    casteCertificate: "जाति प्रमाण पत्र",
    domicileCertificate: "मूल निवास प्रमाण पत्र",
    disabilityCertificate: "दिव्यांग प्रमाण पत्र",
    medicalCertificate: "चिकित्सा प्रमाण पत्र",
    bankPassbook: "बैंक पासबुक",
    utilityBill: "उपयोगिता बिल",
    propertyDocument: "संपत्ति दस्तावेज़",
    employmentCertificate: "रोजगार प्रमाण पत्र",
    studentCertificate: "छात्र प्रमाण पत्र",
    farmerCertificate: "किसान प्रमाण पत्र",
    pensionCertificate: "पेंशन प्रमाण पत्र",
    widowCertificate: "विधवा प्रमाण पत्र",
    singleParentCertificate: "एकल अभिभावक प्रमाण पत्र",
    unemploymentCertificate: "बेरोजगारी प्रमाण पत्र",
    migrantWorkerCertificate: "प्रवासी श्रमिक प्रमाण पत्र",
    tribalCertificate: "आदिवासी प्रमाण पत्र",
    scStCertificate: "अनुसूचित जाति/जनजाति प्रमाण पत्र",
    obcCertificate: "ओबीसी प्रमाण पत्र",
    ewsCertificate: "ईडब्ल्यूएस प्रमाण पत्र",
    and: "और",
    or: "या",
    plus: "प्लस",
    additionalDocuments: "अतिरिक्त दस्तावेज़",
    asRequired: "आवश्यकतानुसार",
    mayBeRequired: "आवश्यक हो सकते हैं",
    mustBeProvided: "प्रदान किए जाने चाहिए",
    originalAndCopy: "मूल और प्रति",
    attestedCopy: "प्रमाणित प्रति",
    selfAttested: "स्व-प्रमाणित",
    notarized: "नोटरीकृत",
    recentPhoto: "हाल का फोटो",
    passportSize: "पासपोर्ट साइज़",
    stampSize: "स्टैम्प साइज़",
    colorPhoto: "रंगीन फोटो",
    blackAndWhite: "काला और सफेद",
    digitalPhoto: "डिजिटल फोटो",
    physicalPhoto: "भौतिक फोटो",
    trackApplication: "आवेदन ट्रैक करें",
    trackingId: "ट्रैकिंग आईडी",
    applicationStatus: "आवेदन स्थिति",
    submitted: "प्रस्तुत किया गया",
    underReview: "समीक्षाधीन",
    documentsRequired: "दस्तावेज़ आवश्यक",
    approved: "स्वीकृत",
    rejected: "अस्वीकृत",
    completed: "पूर्ण",
    cancelled: "रद्द",
    applicantName: "आवेदक का नाम",
    submittedDate: "प्रस्तुत करने की तिथि",
    estimatedCompletion: "अनुमानित पूर्णता",
    currentStatus: "वर्तमान स्थिति",
    documentStatus: "दस्तावेज़ स्थिति",
    applicationTimeline: "आवेदन समयरेखा",
    trackById: "आईडी से ट्रैक करें",
    trackByContact: "संपर्क से ट्रैक करें",
    findApplications: "आवेदन खोजें",
    noApplicationFound: "इस ट्रैकिंग आईडी के साथ कोई आवेदन नहीं मिला",
    noApplicationsFound: "दी गई संपर्क जानकारी के साथ कोई आवेदन नहीं मिला",
    pleaseEnterTrackingId: "कृपया ट्रैकिंग आईडी दर्ज करें",
    pleaseEnterContactInfo: "कृपया या तो ईमेल या फोन नंबर दर्ज करें",
    // New translations - Hindi
    schemes: "योजनाएं",
    governmentSchemes: "सरकारी योजनाएं और लाभ",
    browseSchemes: "सभी महाराष्ट्र सरकारी योजनाएं और लाभ देखें",
    searchSchemes: "योजनाएं खोजें...",
    showingNearbySchemes: "आपके क्षेत्र में उपलब्ध योजनाएं दिखा रहे हैं",
    emergencyHelplines: "आपातकालीन हेल्पलाइन",
    visitWebsite: "वेबसाइट पर जाएं",
    needHelpWithDocuments: "दस्तावेजों में मदद चाहिए?",
    noSchemesFound: "आपके मानदंडों से मेल खाने वाली कोई योजना नहीं मिली",
    documentHelper: "दस्तावेज़ सहायक",
    documentHelperDesc: "सरकारी दस्तावेज़ प्राप्त करने के लिए चरण-दर-चरण गाइड",
    stepByStepGuide: "चरण-दर-चरण गाइड",
    requiredDocuments: "आवश्यक दस्तावेज़",
    processingTime: "प्रसंस्करण समय",
    fees: "शुल्क",
    documentTip: "टिप: कई यात्राओं से बचने के लिए कार्यालय जाने से पहले सभी दस्तावेज़ तैयार रखें",
    adminPanel: "प्रशासक पैनल",
    manageApplications: "आवेदन और योजनाओं का प्रबंधन करें",
    totalApplications: "कुल आवेदन",
    recentApplications: "हाल के आवेदन",
    loading: "लोड हो रहा है...",
    noApplicationsYet: "अभी तक कोई आवेदन नहीं",
    review: "समीक्षा",
    approve: "स्वीकृत करें",
    reject: "अस्वीकार करें",
    // Document assistance translations
    documentAssistance: "Document Assistance",
    documentAssistanceDesc: "We can help you obtain missing documents for a small fee",
    documentAssistanceInfo: "Select the documents you need help with. We provide step-by-step guidance.",
    missing: "Missing",
    needHelp: "Need Help?",
    weCanHelp: "We Can Help You!",
    viewSteps: "View Step-by-Step Guide",
    feeSummary: "Fee Summary",
    baseFee: "Base Fee",
    documentAssistanceFee: "Document Assistance Fee",
    processingFee: "Processing Fee",
    documents: "documents",
    total: "Total",
    affordablePricing: "Affordable pricing to help you get all required documents easily",
    cancel: "Cancel",
    proceedToPayment: "Proceed to Payment",
    paymentSuccess: "Payment Successful!",
    paymentFailed: "Payment Failed",
    applicationFee: "Application Fee",
    payNow: "Pay Now",
    selectPaymentMethod: "Select Payment Method",
    upi: "UPI",
    card: "Credit/Debit Card",
    netBanking: "Net Banking",
    wallet: "Wallet",
  },
};

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => (localStorage.getItem("lang") as Lang) || "en");

  useEffect(() => {
    localStorage.setItem("lang", lang);
    document.documentElement.lang = lang === "en" ? "en" : lang === "mr" ? "mr" : "hi";
    document.body.classList.toggle("font-devanagari", lang === "mr" || lang === "hi");
  }, [lang]);

  const t = useMemo(() => (key: string) => strings[lang][key] ?? key, [lang]);

  const toggleLanguage = () => {
    setLang(l => {
      if (l === "en") return "mr";
      if (l === "mr") return "hi";
      return "en";
    });
  };

  const value = useMemo(() => ({ lang, toggle: toggleLanguage, setLang, t }), [lang, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLang must be used within LanguageProvider");
  return ctx;
}
