import { createContext, useContext, useEffect, useMemo, useState } from "react";

type Lang = "en" | "hi" | "mr" | "bn" | "ta" | "te" | "gu" | "kn" | "ml" | "pa" | "or" | "as";

// Export Lang type for testing
export type { Lang };

type LanguageContextType = {
  lang: Lang;
  toggle: () => void;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
  getLanguageName: () => string;
  getAllLanguages: () => Array<{code: Lang, name: string, nativeName: string}>;
};

// English translations
const englishStrings: Record<string, string> = {
  // Core Navigation & Branding
  home: "Home",
  services: "Services",
  about: "About",
  contact: "Contact",
  findSchemes: "Find Schemes",
  appName: "Govt & Student Help",
  tagline: "One-stop assistance for students and citizens across India",
  heroTitle: "Find Government Schemes, Scholarships & Services",
  heroDesc: "Discover central and state government schemes, scholarships, and services for students and citizens across India.",
  
  // User Categories (NEW)
  forWhom: "Who is this for?",
  students: "Students",
  citizens: "Citizens",
  schemeApplicants: "Scheme Seekers",
  quickLinks: "Quick Links",
  madeFor: "Made for students and citizens",
  evolution: "Evolution of",
  
  // User Type Selection (NEW)
  selectUserType: "I am a...",
  studentDesc: "Looking for scholarships, education schemes, and student services",
  citizenDesc: "Looking for government services, welfare schemes, and citizen benefits",
  schemeApplicantDesc: "Looking to apply for specific government schemes and yojanas",
  schemeSeekers: "Scheme Seekers",
  schemeSeekerDesc: "Apply for specific government schemes and programs",
  
  // Index Page Specific
  govInitiative: "Government of India Initiative",
  govAndStudent: "Government & Student",
  helpPlatform: "Help Platform",
  oneStopAssistance: "One-stop assistance for students and citizens across India",
  governmentSchemesShort: "Government Schemes",
  statesAndUTs: "States & UTs",
  supportAvailable: "Support Available",
  freeServices: "Free Services",
  exploreAllSchemes: "Explore All Schemes",
  whoAreYou: "Who Are You?",
  chooseCategory: "Choose your category to find relevant government schemes and services",
  viewSchemes: "View Schemes",
  popularGovSchemes: "Popular Government Schemes",
  mostAccessedSchemes: "Most accessed schemes by citizens across India",
  viewAllSchemes: "View All Schemes",
  trustedByMillions: "Trusted by Millions",
  citizensHelped: "Citizens Helped",
  applicationsProcessed: "Applications Processed",
  governmentVerified: "Government Verified",
  freeService: "100% Free Service",

  // Location Selection
  selectState: "Select State",
  selectDistrict: "Select District",
  allIndia: "All India",
  search: "Search",
  
  // Categories
  categories: "Service Categories",
  health: "Health",
  education: "Education",
  agriculture: "Agriculture",
  revenue: "Revenue",
  publicWorks: "Public Works",
  more: "More",
  scholarship: "Scholarship",
  welfare: "Welfare",
  employment: "Employment",
  
  // Language Toggle
  lang: "हि/मर",

  // Schemes & Scholarships
  schemes: "Schemes",
  governmentSchemes: "Government Schemes & Scholarships",
  browseSchemes: "Browse schemes for students, citizens, and welfare beneficiaries",
  searchSchemes: "Search schemes...",
  showingNearbySchemes: "Showing schemes available in your area",
  emergencyHelplines: "Emergency Helplines",
  visitWebsite: "Visit Website",
  needHelpWithDocuments: "Need Help with Documents?",
  noSchemesFound: "No schemes found matching your criteria",
  scholarships: "Scholarships",
  studentSchemes: "Student Schemes",
  citizenSchemes: "Citizen Schemes",
  welfareSchemes: "Welfare Schemes",
  
  // Tags (NEW)
  tagStudent: "Student",
  tagCitizen: "Citizen",
  tagGovernment: "Government",
  tagScholarship: "Scholarship",
  tagWelfare: "Welfare",
  tagEducation: "Education",

  // Application & Tracking
  apply: "Apply",
  eligibility: "Eligibility",
  howToApply: "How to Apply",
  step1: "Step 1",
  step2: "Step 2",
  step3: "Step 3",
  step4: "Step 4",
  checkEligibility: "Check Eligibility",
  gatherDocuments: "Gather Documents",
  fillForm: "Fill Application Form",
  submitAndTrack: "Submit & Track",
  trackApplication: "Track Application",
  applicationStatus: "Application Status",
  pending: "Pending",
  approved: "Approved",
  rejected: "Rejected",
  
  // Admin Panel
  adminPanel: "Admin Panel",
  manageApplications: "Manage Applications and Schemes",
  totalApplications: "Total Applications",
  recentApplications: "Recent Applications",
  loading: "Loading...",
  noApplicationsYet: "No applications yet",
  review: "Review",
  approve: "Approve",
  reject: "Reject",

  // Contact & Support
  contactTitle: "Contact Us",
  name: "Name",
  message: "Message",
  submit: "Submit",
  support: "Support",
  supportPhone: "Phone: 1077 (24x7 Citizen Helpline)",
  supportEmail: "Email: support@govhelp.in",

  // Government Contacts
  govContacts: "Government Contacts",
  helpline1077: "National Citizen Helpline",
  helpline1077Phone: "Phone: 1077 (24x7 Free)",
  helpline1077Desc: "All government services helpline",
  
  // Emergency Services
  emergencyServices: "Emergency Services",
  police: "Police: 100",
  fire: "Fire: 101",
  ambulance: "Ambulance: 108",
  disasterMgmt: "Disaster Management: 1070",
  
  // About Page
  aboutTitle: "About Government & Student Help Platform",
  aboutBody: "This platform helps students and citizens across India find government schemes, scholarships, and services. Information is updated regularly from official sources like india.gov.in, scholarships.gov.in, and ministry websites.",
  
  // Authentication
  sign_in: "Sign In",
  sign_out: "Sign Out",
  dashboard: "Dashboard",
  
  // Auth Page Keys (NEW - Task 1)
  login: "Login",
  signup: "Sign up",
  admin: "Admin",
  email: "Email",
  password: "Password",
  displayName: "Display Name",
  district: "District",
  taluka: "Taluka",
  createAccount: "Create account",
  pleaseWait: "Please wait...",
  welcomeBack: "Welcome back!",
  adminAccessOnly: "Admin Access Only",
  restrictedArea: "This area is restricted to authorized government administrators only.",
  authenticating: "Authenticating...",
  adminLogin: "Admin Login",
  invalidCredentials: "Invalid credentials",
  loginFailed: "Login failed",
  signupSuccess: "Account created!",
  checkEmail: "Check your email",
  accountCreated: "Account created! Welcome to Government & Student Help Platform!",
  adminUsername: "Admin Username",
  adminPassword: "Admin Password",
  enterAdminUsername: "Enter admin username",
  enterAdminPassword: "Enter admin password",
  enterFullName: "Enter your full name",
  selectDistrictPlaceholder: "Select District",
  selectTalukaPlaceholder: "Select Taluka",
  
  // Admin Panel Keys (NEW - Task 1)
  totalUsers: "Total Users",
  todayActivity: "Today's Applications",
  pendingReviews: "Pending Applications",
  userManagement: "User Management",
  applicationManagement: "Application Management",
  schemeManagement: "Scheme Management",
  viewDetails: "View Details",
  deleteUser: "Delete User",
  statistics: "Statistics",
  recentActivity: "Recent Activity",
  quickActions: "Quick Actions",
  reviewApplications: "Review Applications",
  addNewScheme: "Add New Scheme",
  viewReports: "View Reports",
  adminDashboard: "Admin Dashboard",
  comprehensiveManagement: "Comprehensive management of schemes and applications",
  live: "Live",
  logout: "Logout",
  allApplications: "All Applications",
  total: "Total",
  noApplicationsFound: "No applications found",
  needsAttention: "Needs attention",
  registeredUsers: "Registered users",
  allTime: "All time",
  receivedToday: "Received today",
  manageAllSchemes: "Manage all government schemes",
  allCategories: "All Categories",
  allStates: "All States",
  export: "Export",
  import: "Import",
  noSchemesFoundFilter: "No Schemes Found",
  adjustFilters: "Adjust filters or add a new scheme",
  manageAllApplications: "Manage all user applications",
  refresh: "Refresh",
  needDocs: "Need Docs",
  users: "Users",
  andMoreUsers: "And {count} more users...",
  noDistrict: "No district",
  categoryDistribution: "Category Distribution",
  applicationStatusLabel: "Application Status",
  systemSettings: "System Settings",
  platformConfiguration: "Platform Configuration",
  defaultLanguage: "Default Language",
  maxUploadSize: "Max Upload Size",
  securitySettings: "Security Settings",
  twoFactorAuth: "Two-Factor Authentication",
  enableForSecurity: "Enable for additional security",
  enable: "Enable",
  sessionTimeout: "Session Timeout",
  autoLogout: "Auto logout after inactivity",
  saveSettings: "Save Settings",
  analytics: "Analytics",
  settings: "Settings",
  
  // Common UI Keys (NEW - Task 1)
  save: "Save",
  cancel: "Cancel",
  edit: "Edit",
  delete: "Delete",
  confirm: "Confirm",
  back: "Back",
  next: "Next",
  previous: "Previous",
  close: "Close",
  open: "Open",
  yes: "Yes",
  no: "No",
  ok: "OK",
  error: "Error",
  success: "Success",
  warning: "Warning",
  info: "Info",
  processing: "Processing...",
  
  // Services & About Page Keys (NEW - Task 1)
  allServices: "All Services",
  serviceCategories: "Service Categories",
  popularServices: "Popular Services",
  mission: "Mission",
  vision: "Vision",
  features: "Features",
  howItWorks: "How It Works",
  
  // Contact Page Keys (NEW - Task 1)
  getInTouch: "Get In Touch",
  sendMessage: "Send Message",
  yourName: "Your Name",
  yourEmail: "Your Email",
  yourMessage: "Your Message",
  messageSent: "Message Sent",
  
  // AI Assistant Keys (NEW - Task 1)
  aiWelcome: "Welcome! I'm here to help you find government schemes and services. How can I assist you today?",
  aiHelp: "I can help you with finding schemes, checking eligibility, and answering questions about government services.",
  aiCommands: "Available commands: /schemes, /eligibility, /apply, /track, /help",
  askQuestion: "Ask a question",
  typeMessage: "Type your message",
  
  // Theme Keys (NEW)
  toggleTheme: "Toggle theme",
  lightMode: "Light",
  darkMode: "Dark",
  systemMode: "System",
};


// Marathi translations
const marathiStrings: Record<string, string> = {
  // Core Navigation & Branding
  home: "मुख्य पृष्ठ",
  services: "सेवा",
  about: "माहिती",
  contact: "संपर्क",
  findSchemes: "योजना शोधा",
  appName: "सरकारी व विद्यार्थी मदत",
  tagline: "विद्यार्थी आणि नागरिकांसाठी एकत्रित सहाय्य",
  heroTitle: "सरकारी सेवा, योजना आणि शिष्यवृत्ती शोधा",
  heroDesc: "जिल्हा आणि तालुका निवडून कार्यालये, योजना, शिष्यवृत्ती आणि सेवा शोधा.",
  
  // User Categories
  forWhom: "हे कोणासाठी आहे?",
  students: "विद्यार्थी",
  citizens: "नागरिक",
  schemeApplicants: "योजना अर्जदार",
  quickLinks: "द्रुत दुवे",
  madeFor: "विद्यार्थी आणि नागरिकांसाठी",
  evolution: "याचे उत्क्रांती",
  
  // User Type Selection
  selectUserType: "मी आहे...",
  studentDesc: "शिष्यवृत्ती, शिक्षण योजना आणि विद्यार्थी सेवा शोधत आहे",
  citizenDesc: "सरकारी सेवा, कल्याण योजना आणि नागरिक लाभ शोधत आहे",
  schemeApplicantDesc: "विशिष्ट सरकारी योजनांसाठी अर्ज करू इच्छितो",
  schemeSeekers: "योजना शोधक",
  schemeSeekerDesc: "विशिष्ट सरकारी योजना आणि कार्यक्रमांसाठी अर्ज करा",
  
  // Index Page Specific
  govInitiative: "भारत सरकारचा उपक्रम",
  govAndStudent: "सरकारी व विद्यार्थी",
  helpPlatform: "मदत प्लॅटफॉर्म",
  oneStopAssistance: "भारतभरातील विद्यार्थी आणि नागरिकांसाठी एकत्रित सहाय्य",
  governmentSchemesShort: "सरकारी योजना",
  statesAndUTs: "राज्य आणि केंद्रशासित प्रदेश",
  supportAvailable: "सहाय्य उपलब्ध",
  freeServices: "मोफत सेवा",
  exploreAllSchemes: "सर्व योजना पहा",
  whoAreYou: "तुम्ही कोण आहात?",
  chooseCategory: "संबंधित सरकारी योजना आणि सेवा शोधण्यासाठी तुमची श्रेणी निवडा",
  viewSchemes: "योजना पहा",
  popularGovSchemes: "लोकप्रिय सरकारी योजना",
  mostAccessedSchemes: "भारतभरातील नागरिकांद्वारे सर्वाधिक वापरल्या जाणाऱ्या योजना",
  viewAllSchemes: "सर्व योजना पहा",
  trustedByMillions: "लाखो लोकांचा विश्वास",
  citizensHelped: "नागरिकांना मदत",
  applicationsProcessed: "अर्ज प्रक्रिया",
  governmentVerified: "सरकार सत्यापित",
  freeService: "100% मोफत सेवा",
  
  // Location
  selectState: "राज्य निवडा",
  selectDistrict: "जिल्हा निवडा",
  selectTaluka: "तालुका निवडा",
  allIndia: "संपूर्ण भारत",
  search: "शोधा",
  
  // Categories
  categories: "सेवा प्रकार",
  health: "आरोग्य",
  education: "शिक्षण",
  agriculture: "कृषी",
  revenue: "महसूल",
  publicWorks: "सार्वजनिक बांधकाम",
  more: "इतर",
  scholarship: "शिष्यवृत्ती",
  welfare: "कल्याण",
  employment: "रोजगार",
  
  lang: "हि",

  // Filters & Results
  filters: "निवड",
  category: "विभाग",
  getDirections: "मार्गदर्शन",
  workingHours: "कामकाजाची वेळ",
  office: "कार्यालय",
  address: "पत्ता",
  phone: "फोन",
  contactEmail: "संपर्क ईमेल",
  noResults: "तुमच्या निवडीसाठी सेवा सापडल्या नाहीत.",
  
  // About
  aboutTitle: "सरकारी व विद्यार्थी मदत प्लॅटफॉर्म बद्दल",
  aboutBody: "हे प्लॅटफॉर्म भारतभरातील विद्यार्थी आणि नागरिकांना सरकारी योजना, शिष्यवृत्ती आणि सेवा शोधण्यात मदत करते. माहिती data.gov.in, india.gov.in आणि scholarships.gov.in सारख्या अधिकृत स्रोतांमधून नियमितपणे अद्यतनित केली जाते.",
  
  // Contact
  contactTitle: "आमच्याशी संपर्क साधा",
  name: "नाव",
  message: "संदेश",
  submit: "सबमिट",
  support: "मदत",
  supportPhone: "फोन: 1800-111-555",
  supportEmail: "ईमेल: support@govhelpindia.in",
  
  // Government Contacts
  govContacts: "शासन संपर्क",
  cmOffice: "India.gov.in पोर्टल",
  cmPhone: "भारताचे राष्ट्रीय पोर्टल",
  cmEmail: "ईमेल: webmaster@nic.in",
  collectorate: "NSP हेल्पडेस्क",
  collectoratePhone: "फोन: 0120-4200200",
  collectorateEmail: "ईमेल: helpdesk@nsp.gov.in",
  helpline1077: "नागरिक हेल्पलाईन",
  helpline1077Phone: "फोन: 1800-111-555 (मोफत)",
  helpline1077Desc: "24x7 नागरिक सेवा हेल्पलाईन",
  
  // Emergency
  emergencyServices: "आपत्कालीन सेवा",
  police: "पोलीस: 100",
  fire: "अग्निशामक: 101",
  ambulance: "रुग्णवाहिका: 108",
  disasterMgmt: "आपत्ती व्यवस्थापन: 1070",
  
  // Online Services
  onlineServices: "ऑनलाईन सेवा",
  aaplePortal: "भारताचे राष्ट्रीय पोर्टल",
  aaplePortalDesc: "सरकारी सेवांसाठी एक-स्टॉप प्रवेश",
  aaplePortalUrl: "india.gov.in",
  rtcPortal: "राष्ट्रीय शिष्यवृत्ती पोर्टल",
  rtcPortalDesc: "ऑनलाइन शिष्यवृत्तीसाठी अर्ज करा",
  rtcPortalUrl: "scholarships.gov.in",
  
  lang: "हि",

  // Application Form
  applyService: "सेवेसाठी अर्ज करा",
  applicationForm: "अर्ज फॉर्म",
  personalInfo: "वैयक्तिक माहिती",
  fullName: "पूर्ण नाव",
  dateOfBirth: "जन्म तारीख",
  gender: "लिंग",
  male: "पुरुष",
  female: "स्त्री",
  other: "इतर",
  fatherName: "वडिलांचे नाव",
  motherName: "आईचे नाव",
  aadharNumber: "आधार क्रमांक",
  panNumber: "पॅन क्रमांक",
  contactInfo: "संपर्क माहिती",
  mobileNumber: "मोबाईल नंबर",
  alternateNumber: "पर्यायी नंबर",
  emailAddress: "ईमेल पत्ता",
  currentAddress: "सध्याचा पत्ता",
  permanentAddress: "कायमचा पत्ता",
  serviceDetails: "सेवा तपशील",
  serviceType: "सेवेचा प्रकार",
  hospitalService: "हॉस्पिटल सेवा",
  medicalIssue: "वैद्यकीय समस्या/गरज",
  urgencyLevel: "तातडीची पातळी",
  low: "कमी",
  medium: "मध्यम",
  high: "उच्च",
  emergency: "आपत्कालीन",
  preferredDate: "प्राधान्य तारीख",
  preferredTime: "प्राधान्य वेळ",
  documents: "कागदपत्रे",
  uploadDocuments: "आवश्यक कागदपत्रे अपलोड करा",
  idProof: "ओळखपत्र (आधार/पॅन/पासपोर्ट)",
  addressProof: "पत्ता पुरावा",
  incomeProof: "उत्पन्न पुरावा (लागू असल्यास)",
  medicalReports: "वैद्यकीय अहवाल (हॉस्पिटल सेवांसाठी)",
  otherDocuments: "इतर संबंधित कागदपत्रे",
  declaration: "घोषणा",
  declarationText: "मी घोषित करतो की वर दिलेली सर्व माहिती माझ्या माहितीनुसार खरी आणि योग्य आहे.",
  terms: "मी अटी व शर्तींशी सहमत आहे",
  submitApplication: "अर्ज सबमिट करा",
  applicationSuccess: "अर्ज यशस्वीरित्या सबमिट झाला!",
  applicationError: "अर्ज सबमिट करताना त्रुटी. कृपया पुन्हा प्रयत्न करा.",
  required: "आवश्यक",
  apply: "अर्ज करा",

  // Eligibility
  eligibility: "पात्रता",
  eligibilityCriteria: "पात्रता निकष",
  ageRequirement: "वय आवश्यकता",
  incomeRequirement: "उत्पन्न आवश्यकता",
  residenceRequirement: "निवास आवश्यकता",
  documentRequirement: "कागदपत्र आवश्यकता",
  allCitizens: "सर्व नागरिक",
  indianResidents: "भारतीय निवासी",
  districtResidents: "जिल्हा निवासी",
  belowPovertyLine: "दारिद्र्य रेषेखालील (बीपीएल)",
  seniorCitizens: "वृद्ध नागरिक (60+)",
  women: "महिला",
  children: "मुले",
  farmers: "शेतकरी",
  disabled: "दिव्यांग व्यक्ती",
  veterans: "लष्करी पूर्वसैनिक",
  widows: "विधवा",
  singleParents: "एकल पालक",
  unemployed: "बेरोजगार",
  migrantWorkers: "स्थलांतरित कामगार",
  tribalCommunities: "आदिवासी समुदाय",
  scheduledCastes: "अनुसूचित जाती",
  scheduledTribes: "अनुसूचित जमाती",
  otherBackwardClasses: "इतर मागास वर्ग",
  economicallyWeaker: "आर्थिकदृष्ट्या कमकुवत घटक",
  noAgeLimit: "वय मर्यादा नाही",
  yearsAndAbove: "वर्षे आणि वरील",
  yearsAndBelow: "वर्षे आणि खाली",
  betweenYears: "{min} आणि {max} वर्षे दरम्यान",
  annualIncome: "वार्षिक उत्पन्न",
  monthlyIncome: "मासिक उत्पन्न",
  familyIncome: "कौटुंबिक उत्पन्न",
  perCapitaIncome: "प्रति व्यक्ती उत्पन्न",
  lessThan: "पेक्षा कमी",
  moreThan: "पेक्षा जास्त",
  between: "दरम्यान",
  rupees: "रुपये",
  lakhs: "लक्ष",
  crores: "कोटी",
  thousand: "हजार",

  // Documents
  validAddress: "वैध पत्ता पुरावा",
  aadharCard: "आधार कार्ड",
  voterId: "मतदार ओळखपत्र",
  rationCard: "रेशन कार्ड",
  drivingLicense: "चालक परवाना",
  passport: "पासपोर्ट",
  birthCertificate: "जन्म दाखला",
  incomeCertificate: "उत्पन्न दाखला",
  casteCertificate: "जात दाखला",
  domicileCertificate: "मूळगाव दाखला",
  disabilityCertificate: "दिव्यांग दाखला",
  medicalCertificate: "वैद्यकीय दाखला",
  bankPassbook: "बँक पासबुक",
  utilityBill: "उपयोगिता बिल",
  propertyDocument: "मालमत्ता कागदपत्र",
  employmentCertificate: "रोजगार दाखला",
  studentCertificate: "विद्यार्थी दाखला",
  farmerCertificate: "शेतकरी दाखला",
  pensionCertificate: "पेन्शन दाखला",
  widowCertificate: "विधवा दाखला",
  singleParentCertificate: "एकल पालक दाखला",
  unemploymentCertificate: "बेरोजगारी दाखला",
  migrantWorkerCertificate: "स्थलांतरित कामगार दाखला",
  tribalCertificate: "आदिवासी दाखला",
  scStCertificate: "अनुसूचित जाती/जमाती दाखला",
  obcCertificate: "ओबीसी दाखला",
  ewsCertificate: "ईडब्ल्यूएस दाखला",
  and: "आणि",
  or: "किंवा",
  plus: "अधिक",
  additionalDocuments: "अतिरिक्त कागदपत्रे",
  asRequired: "आवश्यकतेनुसार",
  mayBeRequired: "आवश्यक असू शकतात",
  mustBeProvided: "दिले पाहिजेत",
  originalAndCopy: "मूळ आणि प्रत",
  attestedCopy: "प्रमाणित प्रत",
  selfAttested: "स्व-प्रमाणित",
  notarized: "नोटरीकृत",
  recentPhoto: "अलीकडील फोटो",
  passportSize: "पासपोर्ट आकार",
  stampSize: "शिक्का आकार",
  colorPhoto: "रंगीत फोटो",
  blackAndWhite: "काळा आणि पांढरा",
  digitalPhoto: "डिजिटल फोटो",
  physicalPhoto: "भौतिक फोटो",

  // Application Tracking
  trackApplication: "अर्ज ट्रॅक करा",
  trackingId: "ट्रॅकिंग आयडी",
  applicationStatus: "अर्ज स्थिती",
  submitted: "सबमिट केले",
  underReview: "पुनरावलोकनाखाली",
  documentsRequired: "कागदपत्रे आवश्यक",
  approved: "मंजूर",
  rejected: "नाकारले",
  completed: "पूर्ण",
  cancelled: "रद्द",
  applicantName: "अर्जदाराचे नाव",
  submittedDate: "सबमिट तारीख",
  estimatedCompletion: "अंदाजे पूर्णता",
  currentStatus: "सध्याची स्थिती",
  documentStatus: "कागदपत्र स्थिती",
  applicationTimeline: "अर्ज वेळरेषा",
  trackById: "आयडीने ट्रॅक करा",
  trackByContact: "संपर्काने ट्रॅक करा",
  findApplications: "अर्ज शोधा",
  noApplicationFound: "या ट्रॅकिंग आयडीशी कोणताही अर्ज सापडला नाही",
  noApplicationsFound: "दिलेल्या संपर्क माहितीशी कोणतेही अर्ज सापडले नाहीत",
  pleaseEnterTrackingId: "कृपया ट्रॅकिंग आयडी प्रविष्ट करा",
  pleaseEnterContactInfo: "कृपया एकतर ईमेल किंवा फोन नंबर प्रविष्ट करा",
  pending: "प्रलंबित",
  
  // Schemes & Scholarships
  schemes: "योजना",
  governmentSchemes: "सरकारी योजना आणि शिष्यवृत्ती",
  browseSchemes: "विद्यार्थी, नागरिक आणि कल्याण लाभार्थ्यांसाठी योजना पहा",
  searchSchemes: "योजना शोधा...",
  showingNearbySchemes: "तुमच्या क्षेत्रात उपलब्ध योजना दाखवत आहे",
  emergencyHelplines: "आपत्कालीन हेल्पलाइन",
  visitWebsite: "वेबसाइट भेट द्या",
  needHelpWithDocuments: "कागदपत्रांसाठी मदत हवी आहे?",
  noSchemesFound: "तुमच्या निकषांशी जुळणाऱ्या योजना सापडल्या नाहीत",
  scholarships: "शिष्यवृत्ती",
  studentSchemes: "विद्यार्थी योजना",
  citizenSchemes: "नागरिक योजना",
  welfareSchemes: "कल्याण योजना",
  
  // Tags
  tagStudent: "विद्यार्थी",
  tagCitizen: "नागरिक",
  tagGovernment: "सरकारी",
  tagScholarship: "शिष्यवृत्ती",
  tagWelfare: "कल्याण",
  tagEducation: "शिक्षण",

  // Document Helper
  documentHelper: "कागदपत्र सहाय्यक",
  documentHelperDesc: "सरकारी कागदपत्रे मिळविण्यासाठी चरण-दर-चरण मार्गदर्शक",
  stepByStepGuide: "चरण-दर-चरण मार्गदर्शक",
  requiredDocuments: "आवश्यक कागदपत्रे",
  processingTime: "प्रक्रिया वेळ",
  fees: "शुल्क",
  documentTip: "टीप: अनेक भेटी टाळण्यासाठी कार्यालयात जाण्यापूर्वी सर्व कागदपत्रे तयार ठेवा",
  
  // Admin Panel
  adminPanel: "प्रशासक पॅनेल",
  manageApplications: "अर्ज आणि योजना व्यवस्थापित करा",
  totalApplications: "एकूण अर्ज",
  recentApplications: "अलीकडील अर्ज",
  loading: "लोड करत आहे...",
  noApplicationsYet: "अद्याप कोणतेही अर्ज नाहीत",
  review: "पुनरावलोकन",
  approve: "मंजूर",
  reject: "नाकारा",
  
  // Document Assistance
  documentAssistance: "कागदपत्र सहाय्य",
  documentAssistanceDesc: "आम्ही तुम्हाला लहान शुल्कासाठी गहाळ कागदपत्रे मिळविण्यात मदत करू शकतो",
  documentAssistanceInfo: "तुम्हाला ज्या कागदपत्रांसाठी मदत हवी आहे ते निवडा.",
  missing: "गहाळ",
  needHelp: "मदत हवी आहे?",
  weCanHelp: "आम्ही तुम्हाला मदत करू शकतो!",
  viewSteps: "चरण-दर-चरण मार्गदर्शक पहा",
  feeSummary: "शुल्क सारांश",
  baseFee: "मूळ शुल्क",
  documentAssistanceFee: "कागदपत्र सहाय्य शुल्क",
  processingFee: "प्रक्रिया शुल्क",
  totalFee: "एकूण शुल्क",
  affordablePricing: "सर्व आवश्यक कागदपत्रे सहजपणे मिळविण्यासाठी परवडणारी किंमत",
  cancelPayment: "पेमेंट रद्द करा",
  proceedToPayment: "पेमेंटसाठी पुढे जा",
  paymentSuccess: "पेमेंट यशस्वी!",
  paymentFailed: "पेमेंट अयशस्वी",
  applicationFee: "अर्ज शुल्क",
  payNow: "आता भरा",
  selectPaymentMethod: "पेमेंट पद्धत निवडा",
  upi: "यूपीआय",
  card: "क्रेडिट/डेबिट कार्ड",
  netBanking: "नेट बँकिंग",
  wallet: "वॉलेट",
  
  // How to Apply
  howToApply: "अर्ज कसा करावा",
  step1: "चरण 1",
  step2: "चरण 2",
  step3: "चरण 3",
  step4: "चरण 4",
  checkEligibility: "पात्रता तपासा",
  gatherDocuments: "कागदपत्रे गोळा करा",
  fillForm: "अर्ज फॉर्म भरा",
  submitAndTrack: "सबमिट करा आणि ट्रॅक करा",
  
  // Tooltips
  tooltipAadhar: "UIDAI द्वारे जारी केलेला 12-अंकी अद्वितीय ओळख क्रमांक",
  tooltipBPL: "दारिद्र्य रेषेखालील - वार्षिक उत्पन्न ₹1 लाखापेक्षा कमी असलेली कुटुंबे",
  tooltipOBC: "इतर मागास वर्ग - सामाजिक आणि शैक्षणिकदृष्ट्या मागास समुदाय",
  tooltipSC: "अनुसूचित जाती - संविधान (अनुसूचित जाती) आदेशात सूचीबद्ध समुदाय",
  tooltipST: "अनुसूचित जमाती - संविधानात सूचीबद्ध आदिवासी समुदाय",
  tooltipEWS: "आर्थिकदृष्ट्या कमकुवत घटक - वार्षिक उत्पन्न ₹8 लाखापेक्षा कमी असलेली कुटुंबे",
  tooltipDomicile: "तुम्ही महाराष्ट्राचे कायमचे रहिवासी आहात हे सिद्ध करणारे प्रमाणपत्र",
  
  // Navigation Keys
  sign_in: "साइन इन",
  sign_out: "साइन आउट",
  dashboard: "डॅशबोर्ड",
  
  // Auth Page Keys (NEW - Task 2.2)
  login: "लॉगिन",
  signup: "साइन अप",
  admin: "प्रशासक",
  email: "ईमेल",
  password: "पासवर्ड",
  displayName: "प्रदर्शन नाव",
  district: "जिल्हा",
  taluka: "तालुका",
  createAccount: "खाते तयार करा",
  pleaseWait: "कृपया प्रतीक्षा करा...",
  welcomeBack: "परत स्वागत आहे!",
  adminAccessOnly: "केवळ प्रशासक प्रवेश",
  restrictedArea: "हे क्षेत्र केवळ अधिकृत सरकारी प्रशासकांसाठी प्रतिबंधित आहे.",
  authenticating: "प्रमाणीकरण करत आहे...",
  adminLogin: "प्रशासक लॉगिन",
  invalidCredentials: "अवैध क्रेडेन्शियल्स",
  loginFailed: "लॉगिन अयशस्वी",
  signupSuccess: "खाते तयार झाले!",
  checkEmail: "तुमचा ईमेल तपासा",
  accountCreated: "खाते तयार झाले! सरकारी व विद्यार्थी मदत प्लॅटफॉर्मवर स्वागत आहे!",
  adminUsername: "प्रशासक वापरकर्तानाव",
  adminPassword: "प्रशासक पासवर्ड",
  enterAdminUsername: "प्रशासक वापरकर्तानाव प्रविष्ट करा",
  enterAdminPassword: "प्रशासक पासवर्ड प्रविष्ट करा",
  enterFullName: "तुमचे पूर्ण नाव प्रविष्ट करा",
  selectDistrictPlaceholder: "जिल्हा निवडा",
  selectTalukaPlaceholder: "तालुका निवडा",
  
  // Admin Panel Keys (NEW - Task 2.2)
  totalUsers: "एकूण वापरकर्ते",
  todayActivity: "आजचे अर्ज",
  pendingReviews: "प्रलंबित अर्ज",
  userManagement: "वापरकर्ता व्यवस्थापन",
  applicationManagement: "अर्ज व्यवस्थापन",
  schemeManagement: "योजना व्यवस्थापन",
  viewDetails: "तपशील पहा",
  deleteUser: "वापरकर्ता हटवा",
  statistics: "सांख्यिकी",
  recentActivity: "अलीकडील क्रियाकलाप",
  quickActions: "द्रुत क्रिया",
  reviewApplications: "अर्जांचे पुनरावलोकन करा",
  addNewScheme: "नवीन योजना जोडा",
  viewReports: "अहवाल पहा",
  adminDashboard: "प्रशासक डॅशबोर्ड",
  comprehensiveManagement: "योजना आणि अर्जांचे सर्वसमावेशक व्यवस्थापन",
  live: "लाइव्ह",
  logout: "लॉगआउट",
  allApplications: "सर्व अर्ज",
  total: "एकूण",
  noApplicationsFound: "कोणतेही अर्ज सापडले नाहीत",
  needsAttention: "लक्ष देणे आवश्यक",
  registeredUsers: "नोंदणीकृत वापरकर्ते",
  allTime: "सर्व काळ",
  receivedToday: "आज प्राप्त झाले",
  manageAllSchemes: "सर्व सरकारी योजना व्यवस्थापित करा",
  allCategories: "सर्व श्रेणी",
  
  // Theme Keys (NEW)
  toggleTheme: "थीम टॉगल करा",
  lightMode: "लाइट",
  darkMode: "डार्क",
  systemMode: "सिस्टम",
  
  // Admin Panel Keys (NEW - Task 2.2)
  allStates: "सर्व राज्ये",
  export: "निर्यात",
  import: "आयात",
  noSchemesFoundFilter: "कोणत्याही योजना सापडल्या नाहीत",
  adjustFilters: "फिल्टर समायोजित करा किंवा नवीन योजना जोडा",
  manageAllApplications: "सर्व वापरकर्ता अर्ज व्यवस्थापित करा",
  refresh: "रिफ्रेश",
  needDocs: "कागदपत्रे आवश्यक",
  users: "वापरकर्ते",
  andMoreUsers: "आणि {count} अधिक वापरकर्ते...",
  noDistrict: "जिल्हा नाही",
  categoryDistribution: "श्रेणी वितरण",
  applicationStatusLabel: "अर्ज स्थिती",
  systemSettings: "सिस्टम सेटिंग्ज",
  platformConfiguration: "प्लॅटफॉर्म कॉन्फिगरेशन",
  defaultLanguage: "डीफॉल्ट भाषा",
  maxUploadSize: "कमाल अपलोड आकार",
  securitySettings: "सुरक्षा सेटिंग्ज",
  twoFactorAuth: "दोन-घटक प्रमाणीकरण",
  enableForSecurity: "अतिरिक्त सुरक्षेसाठी सक्षम करा",
  enable: "सक्षम करा",
  sessionTimeout: "सत्र कालबाह्यता",
  autoLogout: "निष्क्रियतेनंतर स्वयं लॉगआउट",
  saveSettings: "सेटिंग्ज जतन करा",
  analytics: "विश्लेषण",
  settings: "सेटिंग्ज",
  
  // Common UI Keys (NEW - Task 1)
  save: "जतन करा",
  cancel: "रद्द करा",
  edit: "संपादित करा",
  delete: "हटवा",
  confirm: "पुष्टी करा",
  back: "मागे",
  next: "पुढे",
  previous: "मागील",
  close: "बंद करा",
  open: "उघडा",
  yes: "होय",
  no: "नाही",
  ok: "ठीक आहे",
  error: "त्रुटी",
  success: "यशस्वी",
  warning: "चेतावणी",
  info: "माहिती",
  processing: "प्रक्रिया करत आहे...",
  
  // Services & About Page Keys (NEW - Task 1)
  allServices: "सर्व सेवा",
  serviceCategories: "सेवा श्रेणी",
  popularServices: "लोकप्रिय सेवा",
  mission: "ध्येय",
  vision: "दृष्टी",
  features: "वैशिष्ट्ये",
  howItWorks: "हे कसे कार्य करते",
  
  // Contact Page Keys (NEW - Task 1)
  getInTouch: "संपर्कात रहा",
  sendMessage: "संदेश पाठवा",
  yourName: "तुमचे नाव",
  yourEmail: "तुमचा ईमेल",
  yourMessage: "तुमचा संदेश",
  messageSent: "संदेश पाठवला",
  
  // AI Assistant Keys (NEW - Task 1)
  aiWelcome: "स्वागत आहे! मी तुम्हाला सरकारी योजना आणि सेवा शोधण्यात मदत करण्यासाठी येथे आहे. मी तुम्हाला आज कशी मदत करू शकतो?",
  aiHelp: "मी तुम्हाला योजना शोधण्यात, पात्रता तपासण्यात आणि सरकारी सेवांबद्दल प्रश्नांची उत्तरे देण्यात मदत करू शकतो.",
  aiCommands: "उपलब्ध आदेश: /schemes, /eligibility, /apply, /track, /help",
  askQuestion: "प्रश्न विचारा",
  typeMessage: "तुमचा संदेश टाइप करा",
};


// Hindi translations (comprehensive)
const hindiStrings: Record<string, string> = {
  home: "होम",
  services: "सेवाएं",
  about: "के बारे में",
  contact: "संपर्क",
  findSchemes: "योजनाएं खोजें",
  appName: "सरकारी व छात्र सहायता",
  tagline: "छात्रों और नागरिकों के लिए एकीकृत सहायता",
  heroTitle: "सरकारी सेवाएं, योजनाएं और छात्रवृत्ति खोजें",
  heroDesc: "भारत भर के छात्रों और नागरिकों के लिए केंद्रीय और राज्य सरकार की योजनाएं, छात्रवृत्ति और सेवाएं खोजें।",
  forWhom: "यह किसके लिए है?",
  students: "छात्र",
  citizens: "नागरिक",
  schemeApplicants: "योजना आवेदक",
  quickLinks: "त्वरित लिंक",
  madeFor: "छात्रों और नागरिकों के लिए",
  evolution: "इसका विकास",
  selectUserType: "मैं हूं...",
  studentDesc: "छात्रवृत्ति, शिक्षा योजनाएं और छात्र सेवाएं खोज रहा हूं",
  citizenDesc: "सरकारी सेवाएं, कल्याण योजनाएं और नागरिक लाभ खोज रहा हूं",
  schemeApplicantDesc: "विशिष्ट सरकारी योजनाओं के लिए आवेदन करना चाहता हूं",
  schemeSeekers: "योजना आवेदक",
  schemeSeekerDesc: "विशिष्ट सरकारी योजनाओं और कार्यक्रमों के लिए आवेदन करें",
  
  // Index Page Specific
  govInitiative: "भारत सरकार की पहल",
  govAndStudent: "सरकारी व छात्र",
  helpPlatform: "सहायता प्लेटफॉर्म",
  oneStopAssistance: "भारत भर के छात्रों और नागरिकों के लिए एकीकृत सहायता",
  governmentSchemesShort: "सरकारी योजनाएं",
  statesAndUTs: "राज्य और केंद्र शासित प्रदेश",
  supportAvailable: "सहायता उपलब्ध",
  freeServices: "मुफ्त सेवाएं",
  exploreAllSchemes: "सभी योजनाएं देखें",
  whoAreYou: "आप कौन हैं?",
  chooseCategory: "संबंधित सरकारी योजनाओं और सेवाओं को खोजने के लिए अपनी श्रेणी चुनें",
  viewSchemes: "योजनाएं देखें",
  popularGovSchemes: "लोकप्रिय सरकारी योजनाएं",
  mostAccessedSchemes: "भारत भर के नागरिकों द्वारा सबसे अधिक उपयोग की जाने वाली योजनाएं",
  viewAllSchemes: "सभी योजनाएं देखें",
  trustedByMillions: "लाखों लोगों का भरोसा",
  citizensHelped: "नागरिकों की मदद",
  applicationsProcessed: "आवेदन प्रसंस्कृत",
  governmentVerified: "सरकार सत्यापित",
  freeService: "100% मुफ्त सेवा",
  selectState: "राज्य चुनें",
  selectDistrict: "जिला चुनें",
  allIndia: "अखिल भारत",
  search: "खोजें",
  categories: "सेवा श्रेणियां",
  health: "स्वास्थ्य",
  education: "शिक्षा",
  agriculture: "कृषि",
  revenue: "राजस्व",
  publicWorks: "लोक निर्माण",
  more: "और",
  scholarship: "छात्रवृत्ति",
  welfare: "कल्याण",
  employment: "रोजगार",
  lang: "EN/मर",
  schemes: "योजनाएं",
  governmentSchemes: "सरकारी योजनाएं और छात्रवृत्ति",
  browseSchemes: "छात्रों, नागरिकों और कल्याण लाभार्थियों के लिए योजनाएं देखें",
  searchSchemes: "योजनाएं खोजें...",
  showingNearbySchemes: "आपके क्षेत्र में उपलब्ध योजनाएं दिखा रहे हैं",
  emergencyHelplines: "आपातकालीन हेल्पलाइन",
  visitWebsite: "वेबसाइट पर जाएं",
  needHelpWithDocuments: "दस्तावेजों में मदद चाहिए?",
  noSchemesFound: "आपके मानदंडों से मेल खाने वाली कोई योजना नहीं मिली",
  scholarships: "छात्रवृत्ति",
  studentSchemes: "छात्र योजनाएं",
  citizenSchemes: "नागरिक योजनाएं",
  welfareSchemes: "कल्याण योजनाएं",
  tagStudent: "छात्र",
  tagCitizen: "नागरिक",
  tagGovernment: "सरकारी",
  tagScholarship: "छात्रवृत्ति",
  tagWelfare: "कल्याण",
  tagEducation: "शिक्षा",
  apply: "आवेदन करें",
  eligibility: "पात्रता",
  howToApply: "आवेदन कैसे करें",
  step1: "चरण 1",
  step2: "चरण 2",
  step3: "चरण 3",
  step4: "चरण 4",
  checkEligibility: "पात्रता जांचें",
  gatherDocuments: "दस्तावेज़ इकट्ठा करें",
  fillForm: "आवेदन पत्र भरें",
  submitAndTrack: "जमा करें और ट्रैक करें",
  trackApplication: "आवेदन ट्रैक करें",
  applicationStatus: "आवेदन स्थिति",
  pending: "लंबित",
  approved: "स्वीकृत",
  rejected: "अस्वीकृत",
  adminPanel: "प्रशासक पैनल",
  manageApplications: "आवेदन और योजनाओं का प्रबंधन करें",
  totalApplications: "कुल आवेदन",
  recentApplications: "हाल के आवेदन",
  loading: "लोड हो रहा है...",
  noApplicationsYet: "अभी तक कोई आवेदन नहीं",
  review: "समीक्षा",
  approve: "स्वीकृत करें",
  reject: "अस्वीकार करें",
  contactTitle: "हमसे संपर्क करें",
  name: "नाम",
  message: "संदेश",
  submit: "जमा करें",
  support: "सहायता",
  supportPhone: "फोन: 1077 (24x7 नागरिक हेल्पलाइन)",
  supportEmail: "ईमेल: support@govhelp.in",
  govContacts: "सरकारी संपर्क",
  helpline1077: "राष्ट्रीय नागरिक हेल्पलाइन",
  helpline1077Phone: "फोन: 1077 (24x7 मुफ्त)",
  helpline1077Desc: "सभी सरकारी सेवाओं की हेल्पलाइन",
  emergencyServices: "आपातकालीन सेवाएं",
  police: "पुलिस: 100",
  fire: "दमकल: 101",
  ambulance: "एम्बुलेंस: 108",
  disasterMgmt: "आपदा प्रबंधन: 1070",
  aboutTitle: "सरकारी व छात्र सहायता प्लेटफॉर्म के बारे में",
  aboutBody: "यह प्लेटफॉर्म भारत भर के छात्रों और नागरिकों को सरकारी योजनाएं, छात्रवृत्ति और सेवाएं खोजने में मदद करता है। जानकारी नियमित रूप से india.gov.in, scholarships.gov.in और मंत्रालय की वेबसाइटों जैसे आधिकारिक स्रोतों से अपडेट की जाती है।",
  
  // Authentication
  sign_in: "साइन इन",
  sign_out: "साइन आउट",
  dashboard: "डैशबोर्ड",
  
  // Auth Page Keys (NEW - Task 2.1)
  login: "लॉगिन",
  signup: "साइन अप",
  admin: "प्रशासक",
  email: "ईमेल",
  password: "पासवर्ड",
  displayName: "प्रदर्शन नाम",
  district: "जिला",
  taluka: "तालुका",
  createAccount: "खाता बनाएं",
  pleaseWait: "कृपया प्रतीक्षा करें...",
  welcomeBack: "वापसी पर स्वागत है!",
  adminAccessOnly: "केवल प्रशासक पहुंच",
  restrictedArea: "यह क्षेत्र केवल अधिकृत सरकारी प्रशासकों के लिए प्रतिबंधित है।",
  authenticating: "प्रमाणीकरण हो रहा है...",
  adminLogin: "प्रशासक लॉगिन",
  invalidCredentials: "अमान्य प्रमाण पत्र",
  loginFailed: "लॉगिन विफल",
  signupSuccess: "खाता बनाया गया!",
  checkEmail: "अपना ईमेल जांचें",
  accountCreated: "खाता बनाया गया! सरकारी व छात्र सहायता प्लेटफॉर्म में आपका स्वागत है!",
  adminUsername: "प्रशासक उपयोगकर्ता नाम",
  adminPassword: "प्रशासक पासवर्ड",
  enterAdminUsername: "प्रशासक उपयोगकर्ता नाम दर्ज करें",
  enterAdminPassword: "प्रशासक पासवर्ड दर्ज करें",
  enterFullName: "अपना पूरा नाम दर्ज करें",
  selectDistrictPlaceholder: "जिला चुनें",
  selectTalukaPlaceholder: "तालुका चुनें",
  
  // Admin Panel Keys (NEW - Task 2.1)
  totalUsers: "कुल उपयोगकर्ता",
  todayActivity: "आज के आवेदन",
  pendingReviews: "लंबित आवेदन",
  userManagement: "उपयोगकर्ता प्रबंधन",
  applicationManagement: "आवेदन प्रबंधन",
  schemeManagement: "योजना प्रबंधन",
  viewDetails: "विवरण देखें",
  deleteUser: "उपयोगकर्ता हटाएं",
  statistics: "सांख्यिकी",
  recentActivity: "हाल की गतिविधि",
  quickActions: "त्वरित कार्य",
  reviewApplications: "आवेदन समीक्षा",
  addNewScheme: "नई योजना जोड़ें",
  viewReports: "रिपोर्ट देखें",
  adminDashboard: "प्रशासक डैशबोर्ड",
  comprehensiveManagement: "योजनाओं और आवेदनों का व्यापक प्रबंधन",
  live: "लाइव",
  logout: "लॉगआउट",
  allApplications: "सभी आवेदन",
  total: "कुल",
  noApplicationsFound: "कोई आवेदन नहीं मिला",
  needsAttention: "ध्यान देने की आवश्यकता",
  registeredUsers: "पंजीकृत उपयोगकर्ता",
  allTime: "सभी समय",
  receivedToday: "आज प्राप्त",
  manageAllSchemes: "सभी सरकारी योजनाओं को प्रबंधित करें",
  allCategories: "सभी श्रेणियां",
  allStates: "सभी राज्य",
  export: "निर्यात",
  import: "आयात",
  noSchemesFoundFilter: "कोई योजना नहीं मिली",
  adjustFilters: "फ़िल्टर समायोजित करें या नई योजना जोड़ें",
  manageAllApplications: "सभी उपयोगकर्ता आवेदनों को प्रबंधित करें",
  refresh: "रिफ्रेश",
  needDocs: "दस्तावेज़ चाहिए",
  users: "उपयोगकर्ता",
  andMoreUsers: "और {count} अधिक उपयोगकर्ता...",
  noDistrict: "कोई जिला नहीं",
  categoryDistribution: "श्रेणी वितरण",
  applicationStatusLabel: "आवेदन स्थिति",
  systemSettings: "सिस्टम सेटिंग्स",
  platformConfiguration: "प्लेटफॉर्म कॉन्फ़िगरेशन",
  defaultLanguage: "डिफ़ॉल्ट भाषा",
  maxUploadSize: "अधिकतम अपलोड आकार",
  securitySettings: "सुरक्षा सेटिंग्स",
  twoFactorAuth: "दो-कारक प्रमाणीकरण",
  enableForSecurity: "अतिरिक्त सुरक्षा के लिए सक्षम करें",
  enable: "सक्षम करें",
  sessionTimeout: "सत्र समय सीमा",
  autoLogout: "निष्क्रियता के बाद स्वचालित लॉगआउट",
  saveSettings: "सेटिंग्स सहेजें",
  analytics: "विश्लेषण",
  settings: "सेटिंग्स",
  
  // Common UI Keys (NEW - Task 2.1)
  save: "सहेजें",
  cancel: "रद्द करें",
  edit: "संपादित करें",
  delete: "हटाएं",
  confirm: "पुष्टि करें",
  back: "वापस",
  next: "अगला",
  previous: "पिछला",
  close: "बंद करें",
  open: "खोलें",
  yes: "हां",
  no: "नहीं",
  ok: "ठीक है",
  error: "त्रुटि",
  success: "सफलता",
  warning: "चेतावनी",
  info: "जानकारी",
  processing: "प्रसंस्करण...",
  
  // Services & About Page Keys (NEW - Task 2.1)
  allServices: "सभी सेवाएं",
  serviceCategories: "सेवा श्रेणियां",
  popularServices: "लोकप्रिय सेवाएं",
  mission: "मिशन",
  vision: "दृष्टि",
  features: "विशेषताएं",
  howItWorks: "यह कैसे काम करता है",
  
  // Contact Page Keys (NEW - Task 2.1)
  getInTouch: "संपर्क में रहें",
  sendMessage: "संदेश भेजें",
  yourName: "आपका नाम",
  yourEmail: "आपका ईमेल",
  yourMessage: "आपका संदेश",
  messageSent: "संदेश भेजा गया",
  
  // AI Assistant Keys (NEW - Task 2.1)
  aiWelcome: "स्वागत है! मैं आपको सरकारी योजनाएं और सेवाएं खोजने में मदद करने के लिए यहां हूं। आज मैं आपकी कैसे सहायता कर सकता हूं?",
  aiHelp: "मैं आपको योजनाएं खोजने, पात्रता जांचने और सरकारी सेवाओं के बारे में प्रश्नों के उत्तर देने में मदद कर सकता हूं।",
  aiCommands: "उपलब्ध कमांड: /schemes, /eligibility, /apply, /track, /help",
  askQuestion: "एक प्रश्न पूछें",
  typeMessage: "अपना संदेश टाइप करें",
  
  // Theme Keys (NEW)
  toggleTheme: "थीम टॉगल करें",
  lightMode: "लाइट",
  darkMode: "डार्क",
  systemMode: "सिस्टम",
};

// Bengali translations (comprehensive)
const bengaliStrings: Record<string, string> = {
  home: "হোম",
  services: "সেবা",
  about: "সম্পর্কে",
  contact: "যোগাযোগ",
  findSchemes: "প্রকল্প খুঁজুন",
  appName: "সরকারি ও ছাত্র সহায়তা",
  tagline: "ছাত্র এবং নাগরিকদের জন্য একীভূত সহায়তা",
  heroTitle: "সরকারি প্রকল্প, বৃত্তি এবং সেবা খুঁজুন",
  heroDesc: "ভারত জুড়ে ছাত্র এবং নাগরিকদের জন্য কেন্দ্রীয় এবং রাজ্য সরকারের প্রকল্প, বৃত্তি এবং সেবা আবিষ্কার করুন।",
  
  forWhom: "এটি কার জন্য?",
  students: "ছাত্রছাত্রী",
  citizens: "নাগরিক",
  schemeApplicants: "প্রকল্প আবেদনকারী",
  quickLinks: "দ্রুত লিঙ্ক",
  madeFor: "ছাত্র এবং নাগরিকদের জন্য তৈরি",
  evolution: "বিবর্তন",
  
  selectUserType: "আমি একজন...",
  studentDesc: "বৃত্তি, শিক্ষা প্রকল্প এবং ছাত্র সেবা খুঁজছি",
  citizenDesc: "সরকারি সেবা, কল্যাণ প্রকল্প এবং নাগরিক সুবিধা খুঁজছি",
  schemeApplicantDesc: "নির্দিষ্ট সরকারি প্রকল্পের জন্য আবেদন করতে চাই",
  schemeSeekers: "প্রকল্প আবেদনকারী",
  schemeSeekerDesc: "নির্দিষ্ট সরকারি প্রকল্প এবং কর্মসূচির জন্য আবেদন করুন",
  
  govInitiative: "ভারত সরকারের উদ্যোগ",
  govAndStudent: "সরকারি ও ছাত্র",
  helpPlatform: "সহায়তা প্ল্যাটফর্ম",
  oneStopAssistance: "ভারত জুড়ে ছাত্র এবং নাগরিকদের জন্য একীভূত সহায়তা",
  governmentSchemesShort: "সরকারি প্রকল্প",
  statesAndUTs: "রাজ্য এবং কেন্দ্রশাসিত অঞ্চল",
  supportAvailable: "সহায়তা উপলব্ধ",
  freeServices: "বিনামূল্যে সেবা",
  exploreAllSchemes: "সমস্ত প্রকল্প দেখুন",
  whoAreYou: "আপনি কে?",
  chooseCategory: "প্রাসঙ্গিক সরকারি প্রকল্প এবং সেবা খুঁজতে আপনার বিভাগ চয়ন করুন",
  viewSchemes: "প্রকল্প দেখুন",
  popularGovSchemes: "জনপ্রিয় সরকারি প্রকল্প",
  mostAccessedSchemes: "ভারত জুড়ে নাগরিকদের দ্বারা সর্বাধিক ব্যবহৃত প্রকল্প",
  viewAllSchemes: "সমস্ত প্রকল্প দেখুন",
  trustedByMillions: "লক্ষ লক্ষ মানুষের বিশ্বাস",
  citizensHelped: "নাগরিকদের সাহায্য করা হয়েছে",
  applicationsProcessed: "আবেদন প্রক্রিয়াকৃত",
  governmentVerified: "সরকার যাচাইকৃত",
  freeService: "100% বিনামূল্যে সেবা",
  
  selectState: "রাজ্য নির্বাচন করুন",
  selectDistrict: "জেলা নির্বাচন করুন",
  allIndia: "সমগ্র ভারত",
  search: "অনুসন্ধান",
  
  categories: "সেবা বিভাগ",
  health: "স্বাস্থ্য",
  education: "শিক্ষা",
  agriculture: "কৃষি",
  revenue: "রাজস্ব",
  publicWorks: "জনকার্য",
  more: "আরও",
  scholarship: "বৃত্তি",
  welfare: "কল্যাণ",
  employment: "কর্মসংস্থান",
  
  lang: "EN/हि",
  
  schemes: "প্রকল্প",
  governmentSchemes: "সরকারি প্রকল্প এবং বৃত্তি",
  browseSchemes: "ছাত্র, নাগরিক এবং কল্যাণ সুবিধাভোগীদের জন্য প্রকল্প ব্রাউজ করুন",
  searchSchemes: "প্রকল্প খুঁজুন...",
  showingNearbySchemes: "আপনার এলাকায় উপলব্ধ প্রকল্প দেখানো হচ্ছে",
  emergencyHelplines: "জরুরি হেল্পলাইন",
  visitWebsite: "ওয়েবসাইট দেখুন",
  needHelpWithDocuments: "নথিতে সাহায্য প্রয়োজন?",
  noSchemesFound: "আপনার মানদণ্ডের সাথে মিলে এমন কোনো প্রকল্প পাওয়া যায়নি",
  scholarships: "বৃত্তি",
  studentSchemes: "ছাত্র প্রকল্প",
  citizenSchemes: "নাগরিক প্রকল্প",
  welfareSchemes: "কল্যাণ প্রকল্প",
  
  tagStudent: "ছাত্র",
  tagCitizen: "নাগরিক",
  tagGovernment: "সরকারি",
  tagScholarship: "বৃত্তি",
  tagWelfare: "কল্যাণ",
  tagEducation: "শিক্ষা",
  
  apply: "আবেদন করুন",
  eligibility: "যোগ্যতা",
  howToApply: "কীভাবে আবেদন করবেন",
  step1: "ধাপ 1",
  step2: "ধাপ 2",
  step3: "ধাপ 3",
  step4: "ধাপ 4",
  checkEligibility: "যোগ্যতা পরীক্ষা করুন",
  gatherDocuments: "নথি সংগ্রহ করুন",
  fillForm: "আবেদন ফর্ম পূরণ করুন",
  submitAndTrack: "জমা দিন এবং ট্র্যাক করুন",
  trackApplication: "আবেদন ট্র্যাক করুন",
  applicationStatus: "আবেদনের অবস্থা",
  pending: "অপেক্ষমাণ",
  approved: "অনুমোদিত",
  rejected: "প্রত্যাখ্যাত",
  
  adminPanel: "প্রশাসক প্যানেল",
  manageApplications: "আবেদন এবং প্রকল্প পরিচালনা করুন",
  totalApplications: "মোট আবেদন",
  recentApplications: "সাম্প্রতিক আবেদন",
  loading: "লোড হচ্ছে...",
  noApplicationsYet: "এখনও কোনো আবেদন নেই",
  review: "পর্যালোচনা",
  approve: "অনুমোদন করুন",
  reject: "প্রত্যাখ্যান করুন",
  
  contactTitle: "আমাদের সাথে যোগাযোগ করুন",
  name: "নাম",
  message: "বার্তা",
  submit: "জমা দিন",
  support: "সহায়তা",
  supportPhone: "ফোন: 1077 (24x7 নাগরিক হেল্পলাইন)",
  supportEmail: "ইমেল: support@govhelp.in",
  
  govContacts: "সরকারি যোগাযোগ",
  helpline1077: "জাতীয় নাগরিক হেল্পলাইন",
  helpline1077Phone: "ফোন: 1077 (24x7 বিনামূল্যে)",
  helpline1077Desc: "সমস্ত সরকারি সেবা হেল্পলাইন",
  
  emergencyServices: "জরুরি সেবা",
  police: "পুলিশ: 100",
  fire: "ফায়ার: 101",
  ambulance: "অ্যাম্বুলেন্স: 108",
  disasterMgmt: "দুর্যোগ ব্যবস্থাপনা: 1070",
  
  aboutTitle: "সরকারি ও ছাত্র সহায়তা প্ল্যাটফর্ম সম্পর্কে",
  aboutBody: "এই প্ল্যাটফর্মটি ভারত জুড়ে ছাত্র এবং নাগরিকদের সরকারি প্রকল্প, বৃত্তি এবং সেবা খুঁজে পেতে সাহায্য করে। তথ্য নিয়মিত india.gov.in, scholarships.gov.in এবং মন্ত্রণালয়ের ওয়েবসাইটের মতো সরকারি উৎস থেকে আপডেট করা হয়।",
  
  // Authentication
  sign_in: "সাইন ইন",
  sign_out: "সাইন আউট",
  dashboard: "ড্যাশবোর্ড",
  
  // Auth Page Keys (NEW - Task 2.3)
  login: "লগইন",
  signup: "সাইন আপ",
  admin: "প্রশাসক",
  email: "ইমেল",
  password: "পাসওয়ার্ড",
  displayName: "প্রদর্শন নাম",
  district: "জেলা",
  taluka: "তালুকা",
  createAccount: "অ্যাকাউন্ট তৈরি করুন",
  pleaseWait: "অনুগ্রহ করে অপেক্ষা করুন...",
  welcomeBack: "ফিরে আসার জন্য স্বাগতম!",
  adminAccessOnly: "শুধুমাত্র প্রশাসক অ্যাক্সেস",
  restrictedArea: "এই এলাকাটি শুধুমাত্র অনুমোদিত সরকারি প্রশাসকদের জন্য সীমাবদ্ধ।",
  authenticating: "প্রমাণীকরণ হচ্ছে...",
  adminLogin: "প্রশাসক লগইন",
  invalidCredentials: "অবৈধ শংসাপত্র",
  loginFailed: "লগইন ব্যর্থ",
  signupSuccess: "অ্যাকাউন্ট তৈরি হয়েছে!",
  checkEmail: "আপনার ইমেল চেক করুন",
  accountCreated: "অ্যাকাউন্ট তৈরি হয়েছে! সরকারি ও ছাত্র সহায়তা প্ল্যাটফর্মে আপনাকে স্বাগতম!",
  adminUsername: "প্রশাসক ব্যবহারকারীর নাম",
  adminPassword: "প্রশাসক পাসওয়ার্ড",
  enterAdminUsername: "প্রশাসক ব্যবহারকারীর নাম লিখুন",
  enterAdminPassword: "প্রশাসক পাসওয়ার্ড লিখুন",
  enterFullName: "আপনার পূর্ণ নাম লিখুন",
  selectDistrictPlaceholder: "জেলা নির্বাচন করুন",
  selectTalukaPlaceholder: "তালুকা নির্বাচন করুন",
  
  // Admin Panel Keys (NEW - Task 2.3)
  totalUsers: "মোট ব্যবহারকারী",
  todayActivity: "আজকের আবেদন",
  pendingReviews: "অপেক্ষমাণ আবেদন",
  userManagement: "ব্যবহারকারী ব্যবস্থাপনা",
  applicationManagement: "আবেদন ব্যবস্থাপনা",
  schemeManagement: "প্রকল্প ব্যবস্থাপনা",
  viewDetails: "বিস্তারিত দেখুন",
  deleteUser: "ব্যবহারকারী মুছুন",
  statistics: "পরিসংখ্যান",
  recentActivity: "সাম্প্রতিক কার্যকলাপ",
  quickActions: "দ্রুত কর্ম",
  reviewApplications: "আবেদন পর্যালোচনা",
  addNewScheme: "নতুন প্রকল্প যোগ করুন",
  viewReports: "রিপোর্ট দেখুন",
  adminDashboard: "প্রশাসক ড্যাশবোর্ড",
  comprehensiveManagement: "প্রকল্প এবং আবেদনের ব্যাপক ব্যবস্থাপনা",
  live: "লাইভ",
  logout: "লগআউট",
  allApplications: "সমস্ত আবেদন",
  total: "মোট",
  noApplicationsFound: "কোনো আবেদন পাওয়া যায়নি",
  needsAttention: "মনোযোগ প্রয়োজন",
  registeredUsers: "নিবন্ধিত ব্যবহারকারী",
  allTime: "সর্বকালের",
  receivedToday: "আজ প্রাপ্ত",
  manageAllSchemes: "সমস্ত সরকারি প্রকল্প পরিচালনা করুন",
  allCategories: "সমস্ত বিভাগ",
  allStates: "সমস্ত রাজ্য",
  export: "রপ্তানি",
  import: "আমদানি",
  noSchemesFoundFilter: "কোনো প্রকল্প পাওয়া যায়নি",
  adjustFilters: "ফিল্টার সামঞ্জস্য করুন বা নতুন প্রকল্প যোগ করুন",
  manageAllApplications: "সমস্ত ব্যবহারকারী আবেদন পরিচালনা করুন",
  refresh: "রিফ্রেশ",
  needDocs: "নথি প্রয়োজন",
  users: "ব্যবহারকারী",
  andMoreUsers: "এবং {count} আরও ব্যবহারকারী...",
  noDistrict: "কোনো জেলা নেই",
  categoryDistribution: "বিভাগ বিতরণ",
  applicationStatusLabel: "আবেদনের অবস্থা",
  systemSettings: "সিস্টেম সেটিংস",
  platformConfiguration: "প্ল্যাটফর্ম কনফিগারেশন",
  defaultLanguage: "ডিফল্ট ভাষা",
  maxUploadSize: "সর্বোচ্চ আপলোড আকার",
  securitySettings: "নিরাপত্তা সেটিংস",
  twoFactorAuth: "দুই-ফ্যাক্টর প্রমাণীকরণ",
  enableForSecurity: "অতিরিক্ত নিরাপত্তার জন্য সক্ষম করুন",
  enable: "সক্ষম করুন",
  sessionTimeout: "সেশন টাইমআউট",
  autoLogout: "নিষ্ক্রিয়তার পরে স্বয়ংক্রিয় লগআউট",
  saveSettings: "সেটিংস সংরক্ষণ করুন",
  analytics: "বিশ্লেষণ",
  settings: "সেটিংস",
  
  // Common UI Keys (NEW - Task 2.3)
  save: "সংরক্ষণ করুন",
  cancel: "বাতিল করুন",
  edit: "সম্পাদনা করুন",
  delete: "মুছুন",
  confirm: "নিশ্চিত করুন",
  back: "পিছনে",
  next: "পরবর্তী",
  previous: "পূর্ববর্তী",
  close: "বন্ধ করুন",
  open: "খুলুন",
  yes: "হ্যাঁ",
  no: "না",
  ok: "ঠিক আছে",
  error: "ত্রুটি",
  success: "সফলতা",
  warning: "সতর্কতা",
  info: "তথ্য",
  processing: "প্রক্রিয়াকরণ...",
  
  // Services & About Page Keys (NEW - Task 2.3)
  allServices: "সমস্ত সেবা",
  serviceCategories: "সেবা বিভাগ",
  popularServices: "জনপ্রিয় সেবা",
  mission: "মিশন",
  vision: "দৃষ্টিভঙ্গি",
  features: "বৈশিষ্ট্য",
  howItWorks: "এটি কীভাবে কাজ করে",
  
  // Contact Page Keys (NEW - Task 2.3)
  getInTouch: "যোগাযোগ করুন",
  sendMessage: "বার্তা পাঠান",
  yourName: "আপনার নাম",
  yourEmail: "আপনার ইমেল",
  yourMessage: "আপনার বার্তা",
  messageSent: "বার্তা পাঠানো হয়েছে",
  
  // AI Assistant Keys (NEW - Task 2.3)
  aiWelcome: "স্বাগতম! আমি আপনাকে সরকারি প্রকল্প এবং সেবা খুঁজে পেতে সাহায্য করতে এখানে আছি। আজ আমি আপনাকে কীভাবে সাহায্য করতে পারি?",
  aiHelp: "আমি আপনাকে প্রকল্প খুঁজতে, যোগ্যতা পরীক্ষা করতে এবং সরকারি সেবা সম্পর্কে প্রশ্নের উত্তর দিতে সাহায্য করতে পারি।",
  aiCommands: "উপলব্ধ কমান্ড: /schemes, /eligibility, /apply, /track, /help",
  askQuestion: "একটি প্রশ্ন জিজ্ঞাসা করুন",
  typeMessage: "আপনার বার্তা টাইপ করুন",
  
  // Theme Keys (NEW)
  toggleTheme: "থিম টগল করুন",
  lightMode: "লাইট",
  darkMode: "ডার্ক",
  systemMode: "সিস্টেম",
};

// Tamil translations (comprehensive)
const tamilStrings: Record<string, string> = {
  ...englishStrings, // Start with English as base
  home: "முகப்பு",
  services: "சேவைகள்",
  about: "பற்றி",
  contact: "தொடர்பு",
  findSchemes: "திட்டங்களைக் கண்டறியவும்",
  appName: "அரசு மற்றும் மாணவர் உதவி",
  tagline: "மாணவர்கள் மற்றும் குடிமக்களுக்கான ஒருங்கிணைந்த உதவி",
  heroTitle: "அரசு திட்டங்கள், உதவித்தொகைகள் மற்றும் சேவைகளைக் கண்டறியவும்",
  heroDesc: "இந்தியா முழுவதும் உள்ள மாணவர்கள் மற்றும் குடிமக்களுக்கான மத்திய மற்றும் மாநில அரசு திட்டங்கள், உதவித்தொகைகள் மற்றும் சேவைகளைக் கண்டறியவும்।",
  forWhom: "இது யாருக்கானது?",
  students: "மாணவர்கள்",
  citizens: "குடிமக்கள்",
  schemeApplicants: "திட்ட விண்ணப்பதாரர்கள்",
  selectUserType: "நான் ஒரு...",
  studentDesc: "உதவித்தொகைகள், கல்வி திட்டங்கள் மற்றும் மாணவர் சேவைகளைத் தேடுகிறேன்",
  citizenDesc: "அரசு சேவைகள், நல்வாழ்வு திட்டங்கள் மற்றும் குடிமக்கள் நலன்களைத் தேடுகிறேன்",
  schemeApplicantDesc: "குறிப்பிட்ட அரசு திட்டங்களுக்கு விண்ணப்பிக்க விரும்புகிறேன்",
  schemeSeekers: "திட்ட விண்ணப்பதாரர்கள்",
  govInitiative: "இந்திய அரசின் முயற்சி",
  govAndStudent: "அரசு மற்றும் மாணவர்",
  helpPlatform: "உதவி தளம்",
  oneStopAssistance: "இந்தியா முழுவதும் உள்ள மாணவர்கள் மற்றும் குடிமக்களுக்கான ஒருங்கிணைந்த உதவி",
  governmentSchemesShort: "அரசு திட்டங்கள்",
  statesAndUTs: "மாநிலங்கள் மற்றும் யூனியன் பிரதேசங்கள்",
  exploreAllSchemes: "அனைத்து திட்டங்களையும் ஆராயுங்கள்",
  whoAreYou: "நீங்கள் யார்?",
  chooseCategory: "தொடர்புடைய அரசு திட்டங்கள் மற்றும் சேவைகளைக் கண்டறிய உங்கள் வகையைத் தேர்ந்தெடுக்கவும்",
  viewSchemes: "திட்டங்களைக் காண்க",
  popularGovSchemes: "பிரபலமான அரசு திட்டங்கள்",
  mostAccessedSchemes: "இந்தியா முழுவதும் உள்ள குடிமக்களால் அதிகம் பயன்படுத்தப்படும் திட்டங்கள்",
  viewAllSchemes: "அனைத்து திட்டங்களையும் காண்க",
  trustedByMillions: "மில்லியன் கணக்கானோரின் நம்பிக்கை",
  citizensHelped: "குடிமக்களுக்கு உதவியது",
  search: "தேடல்",
  health: "சுகாதாரம்",
  education: "கல்வி",
  agriculture: "விவசாயம்",
  scholarship: "உதவித்தொகை",
  welfare: "நலன்",
  employment: "வேலைவாய்ப்பு",
  schemes: "திட்டங்கள்",
  apply: "விண்ணப்பிக்கவும்",
  eligibility: "தகுதி",
  pending: "நிலுவையில்",
  approved: "அங்கீகரிக்கப்பட்டது",
  rejected: "நிராகரிக்கப்பட்டது",
  contactTitle: "எங்களை தொடர்பு கொள்ளுங்கள்",
  name: "பெயர்",
  message: "செய்தி",
  submit: "சமர்ப்பிக்கவும்",
  aboutTitle: "அரசு மற்றும் மாணவர் உதவி தளம் பற்றி",
  aboutBody: "இந்த தளம் இந்தியா முழுவதும் உள்ள மாணவர்கள் மற்றும் குடிமக்கள் அரசு திட்டங்கள், உதவித்தொகைகள் மற்றும் சேவைகளைக் கண்டறிய உதவுகிறது।",
  
  // Authentication
  sign_in: "உள்நுழைய",
  sign_out: "வெளியேறு",
  dashboard: "டாஷ்போர்டு",
  
  // Auth Page Keys (NEW - Task 3.1)
  login: "உள்நுழைவு",
  signup: "பதிவு செய்க",
  admin: "நிர்வாகி",
  email: "மின்னஞ்சல்",
  password: "கடவுச்சொல்",
  displayName: "காட்சி பெயர்",
  district: "மாவட்டம்",
  taluka: "தாலுகா",
  createAccount: "கணக்கை உருவாக்கவும்",
  pleaseWait: "தயவுசெய்து காத்திருக்கவும்...",
  welcomeBack: "மீண்டும் வரவேற்கிறோம்!",
  adminAccessOnly: "நிர்வாகி அணுகல் மட்டும்",
  restrictedArea: "இந்த பகுதி அங்கீகரிக்கப்பட்ட அரசு நிர்வாகிகளுக்கு மட்டுமே கட்டுப்படுத்தப்பட்டுள்ளது.",
  authenticating: "அங்கீகரிக்கப்படுகிறது...",
  adminLogin: "நிர்வாகி உள்நுழைவு",
  invalidCredentials: "தவறான சான்றுகள்",
  loginFailed: "உள்நுழைவு தோல்வியடைந்தது",
  signupSuccess: "கணக்கு உருவாக்கப்பட்டது!",
  checkEmail: "உங்கள் மின்னஞ்சலைச் சரிபார்க்கவும்",
  accountCreated: "கணக்கு உருவாக்கப்பட்டது! அரசு மற்றும் மாணவர் உதவி தளத்திற்கு வரவேற்கிறோம்!",
  adminUsername: "நிர்வாகி பயனர்பெயர்",
  adminPassword: "நிர்வாகி கடவுச்சொல்",
  enterAdminUsername: "நிர்வாகி பயனர்பெயரை உள்ளிடவும்",
  enterAdminPassword: "நிர்வாகி கடவுச்சொல்லை உள்ளிடவும்",
  enterFullName: "உங்கள் முழு பெயரை உள்ளிடவும்",
  selectDistrictPlaceholder: "மாவட்டத்தைத் தேர்ந்தெடுக்கவும்",
  selectTalukaPlaceholder: "தாலுகாவைத் தேர்ந்தெடுக்கவும்",
  
  // Admin Panel Keys (NEW - Task 3.1)
  totalUsers: "மொத்த பயனர்கள்",
  todayActivity: "இன்றைய விண்ணப்பங்கள்",
  pendingReviews: "நிலுவையில் உள்ள விண்ணப்பங்கள்",
  userManagement: "பயனர் மேலாண்மை",
  applicationManagement: "விண்ணப்ப மேலாண்மை",
  schemeManagement: "திட்ட மேலாண்மை",
  viewDetails: "விவரங்களைக் காண்க",
  deleteUser: "பயனரை நீக்கு",
  statistics: "புள்ளிவிவரங்கள்",
  recentActivity: "சமீபத்திய செயல்பாடு",
  quickActions: "விரைவு செயல்கள்",
  reviewApplications: "விண்ணப்பங்களை மதிப்பாய்வு செய்க",
  addNewScheme: "புதிய திட்டத்தைச் சேர்க்கவும்",
  viewReports: "அறிக்கைகளைக் காண்க",
  adminDashboard: "நிர்வாகி டாஷ்போர்டு",
  comprehensiveManagement: "திட்டங்கள் மற்றும் விண்ணப்பங்களின் விரிவான மேலாண்மை",
  live: "நேரலை",
  logout: "வெளியேறு",
  allApplications: "அனைத்து விண்ணப்பங்கள்",
  total: "மொத்தம்",
  noApplicationsFound: "விண்ணப்பங்கள் எதுவும் கிடைக்கவில்லை",
  needsAttention: "கவனம் தேவை",
  registeredUsers: "பதிவு செய்யப்பட்ட பயனர்கள்",
  allTime: "எல்லா காலமும்",
  receivedToday: "இன்று பெறப்பட்டது",
  manageAllSchemes: "அனைத்து அரசு திட்டங்களையும் நிர்வகிக்கவும்",
  allCategories: "அனைத்து வகைகள்",
  allStates: "அனைத்து மாநிலங்கள்",
  export: "ஏற்றுமதி",
  import: "இறக்குமதி",
  noSchemesFoundFilter: "திட்டங்கள் எதுவும் கிடைக்கவில்லை",
  adjustFilters: "வடிப்பான்களை சரிசெய்யவும் அல்லது புதிய திட்டத்தைச் சேர்க்கவும்",
  manageAllApplications: "அனைத்து பயனர் விண்ணப்பங்களையும் நிர்வகிக்கவும்",
  refresh: "புதுப்பிக்கவும்",
  needDocs: "ஆவணங்கள் தேவை",
  users: "பயனர்கள்",
  andMoreUsers: "மற்றும் {count} மேலும் பயனர்கள்...",
  noDistrict: "மாவட்டம் இல்லை",
  categoryDistribution: "வகை விநியோகம்",
  applicationStatusLabel: "விண்ணப்ப நிலை",
  systemSettings: "கணினி அமைப்புகள்",
  platformConfiguration: "தள உள்ளமைவு",
  defaultLanguage: "இயல்புநிலை மொழி",
  maxUploadSize: "அதிகபட்ச பதிவேற்ற அளவு",
  securitySettings: "பாதுகாப்பு அமைப்புகள்",
  twoFactorAuth: "இரு-காரணி அங்கீகாரம்",
  enableForSecurity: "கூடுதல் பாதுகாப்பிற்கு இயக்கவும்",
  enable: "இயக்கு",
  sessionTimeout: "அமர்வு காலாவதி",
  autoLogout: "செயலற்ற நிலைக்குப் பிறகு தானாக வெளியேறு",
  saveSettings: "அமைப்புகளைச் சேமிக்கவும்",
  analytics: "பகுப்பாய்வு",
  settings: "அமைப்புகள்",
  
  // Common UI Keys (NEW - Task 3.1)
  save: "சேமிக்கவும்",
  cancel: "ரத்துசெய்",
  edit: "திருத்து",
  delete: "நீக்கு",
  confirm: "உறுதிப்படுத்து",
  back: "பின்",
  next: "அடுத்து",
  previous: "முந்தைய",
  close: "மூடு",
  open: "திற",
  yes: "ஆம்",
  no: "இல்லை",
  ok: "சரி",
  error: "பிழை",
  success: "வெற்றி",
  warning: "எச்சரிக்கை",
  info: "தகவல்",
  processing: "செயலாக்கப்படுகிறது...",
  
  // Services & About Page Keys (NEW - Task 3.1)
  allServices: "அனைத்து சேவைகள்",
  serviceCategories: "சேவை வகைகள்",
  popularServices: "பிரபலமான சேவைகள்",
  mission: "நோக்கம்",
  vision: "பார்வை",
  features: "அம்சங்கள்",
  howItWorks: "இது எவ்வாறு செயல்படுகிறது",
  
  // Contact Page Keys (NEW - Task 3.1)
  getInTouch: "தொடர்பில் இருங்கள்",
  sendMessage: "செய்தி அனுப்பவும்",
  yourName: "உங்கள் பெயர்",
  yourEmail: "உங்கள் மின்னஞ்சல்",
  yourMessage: "உங்கள் செய்தி",
  messageSent: "செய்தி அனுப்பப்பட்டது",
  
  // AI Assistant Keys (NEW - Task 3.1)
  aiWelcome: "வரவேற்கிறோம்! அரசு திட்டங்கள் மற்றும் சேவைகளைக் கண்டறிய உங்களுக்கு உதவ நான் இங்கே இருக்கிறேன். இன்று நான் உங்களுக்கு எவ்வாறு உதவ முடியும்?",
  aiHelp: "திட்டங்களைக் கண்டறிதல், தகுதியைச் சரிபார்த்தல் மற்றும் அரசு சேவைகள் பற்றிய கேள்விகளுக்கு பதிலளிப்பதில் நான் உங்களுக்கு உதவ முடியும்.",
  aiCommands: "கிடைக்கும் கட்டளைகள்: /schemes, /eligibility, /apply, /track, /help",
  askQuestion: "ஒரு கேள்வி கேளுங்கள்",
  typeMessage: "உங்கள் செய்தியை தட்டச்சு செய்யவும்",
  
  // Theme Keys (NEW)
  toggleTheme: "தீம் மாற்று",
  lightMode: "லைட்",
  darkMode: "டார்க்",
  systemMode: "சிஸ்டம்",
};

// Telugu translations (comprehensive)
const teluguStrings: Record<string, string> = {
  ...englishStrings, // Start with English as base
  home: "హోమ్",
  services: "సేవలు",
  about: "గురించి",
  contact: "సంప్రదింపులు",
  appName: "ప్రభుత్వ మరియు విద్యార్థి సహాయం",
  tagline: "విద్యార్థులు మరియు పౌరులకు సమగ్ర సహాయం",
  heroTitle: "ప్రభుత్వ పథకాలు, స్కాలర్‌షిప్‌లు మరియు సేవలను కనుగొనండి",
  heroDesc: "భారతదేశం అంతటా విద్యార్థులు మరియు పౌరుల కోసం కేంద్ర మరియు రాష్ట్ర ప్రభుత్వ పథకాలు, స్కాలర్‌షిప్‌లు మరియు సేవలను కనుగొనండి।",
  students: "విద్యార్థులు",
  citizens: "పౌరులు",
  schemeApplicants: "పథకం దరఖాస్తుదారులు",
  govInitiative: "భారత ప్రభుత్వ చొరవ",
  govAndStudent: "ప్రభుత్వ మరియు విద్యార్థి",
  helpPlatform: "సహాయ వేదిక",
  oneStopAssistance: "భారతదేశం అంతటా విద్యార్థులు మరియు పౌరులకు సమగ్ర సహాయం",
  exploreAllSchemes: "అన్ని పథకాలను అన్వేషించండి",
  whoAreYou: "మీరు ఎవరు?",
  viewSchemes: "పథకాలను చూడండి",
  search: "వెతకండి",
  health: "ఆరోగ్యం",
  education: "విద్య",
  agriculture: "వ్యవసాయం",
  scholarship: "స్కాలర్‌షిప్",
  welfare: "సంక్షేమం",
  employment: "ఉపాధి",
  schemes: "పథకాలు",
  apply: "దరఖాస్తు చేయండి",
  eligibility: "అర్హత",
  pending: "పెండింగ్‌లో",
  approved: "ఆమోదించబడింది",
  rejected: "తిరస్కరించబడింది",
  contactTitle: "మమ్మల్ని సంప్రదించండి",
  name: "పేరు",
  message: "సందేశం",
  submit: "సమర్పించండి",
  aboutTitle: "ప్రభుత్వ మరియు విద్యార్థి సహాయ వేదిక గురించి",
  aboutBody: "ఈ వేదిక భారతదేశం అంతటా విద్యార్థులు మరియు పౌరులు ప్రభుత్వ పథకాలు, స్కాలర్‌షిప్‌లు మరియు సేవలను కనుగొనడంలో సహాయపడుతుంది।",
  
  // Authentication
  sign_in: "సైన్ ఇన్",
  sign_out: "సైన్ అవుట్",
  dashboard: "డాష్‌బోర్డ్",
  
  // Auth Page Keys (NEW - Task 3.2)
  login: "లాగిన్",
  signup: "సైన్ అప్",
  admin: "నిర్వాహకుడు",
  email: "ఇమెయిల్",
  password: "పాస్‌వర్డ్",
  displayName: "ప్రదర్శన పేరు",
  district: "జిల్లా",
  taluka: "తాలూకా",
  createAccount: "ఖాతా సృష్టించండి",
  pleaseWait: "దయచేసి వేచి ఉండండి...",
  welcomeBack: "తిరిగి స్వాగతం!",
  adminAccessOnly: "నిర్వాహక యాక్సెస్ మాత్రమే",
  restrictedArea: "ఈ ప్రాంతం అధికారం పొందిన ప్రభుత్వ నిర్వాహకులకు మాత్రమే పరిమితం చేయబడింది.",
  authenticating: "ప్రామాణీకరిస్తోంది...",
  adminLogin: "నిర్వాహక లాగిన్",
  invalidCredentials: "చెల్లని ఆధారాలు",
  loginFailed: "లాగిన్ విఫలమైంది",
  signupSuccess: "ఖాతా సృష్టించబడింది!",
  checkEmail: "మీ ఇమెయిల్‌ను తనిఖీ చేయండి",
  accountCreated: "ఖాతా సృష్టించబడింది! ప్రభుత్వ మరియు విద్యార్థి సహాయ వేదికకు స్వాగతం!",
  adminUsername: "నిర్వాహక వినియోగదారు పేరు",
  adminPassword: "నిర్వాహక పాస్‌వర్డ్",
  enterAdminUsername: "నిర్వాహక వినియోగదారు పేరును నమోదు చేయండి",
  enterAdminPassword: "నిర్వాహక పాస్‌వర్డ్‌ను నమోదు చేయండి",
  enterFullName: "మీ పూర్తి పేరును నమోదు చేయండి",
  selectDistrictPlaceholder: "జిల్లాను ఎంచుకోండి",
  selectTalukaPlaceholder: "తాలూకాను ఎంచుకోండి",
  
  // Admin Panel Keys (NEW - Task 3.2)
  totalUsers: "మొత్తం వినియోగదారులు",
  todayActivity: "నేటి దరఖాస్తులు",
  pendingReviews: "పెండింగ్‌లో ఉన్న దరఖాస్తులు",
  userManagement: "వినియోగదారు నిర్వహణ",
  applicationManagement: "దరఖాస్తు నిర్వహణ",
  schemeManagement: "పథకం నిర్వహణ",
  viewDetails: "వివరాలను చూడండి",
  deleteUser: "వినియోగదారుని తొలగించండి",
  statistics: "గణాంకాలు",
  recentActivity: "ఇటీవలి కార్యాచరణ",
  quickActions: "త్వరిత చర్యలు",
  reviewApplications: "దరఖాస్తులను సమీక్షించండి",
  addNewScheme: "కొత్త పథకాన్ని జోడించండి",
  viewReports: "నివేదికలను చూడండి",
  adminDashboard: "నిర్వాహక డాష్‌బోర్డ్",
  comprehensiveManagement: "పథకాలు మరియు దరఖాస్తుల సమగ్ర నిర్వహణ",
  live: "ప్రత్యక్ష",
  logout: "లాగ్అవుట్",
  allApplications: "అన్ని దరఖాస్తులు",
  total: "మొత్తం",
  noApplicationsFound: "దరఖాస్తులు కనుగొనబడలేదు",
  needsAttention: "శ్రద్ధ అవసరం",
  registeredUsers: "నమోదిత వినియోగదారులు",
  allTime: "అన్ని సమయాలు",
  receivedToday: "నేడు స్వీకరించబడింది",
  manageAllSchemes: "అన్ని ప్రభుత్వ పథకాలను నిర్వహించండి",
  allCategories: "అన్ని వర్గాలు",
  allStates: "అన్ని రాష్ట్రాలు",
  export: "ఎగుమతి",
  import: "దిగుమతి",
  noSchemesFoundFilter: "పథకాలు కనుగొనబడలేదు",
  adjustFilters: "ఫిల్టర్‌లను సర్దుబాటు చేయండి లేదా కొత్త పథకాన్ని జోడించండి",
  manageAllApplications: "అన్ని వినియోగదారు దరఖాస్తులను నిర్వహించండి",
  refresh: "రిఫ్రెష్",
  needDocs: "పత్రాలు అవసరం",
  users: "వినియోగదారులు",
  andMoreUsers: "మరియు {count} మరిన్ని వినియోగదారులు...",
  noDistrict: "జిల్లా లేదు",
  categoryDistribution: "వర్గం పంపిణీ",
  applicationStatusLabel: "దరఖాస్తు స్థితి",
  systemSettings: "సిస్టమ్ సెట్టింగ్‌లు",
  platformConfiguration: "ప్లాట్‌ఫారమ్ కాన్ఫిగరేషన్",
  defaultLanguage: "డిఫాల్ట్ భాష",
  maxUploadSize: "గరిష్ట అప్‌లోడ్ పరిమాణం",
  securitySettings: "భద్రతా సెట్టింగ్‌లు",
  twoFactorAuth: "రెండు-కారకాల ప్రామాణీకరణ",
  enableForSecurity: "అదనపు భద్రత కోసం ప్రారంభించండి",
  enable: "ప్రారంభించు",
  sessionTimeout: "సెషన్ గడువు ముగింపు",
  autoLogout: "నిష్క్రియత తర్వాత స్వయంచాలకంగా లాగ్అవుట్",
  saveSettings: "సెట్టింగ్‌లను సేవ్ చేయండి",
  analytics: "విశ్లేషణలు",
  settings: "సెట్టింగ్‌లు",
  
  // Common UI Keys (NEW - Task 3.2)
  save: "సేవ్ చేయండి",
  cancel: "రద్దు చేయండి",
  edit: "సవరించు",
  delete: "తొలగించు",
  confirm: "నిర్ధారించు",
  back: "వెనుకకు",
  next: "తదుపరి",
  previous: "మునుపటి",
  close: "మూసివేయి",
  open: "తెరువు",
  yes: "అవును",
  no: "కాదు",
  ok: "సరే",
  error: "లోపం",
  success: "విజయం",
  warning: "హెచ్చరిక",
  info: "సమాచారం",
  processing: "ప్రాసెస్ చేస్తోంది...",
  
  // Services & About Page Keys (NEW - Task 3.2)
  allServices: "అన్ని సేవలు",
  serviceCategories: "సేవా వర్గాలు",
  popularServices: "ప్రసిద్ధ సేవలు",
  mission: "లక్ష్యం",
  vision: "దృష్టి",
  features: "లక్షణాలు",
  howItWorks: "ఇది ఎలా పనిచేస్తుంది",
  
  // Contact Page Keys (NEW - Task 3.2)
  getInTouch: "సంప్రదించండి",
  sendMessage: "సందేశం పంపండి",
  yourName: "మీ పేరు",
  yourEmail: "మీ ఇమెయిల్",
  yourMessage: "మీ సందేశం",
  messageSent: "సందేశం పంపబడింది",
  
  // AI Assistant Keys (NEW - Task 3.2)
  aiWelcome: "స్వాగతం! ప్రభుత్వ పథకాలు మరియు సేవలను కనుగొనడంలో మీకు సహాయం చేయడానికి నేను ఇక్కడ ఉన్నాను. నేడు నేను మీకు ఎలా సహాయం చేయగలను?",
  aiHelp: "పథకాలను కనుగొనడం, అర్హతను తనిఖీ చేయడం మరియు ప్రభుత్వ సేవల గురించి ప్రశ్నలకు సమాధానం ఇవ్వడంలో నేను మీకు సహాయం చేయగలను.",
  aiCommands: "అందుబాటులో ఉన్న ఆదేశాలు: /schemes, /eligibility, /apply, /track, /help",
  askQuestion: "ఒక ప్రశ్న అడగండి",
  typeMessage: "మీ సందేశాన్ని టైప్ చేయండి",
  
  // Theme Keys (NEW)
  toggleTheme: "థీమ్ టోగుల్ చేయండి",
  lightMode: "లైట్",
  darkMode: "డార్క్",
  systemMode: "సిస్టమ్",
};

// Gujarati translations (comprehensive)
const gujaratiStrings: Record<string, string> = {
  ...englishStrings,
  home: "હોમ",
  services: "સેવાઓ",
  about: "વિશે",
  contact: "સંપર્ક",
  appName: "સરકારી અને વિદ્યાર્થી સહાય",
  tagline: "વિદ્યાર્થીઓ અને નાગરિકો માટે એકીકૃત સહાય",
  students: "વિદ્યાર્થીઓ",
  citizens: "નાગરિકો",
  schemeApplicants: "યોજના અરજદારો",
  govInitiative: "ભારત સરકારની પહેલ",
  govAndStudent: "સરકારી અને વિદ્યાર્થી",
  helpPlatform: "સહાય પ્લેટફોર્મ",
  oneStopAssistance: "ભારતભરના વિદ્યાર્થીઓ અને નાગરિકો માટે એકીકૃત સહાય",
  exploreAllSchemes: "બધી યોજનાઓ શોધો",
  whoAreYou: "તમે કોણ છો?",
  viewSchemes: "યોજનાઓ જુઓ",
  search: "શોધો",
  health: "આરોગ્ય",
  education: "શિક્ષણ",
  agriculture: "કૃષિ",
  scholarship: "શિષ્યવૃત્તિ",
  welfare: "કલ્યાણ",
  employment: "રોજગાર",
  schemes: "યોજનાઓ",
  apply: "અરજી કરો",
  eligibility: "પાત્રતા",
  pending: "બાકી",
  approved: "મંજૂર",
  rejected: "નકારવામાં આવ્યું",
  contactTitle: "અમારો સંપર્ક કરો",
  name: "નામ",
  message: "સંદેશ",
  submit: "સબમિટ કરો",
  aboutTitle: "સરકારી અને વિદ્યાર્થી સહાય પ્લેટફોર્મ વિશે",
  aboutBody: "આ પ્લેટફોર્મ ભારતભરના વિદ્યાર્થીઓ અને નાગરિકોને સરકારી યોજનાઓ, શિષ્યવૃત્તિઓ અને સેવાઓ શોધવામાં મદદ કરે છે।",
  
  // Authentication
  sign_in: "સાઇન ઇન",
  sign_out: "સાઇન આઉટ",
  dashboard: "ડેશબોર્ડ",
  
  // Auth Page Keys (NEW - Task 3.3)
  login: "લોગિન",
  signup: "સાઇન અપ",
  admin: "એડમિન",
  email: "ઇમેઇલ",
  password: "પાસવર્ડ",
  displayName: "પ્રદર્શન નામ",
  district: "જિલ્લો",
  taluka: "તાલુકો",
  createAccount: "ખાતું બનાવો",
  pleaseWait: "કૃપા કરીને રાહ જુઓ...",
  welcomeBack: "પાછા સ્વાગત છે!",
  adminAccessOnly: "ફક્ત એડમિન એક્સેસ",
  restrictedArea: "આ વિસ્તાર ફક્ત અધિકૃત સરકારી એડમિનિસ્ટ્રેટર્સ માટે પ્રતિબંધિત છે.",
  authenticating: "પ્રમાણીકરણ કરી રહ્યું છે...",
  adminLogin: "એડમિન લોગિન",
  invalidCredentials: "અમાન્ય ઓળખપત્રો",
  loginFailed: "લોગિન નિષ્ફળ",
  signupSuccess: "ખાતું બનાવ્યું!",
  checkEmail: "તમારું ઇમેઇલ તપાસો",
  accountCreated: "ખાતું બનાવ્યું! સરકારી અને વિદ્યાર્થી સહાય પ્લેટફોર્મમાં આપનું સ્વાગત છે!",
  adminUsername: "એડમિન વપરાશકર્તા નામ",
  adminPassword: "એડમિન પાસવર્ડ",
  enterAdminUsername: "એડમિન વપરાશકર્તા નામ દાખલ કરો",
  enterAdminPassword: "એડમિન પાસવર્ડ દાખલ કરો",
  enterFullName: "તમારું પૂરું નામ દાખલ કરો",
  selectDistrictPlaceholder: "જિલ્લો પસંદ કરો",
  selectTalukaPlaceholder: "તાલુકો પસંદ કરો",
  
  // Admin Panel Keys (NEW - Task 3.3)
  totalUsers: "કુલ વપરાશકર્તાઓ",
  todayActivity: "આજની અરજીઓ",
  pendingReviews: "બાકી અરજીઓ",
  userManagement: "વપરાશકર્તા વ્યવસ્થાપન",
  applicationManagement: "અરજી વ્યવસ્થાપન",
  schemeManagement: "યોજના વ્યવસ્થાપન",
  viewDetails: "વિગતો જુઓ",
  deleteUser: "વપરાશકર્તાને કાઢી નાખો",
  statistics: "આંકડા",
  recentActivity: "તાજેતરની પ્રવૃત્તિ",
  quickActions: "ઝડપી ક્રિયાઓ",
  reviewApplications: "અરજીઓની સમીક્ષા કરો",
  addNewScheme: "નવી યોજના ઉમેરો",
  viewReports: "રિપોર્ટ્સ જુઓ",
  adminDashboard: "એડમિન ડેશબોર્ડ",
  comprehensiveManagement: "યોજનાઓ અને અરજીઓનું વ્યાપક વ્યવસ્થાપન",
  live: "લાઇવ",
  logout: "લોગઆઉટ",
  allApplications: "બધી અરજીઓ",
  total: "કુલ",
  noApplicationsFound: "કોઈ અરજીઓ મળી નથી",
  needsAttention: "ધ્યાન જરૂરી છે",
  registeredUsers: "નોંધાયેલા વપરાશકર્તાઓ",
  allTime: "બધા સમય",
  receivedToday: "આજે પ્રાપ્ત",
  manageAllSchemes: "બધી સરકારી યોજનાઓનું સંચાલન કરો",
  allCategories: "બધી શ્રેણીઓ",
  allStates: "બધા રાજ્યો",
  export: "નિકાસ",
  import: "આયાત",
  noSchemesFoundFilter: "કોઈ યોજનાઓ મળી નથી",
  adjustFilters: "ફિલ્ટર્સ સમાયોજિત કરો અથવા નવી યોજના ઉમેરો",
  manageAllApplications: "બધી વપરાશકર્તા અરજીઓનું સંચાલન કરો",
  refresh: "રિફ્રેશ",
  needDocs: "દસ્તાવેજો જરૂરી",
  users: "વપરાશકર્તાઓ",
  andMoreUsers: "અને {count} વધુ વપરાશકર્તાઓ...",
  noDistrict: "કોઈ જિલ્લો નથી",
  categoryDistribution: "શ્રેણી વિતરણ",
  applicationStatusLabel: "અરજી સ્થિતિ",
  systemSettings: "સિસ્ટમ સેટિંગ્સ",
  platformConfiguration: "પ્લેટફોર્મ રૂપરેખાંકન",
  defaultLanguage: "ડિફોલ્ટ ભાષા",
  maxUploadSize: "મહત્તમ અપલોડ કદ",
  securitySettings: "સુરક્ષા સેટિંગ્સ",
  twoFactorAuth: "બે-પરિબળ પ્રમાણીકરણ",
  enableForSecurity: "વધારાની સુરક્ષા માટે સક્ષમ કરો",
  enable: "સક્ષમ કરો",
  sessionTimeout: "સત્ર સમયસમાપ્તિ",
  autoLogout: "નિષ્ક્રિયતા પછી સ્વચાલિત લોગઆઉટ",
  saveSettings: "સેટિંગ્સ સાચવો",
  analytics: "વિશ્લેષણ",
  settings: "સેટિંગ્સ",
  
  // Common UI Keys (NEW - Task 3.3)
  save: "સાચવો",
  cancel: "રદ કરો",
  edit: "સંપાદિત કરો",
  delete: "કાઢી નાખો",
  confirm: "પુષ્ટિ કરો",
  back: "પાછળ",
  next: "આગળ",
  previous: "પહેલાં",
  close: "બંધ કરો",
  open: "ખોલો",
  yes: "હા",
  no: "ના",
  ok: "ઠીક છે",
  error: "ભૂલ",
  success: "સફળતા",
  warning: "ચેતવણી",
  info: "માહિતી",
  processing: "પ્રક્રિયા કરી રહ્યું છે...",
  
  // Services & About Page Keys (NEW - Task 3.3)
  allServices: "બધી સેવાઓ",
  serviceCategories: "સેવા શ્રેણીઓ",
  popularServices: "લોકપ્રિય સેવાઓ",
  mission: "મિશન",
  vision: "વિઝન",
  features: "લક્ષણો",
  howItWorks: "તે કેવી રીતે કામ કરે છે",
  
  // Contact Page Keys (NEW - Task 3.3)
  getInTouch: "સંપર્કમાં રહો",
  sendMessage: "સંદેશ મોકલો",
  yourName: "તમારું નામ",
  yourEmail: "તમારું ઇમેઇલ",
  yourMessage: "તમારો સંદેશ",
  messageSent: "સંદેશ મોકલ્યો",
  
  // AI Assistant Keys (NEW - Task 3.3)
  aiWelcome: "સ્વાગત છે! સરકારી યોજનાઓ અને સેવાઓ શોધવામાં તમને મદદ કરવા હું અહીં છું. આજે હું તમને કેવી રીતે મદદ કરી શકું?",
  aiHelp: "યોજનાઓ શોધવામાં, પાત્રતા તપાસવામાં અને સરકારી સેવાઓ વિશેના પ્રશ્નોના જવાબ આપવામાં હું તમને મદદ કરી શકું છું.",
  aiCommands: "ઉપલબ્ધ આદેશો: /schemes, /eligibility, /apply, /track, /help",
  askQuestion: "એક પ્રશ્ન પૂછો",
  typeMessage: "તમારો સંદેશ ટાઇપ કરો",
  
  // Theme Keys (NEW)
  toggleTheme: "થીમ ટોગલ કરો",
  lightMode: "લાઇટ",
  darkMode: "ડાર્ક",
  systemMode: "સિસ્ટમ",
};

// Kannada translations (comprehensive)
const kannadaStrings: Record<string, string> = {
  ...englishStrings,
  home: "ಮುಖ್ಯ ಪುಟ",
  services: "ಸೇವೆಗಳು",
  about: "ಬಗ್ಗೆ",
  contact: "ಸಂಪರ್ಕ",
  appName: "ಸರ್ಕಾರಿ ಮತ್ತು ವಿದ್ಯಾರ್ಥಿ ಸಹಾಯ",
  tagline: "ವಿದ್ಯಾರ್ಥಿಗಳು ಮತ್ತು ನಾಗರಿಕರಿಗೆ ಏಕೀಕೃತ ಸಹಾಯ",
  students: "ವಿದ್ಯಾರ್ಥಿಗಳು",
  citizens: "ನಾಗರಿಕರು",
  schemeApplicants: "ಯೋಜನೆ ಅರ್ಜಿದಾರರು",
  govInitiative: "ಭಾರತ ಸರ್ಕಾರದ ಉಪಕ್ರಮ",
  govAndStudent: "ಸರ್ಕಾರಿ ಮತ್ತು ವಿದ್ಯಾರ್ಥಿ",
  helpPlatform: "ಸಹಾಯ ವೇದಿಕೆ",
  oneStopAssistance: "ಭಾರತದಾದ್ಯಂತ ವಿದ್ಯಾರ್ಥಿಗಳು ಮತ್ತು ನಾಗರಿಕರಿಗೆ ಏಕೀಕೃತ ಸಹಾಯ",
  exploreAllSchemes: "ಎಲ್ಲಾ ಯೋಜನೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ",
  whoAreYou: "ನೀವು ಯಾರು?",
  viewSchemes: "ಯೋಜನೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
  search: "ಹುಡುಕಿ",
  health: "ಆರೋಗ್ಯ",
  education: "ಶಿಕ್ಷಣ",
  agriculture: "ಕೃಷಿ",
  scholarship: "ವಿದ್ಯಾರ್ಥಿವೇತನ",
  welfare: "ಕಲ್ಯಾಣ",
  employment: "ಉದ್ಯೋಗ",
  schemes: "ಯೋಜನೆಗಳು",
  apply: "ಅರ್ಜಿ ಸಲ್ಲಿಸಿ",
  eligibility: "ಅರ್ಹತೆ",
  pending: "ಬಾಕಿ ಇದೆ",
  approved: "ಅನುಮೋದಿಸಲಾಗಿದೆ",
  rejected: "ತಿರಸ್ಕರಿಸಲಾಗಿದೆ",
  contactTitle: "ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ",
  name: "ಹೆಸರು",
  message: "ಸಂದೇಶ",
  submit: "ಸಲ್ಲಿಸಿ",
  aboutTitle: "ಸರ್ಕಾರಿ ಮತ್ತು ವಿದ್ಯಾರ್ಥಿ ಸಹಾಯ ವೇದಿಕೆಯ ಬಗ್ಗೆ",
  aboutBody: "ಈ ವೇದಿಕೆಯು ಭಾರತದಾದ್ಯಂತ ವಿದ್ಯಾರ್ಥಿಗಳು ಮತ್ತು ನಾಗರಿಕರು ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು, ವಿದ್ಯಾರ್ಥಿವೇತನಗಳು ಮತ್ತು ಸೇವೆಗಳನ್ನು ಕಂಡುಹಿಡಿಯಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ।",
  
  // Authentication
  sign_in: "ಸೈನ್ ಇನ್",
  sign_out: "ಸೈನ್ ಔಟ್",
  dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
  
  // Auth Page Keys (NEW - Task 4.1)
  login: "ಲಾಗಿನ್",
  signup: "ಸೈನ್ ಅಪ್",
  admin: "ನಿರ್ವಾಹಕ",
  email: "ಇಮೇಲ್",
  password: "ಪಾಸ್‌ವರ್ಡ್",
  displayName: "ಪ್ರದರ್ಶನ ಹೆಸರು",
  district: "ಜಿಲ್ಲೆ",
  taluka: "ತಾಲೂಕು",
  createAccount: "ಖಾತೆ ರಚಿಸಿ",
  pleaseWait: "ದಯವಿಟ್ಟು ನಿರೀಕ್ಷಿಸಿ...",
  welcomeBack: "ಮತ್ತೆ ಸ್ವಾಗತ!",
  adminAccessOnly: "ನಿರ್ವಾಹಕ ಪ್ರವೇಶ ಮಾತ್ರ",
  restrictedArea: "ಈ ಪ್ರದೇಶವು ಅಧಿಕೃತ ಸರ್ಕಾರಿ ನಿರ್ವಾಹಕರಿಗೆ ಮಾತ್ರ ನಿರ್ಬಂಧಿತವಾಗಿದೆ.",
  authenticating: "ದೃಢೀಕರಿಸಲಾಗುತ್ತಿದೆ...",
  adminLogin: "ನಿರ್ವಾಹಕ ಲಾಗಿನ್",
  invalidCredentials: "ಅಮಾನ್ಯ ರುಜುವಾತುಗಳು",
  loginFailed: "ಲಾಗಿನ್ ವಿಫಲವಾಗಿದೆ",
  signupSuccess: "ಖಾತೆ ರಚಿಸಲಾಗಿದೆ!",
  checkEmail: "ನಿಮ್ಮ ಇಮೇಲ್ ಪರಿಶೀಲಿಸಿ",
  accountCreated: "ಖಾತೆ ರಚಿಸಲಾಗಿದೆ! ಸರ್ಕಾರಿ ಮತ್ತು ವಿದ್ಯಾರ್ಥಿ ಸಹಾಯ ವೇದಿಕೆಗೆ ಸ್ವಾಗತ!",
  adminUsername: "ನಿರ್ವಾಹಕ ಬಳಕೆದಾರ ಹೆಸರು",
  adminPassword: "ನಿರ್ವಾಹಕ ಪಾಸ್‌ವರ್ಡ್",
  enterAdminUsername: "ನಿರ್ವಾಹಕ ಬಳಕೆದಾರ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
  enterAdminPassword: "ನಿರ್ವಾಹಕ ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ",
  enterFullName: "ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
  selectDistrictPlaceholder: "ಜಿಲ್ಲೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  selectTalukaPlaceholder: "ತಾಲೂಕನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  
  // Admin Panel Keys (NEW - Task 4.1)
  totalUsers: "ಒಟ್ಟು ಬಳಕೆದಾರರು",
  todayActivity: "ಇಂದಿನ ಅರ್ಜಿಗಳು",
  pendingReviews: "ಬಾಕಿ ಇರುವ ಅರ್ಜಿಗಳು",
  userManagement: "ಬಳಕೆದಾರ ನಿರ್ವಹಣೆ",
  applicationManagement: "ಅರ್ಜಿ ನಿರ್ವಹಣೆ",
  schemeManagement: "ಯೋಜನೆ ನಿರ್ವಹಣೆ",
  viewDetails: "ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
  deleteUser: "ಬಳಕೆದಾರರನ್ನು ಅಳಿಸಿ",
  statistics: "ಅಂಕಿಅಂಶಗಳು",
  recentActivity: "ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ",
  quickActions: "ತ್ವರಿತ ಕ್ರಿಯೆಗಳು",
  reviewApplications: "ಅರ್ಜಿಗಳನ್ನು ಪರಿಶೀಲಿಸಿ",
  addNewScheme: "ಹೊಸ ಯೋಜನೆಯನ್ನು ಸೇರಿಸಿ",
  viewReports: "ವರದಿಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
  adminDashboard: "ನಿರ್ವಾಹಕ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
  comprehensiveManagement: "ಯೋಜನೆಗಳು ಮತ್ತು ಅರ್ಜಿಗಳ ಸಮಗ್ರ ನಿರ್ವಹಣೆ",
  live: "ಲೈವ್",
  logout: "ಲಾಗ್ಔಟ್",
  allApplications: "ಎಲ್ಲಾ ಅರ್ಜಿಗಳು",
  total: "ಒಟ್ಟು",
  noApplicationsFound: "ಯಾವುದೇ ಅರ್ಜಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
  needsAttention: "ಗಮನ ಅಗತ್ಯವಿದೆ",
  registeredUsers: "ನೋಂದಾಯಿತ ಬಳಕೆದಾರರು",
  allTime: "ಎಲ್ಲಾ ಸಮಯ",
  receivedToday: "ಇಂದು ಸ್ವೀಕರಿಸಲಾಗಿದೆ",
  manageAllSchemes: "ಎಲ್ಲಾ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
  allCategories: "ಎಲ್ಲಾ ವರ್ಗಗಳು",
  allStates: "ಎಲ್ಲಾ ರಾಜ್ಯಗಳು",
  export: "ರಫ್ತು",
  import: "ಆಮದು",
  noSchemesFoundFilter: "ಯಾವುದೇ ಯೋಜನೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
  adjustFilters: "ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಸರಿಹೊಂದಿಸಿ ಅಥವಾ ಹೊಸ ಯೋಜನೆಯನ್ನು ಸೇರಿಸಿ",
  manageAllApplications: "ಎಲ್ಲಾ ಬಳಕೆದಾರ ಅರ್ಜಿಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
  refresh: "ರಿಫ್ರೆಶ್",
  needDocs: "ದಾಖಲೆಗಳು ಅಗತ್ಯವಿದೆ",
  users: "ಬಳಕೆದಾರರು",
  andMoreUsers: "ಮತ್ತು {count} ಹೆಚ್ಚಿನ ಬಳಕೆದಾರರು...",
  noDistrict: "ಯಾವುದೇ ಜಿಲ್ಲೆ ಇಲ್ಲ",
  categoryDistribution: "ವರ್ಗ ವಿತರಣೆ",
  applicationStatusLabel: "ಅರ್ಜಿ ಸ್ಥಿತಿ",
  systemSettings: "ಸಿಸ್ಟಮ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
  platformConfiguration: "ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಕಾನ್ಫಿಗರೇಶನ್",
  defaultLanguage: "ಡೀಫಾಲ್ಟ್ ಭಾಷೆ",
  maxUploadSize: "ಗರಿಷ್ಠ ಅಪ್‌ಲೋಡ್ ಗಾತ್ರ",
  securitySettings: "ಭದ್ರತಾ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
  twoFactorAuth: "ಎರಡು-ಅಂಶ ದೃಢೀಕರಣ",
  enableForSecurity: "ಹೆಚ್ಚುವರಿ ಭದ್ರತೆಗಾಗಿ ಸಕ್ರಿಯಗೊಳಿಸಿ",
  enable: "ಸಕ್ರಿಯಗೊಳಿಸಿ",
  sessionTimeout: "ಸೆಷನ್ ಟೈಮ್‌ಔಟ್",
  autoLogout: "ನಿಷ್ಕ್ರಿಯತೆಯ ನಂತರ ಸ್ವಯಂಚಾಲಿತ ಲಾಗ್ಔಟ್",
  saveSettings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಉಳಿಸಿ",
  analytics: "ವಿಶ್ಲೇಷಣೆ",
  settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
  
  // Common UI Keys (NEW - Task 4.1)
  save: "ಉಳಿಸಿ",
  cancel: "ರದ್ದುಮಾಡಿ",
  edit: "ಸಂಪಾದಿಸಿ",
  delete: "ಅಳಿಸಿ",
  confirm: "ದೃಢೀಕರಿಸಿ",
  back: "ಹಿಂದೆ",
  next: "ಮುಂದೆ",
  previous: "ಹಿಂದಿನ",
  close: "ಮುಚ್ಚಿ",
  open: "ತೆರೆಯಿರಿ",
  yes: "ಹೌದು",
  no: "ಇಲ್ಲ",
  ok: "ಸರಿ",
  error: "ದೋಷ",
  success: "ಯಶಸ್ಸು",
  warning: "ಎಚ್ಚರಿಕೆ",
  info: "ಮಾಹಿತಿ",
  processing: "ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...",
  
  // Services & About Page Keys (NEW - Task 4.1)
  allServices: "ಎಲ್ಲಾ ಸೇವೆಗಳು",
  serviceCategories: "ಸೇವಾ ವರ್ಗಗಳು",
  popularServices: "ಜನಪ್ರಿಯ ಸೇವೆಗಳು",
  mission: "ಧ್ಯೇಯ",
  vision: "ದೃಷ್ಟಿ",
  features: "ವೈಶಿಷ್ಟ್ಯಗಳು",
  howItWorks: "ಇದು ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ",
  
  // Contact Page Keys (NEW - Task 4.1)
  getInTouch: "ಸಂಪರ್ಕದಲ್ಲಿರಿ",
  sendMessage: "ಸಂದೇಶ ಕಳುಹಿಸಿ",
  yourName: "ನಿಮ್ಮ ಹೆಸರು",
  yourEmail: "ನಿಮ್ಮ ಇಮೇಲ್",
  yourMessage: "ನಿಮ್ಮ ಸಂದೇಶ",
  messageSent: "ಸಂದೇಶ ಕಳುಹಿಸಲಾಗಿದೆ",
  
  // AI Assistant Keys (NEW - Task 4.1)
  aiWelcome: "ಸ್ವಾಗತ! ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು ಮತ್ತು ಸೇವೆಗಳನ್ನು ಕಂಡುಹಿಡಿಯಲು ನಿಮಗೆ ಸಹಾಯ ಮಾಡಲು ನಾನು ಇಲ್ಲಿದ್ದೇನೆ. ಇಂದು ನಾನು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?",
  aiHelp: "ಯೋಜನೆಗಳನ್ನು ಕಂಡುಹಿಡಿಯುವುದು, ಅರ್ಹತೆಯನ್ನು ಪರಿಶೀಲಿಸುವುದು ಮತ್ತು ಸರ್ಕಾರಿ ಸೇವೆಗಳ ಬಗ್ಗೆ ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಿಸುವುದರಲ್ಲಿ ನಾನು ನಿಮಗೆ ಸಹಾಯ ಮಾಡಬಲ್ಲೆ.",
  aiCommands: "ಲಭ್ಯವಿರುವ ಆಜ್ಞೆಗಳು: /schemes, /eligibility, /apply, /track, /help",
  askQuestion: "ಒಂದು ಪ್ರಶ್ನೆ ಕೇಳಿ",
  typeMessage: "ನಿಮ್ಮ ಸಂದೇಶವನ್ನು ಟೈಪ್ ಮಾಡಿ",
  
  // Theme Keys (NEW)
  toggleTheme: "ಥೀಮ್ ಟಾಗಲ್ ಮಾಡಿ",
  lightMode: "ಲೈಟ್",
  darkMode: "ಡಾರ್ಕ್",
  systemMode: "ಸಿಸ್ಟಮ್",
};

// Malayalam translations (comprehensive)
const malayalamStrings: Record<string, string> = {
  ...englishStrings,
  home: "ഹോം",
  services: "സേവനങ്ങൾ",
  about: "കുറിച്ച്",
  contact: "ബന്ധപ്പെടുക",
  appName: "സർക്കാർ, വിദ്യാർത്ഥി സഹായം",
  tagline: "വിദ്യാർത്ഥികൾക്കും പൗരന്മാർക്കും സമഗ്ര സഹായം",
  students: "വിദ്യാർത്ഥികൾ",
  citizens: "പൗരന്മാർ",
  schemeApplicants: "പദ്ധതി അപേക്ഷകർ",
  govInitiative: "ഇന്ത്യാ ഗവൺമെന്റ് സംരംഭം",
  govAndStudent: "സർക്കാർ, വിദ്യാർത്ഥി",
  helpPlatform: "സഹായ പ്ലാറ്റ്ഫോം",
  oneStopAssistance: "ഇന്ത്യയിലുടനീളമുള്ള വിദ്യാർത്ഥികൾക്കും പൗരന്മാർക്കും സമഗ്ര സഹായം",
  exploreAllSchemes: "എല്ലാ പദ്ധതികളും പര്യവേക്ഷണം ചെയ്യുക",
  whoAreYou: "നിങ്ങൾ ആരാണ്?",
  viewSchemes: "പദ്ധതികൾ കാണുക",
  search: "തിരയുക",
  health: "ആരോഗ്യം",
  education: "വിദ്യാഭ്യാസം",
  agriculture: "കൃഷി",
  scholarship: "സ്കോളർഷിപ്പ്",
  welfare: "ക്ഷേമം",
  employment: "തൊഴിൽ",
  schemes: "പദ്ധതികൾ",
  apply: "അപേക്ഷിക്കുക",
  eligibility: "യോഗ്യത",
  pending: "തീർപ്പുകൽപ്പിക്കാത്ത",
  approved: "അംഗീകരിച്ചു",
  rejected: "നിരസിച്ചു",
  contactTitle: "ഞങ്ങളെ ബന്ധപ്പെടുക",
  name: "പേര്",
  message: "സന്ദേശം",
  submit: "സമർപ്പിക്കുക",
  aboutTitle: "സർക്കാർ, വിദ്യാർത്ഥി സഹായ പ്ലാറ്റ്ഫോമിനെ കുറിച്ച്",
  aboutBody: "ഈ പ്ലാറ്റ്ഫോം ഇന്ത്യയിലുടനീളമുള്ള വിദ്യാർത്ഥികളെയും പൗരന്മാരെയും സർക്കാർ പദ്ധതികൾ, സ്കോളർഷിപ്പുകൾ, സേവനങ്ങൾ എന്നിവ കണ്ടെത്താൻ സഹായിക്കുന്നു।",
  
  // Authentication
  sign_in: "സൈൻ ഇൻ",
  sign_out: "സൈൻ ഔട്ട്",
  dashboard: "ഡാഷ്ബോർഡ്",
  
  // Auth Page Keys (NEW - Task 4.2)
  login: "ലോഗിൻ",
  signup: "സൈൻ അപ്പ്",
  admin: "അഡ്മിൻ",
  email: "ഇമെയിൽ",
  password: "പാസ്‌വേഡ്",
  displayName: "പ്രദർശന നാമം",
  district: "ജില്ല",
  taluka: "താലൂക്ക്",
  createAccount: "അക്കൗണ്ട് സൃഷ്ടിക്കുക",
  pleaseWait: "ദയവായി കാത്തിരിക്കുക...",
  welcomeBack: "തിരികെ സ്വാഗതം!",
  adminAccessOnly: "അഡ്മിൻ ആക്സസ് മാത്രം",
  restrictedArea: "ഈ മേഖല അംഗീകൃത സർക്കാർ അഡ്മിനിസ്ട്രേറ്റർമാർക്ക് മാത്രമായി പരിമിതപ്പെടുത്തിയിരിക്കുന്നു.",
  authenticating: "പ്രാമാണീകരിക്കുന്നു...",
  adminLogin: "അഡ്മിൻ ലോഗിൻ",
  invalidCredentials: "അസാധുവായ യോഗ്യതാപത്രങ്ങൾ",
  loginFailed: "ലോഗിൻ പരാജയപ്പെട്ടു",
  signupSuccess: "അക്കൗണ്ട് സൃഷ്ടിച്ചു!",
  checkEmail: "നിങ്ങളുടെ ഇമെയിൽ പരിശോധിക്കുക",
  accountCreated: "അക്കൗണ്ട് സൃഷ്ടിച്ചു! സർക്കാർ, വിദ്യാർത്ഥി സഹായ പ്ലാറ്റ്ഫോമിലേക്ക് സ്വാഗതം!",
  adminUsername: "അഡ്മിൻ ഉപയോക്തൃനാമം",
  adminPassword: "അഡ്മിൻ പാസ്‌വേഡ്",
  enterAdminUsername: "അഡ്മിൻ ഉപയോക്തൃനാമം നൽകുക",
  enterAdminPassword: "അഡ്മിൻ പാസ്‌വേഡ് നൽകുക",
  enterFullName: "നിങ്ങളുടെ പൂർണ്ണ നാമം നൽകുക",
  selectDistrictPlaceholder: "ജില്ല തിരഞ്ഞെടുക്കുക",
  selectTalukaPlaceholder: "താലൂക്ക് തിരഞ്ഞെടുക്കുക",
  
  // Admin Panel Keys (NEW - Task 4.2)
  totalUsers: "മൊത്തം ഉപയോക്താക്കൾ",
  todayActivity: "ഇന്നത്തെ അപേക്ഷകൾ",
  pendingReviews: "തീർപ്പുകൽപ്പിക്കാത്ത അപേക്ഷകൾ",
  userManagement: "ഉപയോക്തൃ മാനേജ്മെന്റ്",
  applicationManagement: "അപേക്ഷ മാനേജ്മെന്റ്",
  schemeManagement: "പദ്ധതി മാനേജ്മെന്റ്",
  viewDetails: "വിശദാംശങ്ങൾ കാണുക",
  deleteUser: "ഉപയോക്താവിനെ ഇല്ലാതാക്കുക",
  statistics: "സ്ഥിതിവിവരക്കണക്കുകൾ",
  recentActivity: "സമീപകാല പ്രവർത്തനം",
  quickActions: "ദ്രുത പ്രവർത്തനങ്ങൾ",
  reviewApplications: "അപേക്ഷകൾ അവലോകനം ചെയ്യുക",
  addNewScheme: "പുതിയ പദ്ധതി ചേർക്കുക",
  viewReports: "റിപ്പോർട്ടുകൾ കാണുക",
  adminDashboard: "അഡ്മിൻ ഡാഷ്ബോർഡ്",
  comprehensiveManagement: "പദ്ധതികളുടെയും അപേക്ഷകളുടെയും സമഗ്ര മാനേജ്മെന്റ്",
  live: "തത്സമയം",
  logout: "ലോഗൗട്ട്",
  allApplications: "എല്ലാ അപേക്ഷകളും",
  total: "മൊത്തം",
  noApplicationsFound: "അപേക്ഷകളൊന്നും കണ്ടെത്തിയില്ല",
  needsAttention: "ശ്രദ്ധ ആവശ്യമാണ്",
  registeredUsers: "രജിസ്റ്റർ ചെയ്ത ഉപയോക്താക്കൾ",
  allTime: "എല്ലാ സമയവും",
  receivedToday: "ഇന്ന് ലഭിച്ചത്",
  manageAllSchemes: "എല്ലാ സർക്കാർ പദ്ധതികളും മാനേജ് ചെയ്യുക",
  allCategories: "എല്ലാ വിഭാഗങ്ങളും",
  allStates: "എല്ലാ സംസ്ഥാനങ്ങളും",
  export: "കയറ്റുമതി",
  import: "ഇറക്കുമതി",
  noSchemesFoundFilter: "പദ്ധതികളൊന്നും കണ്ടെത്തിയില്ല",
  adjustFilters: "ഫിൽട്ടറുകൾ ക്രമീകരിക്കുക അല്ലെങ്കിൽ പുതിയ പദ്ധതി ചേർക്കുക",
  manageAllApplications: "എല്ലാ ഉപയോക്തൃ അപേക്ഷകളും മാനേജ് ചെയ്യുക",
  refresh: "പുതുക്കുക",
  needDocs: "രേഖകൾ ആവശ്യമാണ്",
  users: "ഉപയോക്താക്കൾ",
  andMoreUsers: "കൂടാതെ {count} കൂടുതൽ ഉപയോക്താക്കൾ...",
  noDistrict: "ജില്ലയില്ല",
  categoryDistribution: "വിഭാഗ വിതരണം",
  applicationStatusLabel: "അപേക്ഷാ നില",
  systemSettings: "സിസ്റ്റം ക്രമീകരണങ്ങൾ",
  platformConfiguration: "പ്ലാറ്റ്ഫോം കോൺഫിഗറേഷൻ",
  defaultLanguage: "സ്ഥിര ഭാഷ",
  maxUploadSize: "പരമാവധി അപ്‌ലോഡ് വലുപ്പം",
  securitySettings: "സുരക്ഷാ ക്രമീകരണങ്ങൾ",
  twoFactorAuth: "രണ്ട്-ഘടക പ്രാമാണീകരണം",
  enableForSecurity: "അധിക സുരക്ഷയ്ക്കായി പ്രവർത്തനക്ഷമമാക്കുക",
  enable: "പ്രവർത്തനക്ഷമമാക്കുക",
  sessionTimeout: "സെഷൻ ടൈംഔട്ട്",
  autoLogout: "നിഷ്ക്രിയത്വത്തിന് ശേഷം സ്വയമേവ ലോഗൗട്ട്",
  saveSettings: "ക്രമീകരണങ്ങൾ സംരക്ഷിക്കുക",
  analytics: "വിശകലനം",
  settings: "ക്രമീകരണങ്ങൾ",
  
  // Common UI Keys (NEW - Task 4.2)
  save: "സംരക്ഷിക്കുക",
  cancel: "റദ്ദാക്കുക",
  edit: "എഡിറ്റ് ചെയ്യുക",
  delete: "ഇല്ലാതാക്കുക",
  confirm: "സ്ഥിരീകരിക്കുക",
  back: "പിന്നോട്ട്",
  next: "അടുത്തത്",
  previous: "മുമ്പത്തേത്",
  close: "അടയ്ക്കുക",
  open: "തുറക്കുക",
  yes: "അതെ",
  no: "ഇല്ല",
  ok: "ശരി",
  error: "പിശക്",
  success: "വിജയം",
  warning: "മുന്നറിയിപ്പ്",
  info: "വിവരം",
  processing: "പ്രോസസ്സ് ചെയ്യുന്നു...",
  
  // Services & About Page Keys (NEW - Task 4.2)
  allServices: "എല്ലാ സേവനങ്ങളും",
  serviceCategories: "സേവന വിഭാഗങ്ങൾ",
  popularServices: "ജനപ്രിയ സേവനങ്ങൾ",
  mission: "ദൗത്യം",
  vision: "കാഴ്ചപ്പാട്",
  features: "സവിശേഷതകൾ",
  howItWorks: "ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു",
  
  // Contact Page Keys (NEW - Task 4.2)
  getInTouch: "ബന്ധപ്പെടുക",
  sendMessage: "സന്ദേശം അയയ്ക്കുക",
  yourName: "നിങ്ങളുടെ പേര്",
  yourEmail: "നിങ്ങളുടെ ഇമെയിൽ",
  yourMessage: "നിങ്ങളുടെ സന്ദേശം",
  messageSent: "സന്ദേശം അയച്ചു",
  
  // AI Assistant Keys (NEW - Task 4.2)
  aiWelcome: "സ്വാഗതം! സർക്കാർ പദ്ധതികളും സേവനങ്ങളും കണ്ടെത്താൻ നിങ്ങളെ സഹായിക്കാൻ ഞാൻ ഇവിടെയുണ്ട്. ഇന്ന് ഞാൻ നിങ്ങളെ എങ്ങനെ സഹായിക്കും?",
  aiHelp: "പദ്ധതികൾ കണ്ടെത്തുന്നതിനും യോഗ്യത പരിശോധിക്കുന്നതിനും സർക്കാർ സേവനങ്ങളെക്കുറിച്ചുള്ള ചോദ്യങ്ങൾക്ക് ഉത്തരം നൽകുന്നതിനും ഞാൻ നിങ്ങളെ സഹായിക്കും.",
  aiCommands: "ലഭ്യമായ കമാൻഡുകൾ: /schemes, /eligibility, /apply, /track, /help",
  askQuestion: "ഒരു ചോദ്യം ചോദിക്കുക",
  typeMessage: "നിങ്ങളുടെ സന്ദേശം ടൈപ്പ് ചെയ്യുക",
  
  // Theme Keys (NEW)
  toggleTheme: "തീം ടോഗിൾ ചെയ്യുക",
  lightMode: "ലൈറ്റ്",
  darkMode: "ഡാർക്ക്",
  systemMode: "സിസ്റ്റം",
};

// Punjabi translations (comprehensive)
const punjabiStrings: Record<string, string> = {
  ...englishStrings,
  home: "ਘਰ",
  services: "ਸੇਵਾਵਾਂ",
  about: "ਬਾਰੇ",
  contact: "ਸੰਪਰਕ",
  appName: "ਸਰਕਾਰੀ ਅਤੇ ਵਿਦਿਆਰਥੀ ਸਹਾਇਤਾ",
  tagline: "ਵਿਦਿਆਰਥੀਆਂ ਅਤੇ ਨਾਗਰਿਕਾਂ ਲਈ ਏਕੀਕ੍ਰਿਤ ਸਹਾਇਤਾ",
  students: "ਵਿਦਿਆਰਥੀ",
  citizens: "ਨਾਗਰਿਕ",
  schemeApplicants: "ਸਕੀਮ ਅਰਜ਼ੀਦਾਰ",
  govInitiative: "ਭਾਰਤ ਸਰਕਾਰ ਦੀ ਪਹਿਲਕਦਮੀ",
  govAndStudent: "ਸਰਕਾਰੀ ਅਤੇ ਵਿਦਿਆਰਥੀ",
  helpPlatform: "ਸਹਾਇਤਾ ਪਲੇਟਫਾਰਮ",
  oneStopAssistance: "ਭਾਰਤ ਭਰ ਦੇ ਵਿਦਿਆਰਥੀਆਂ ਅਤੇ ਨਾਗਰਿਕਾਂ ਲਈ ਏਕੀਕ੍ਰਿਤ ਸਹਾਇਤਾ",
  exploreAllSchemes: "ਸਾਰੀਆਂ ਸਕੀਮਾਂ ਦੀ ਪੜਚੋਲ ਕਰੋ",
  whoAreYou: "ਤੁਸੀਂ ਕੌਣ ਹੋ?",
  viewSchemes: "ਸਕੀਮਾਂ ਦੇਖੋ",
  search: "ਖੋਜੋ",
  health: "ਸਿਹਤ",
  education: "ਸਿੱਖਿਆ",
  agriculture: "ਖੇਤੀਬਾੜੀ",
  scholarship: "ਸਕਾਲਰਸ਼ਿਪ",
  welfare: "ਭਲਾਈ",
  employment: "ਰੁਜ਼ਗਾਰ",
  schemes: "ਸਕੀਮਾਂ",
  apply: "ਅਰਜ਼ੀ ਦਿਓ",
  eligibility: "ਯੋਗਤਾ",
  pending: "ਬਕਾਇਆ",
  approved: "ਮਨਜ਼ੂਰ",
  rejected: "ਰੱਦ",
  contactTitle: "ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੋ",
  name: "ਨਾਮ",
  message: "ਸੰਦੇਸ਼",
  submit: "ਜਮ੍ਹਾਂ ਕਰੋ",
  aboutTitle: "ਸਰਕਾਰੀ ਅਤੇ ਵਿਦਿਆਰਥੀ ਸਹਾਇਤਾ ਪਲੇਟਫਾਰਮ ਬਾਰੇ",
  aboutBody: "ਇਹ ਪਲੇਟਫਾਰਮ ਭਾਰਤ ਭਰ ਦੇ ਵਿਦਿਆਰਥੀਆਂ ਅਤੇ ਨਾਗਰਿਕਾਂ ਨੂੰ ਸਰਕਾਰੀ ਸਕੀਮਾਂ, ਸਕਾਲਰਸ਼ਿਪਾਂ ਅਤੇ ਸੇਵਾਵਾਂ ਲੱਭਣ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹੈ।",
  
  // Authentication
  sign_in: "ਸਾਈਨ ਇਨ",
  sign_out: "ਸਾਈਨ ਆਊਟ",
  dashboard: "ਡੈਸ਼ਬੋਰਡ",
  
  // Auth Page Keys (NEW - Task 4.3)
  login: "ਲਾਗਇਨ",
  signup: "ਸਾਈਨ ਅੱਪ",
  admin: "ਐਡਮਿਨ",
  email: "ਈਮੇਲ",
  password: "ਪਾਸਵਰਡ",
  displayName: "ਡਿਸਪਲੇ ਨਾਮ",
  district: "ਜ਼ਿਲ੍ਹਾ",
  taluka: "ਤਹਿਸੀਲ",
  createAccount: "ਖਾਤਾ ਬਣਾਓ",
  pleaseWait: "ਕਿਰਪਾ ਕਰਕੇ ਉਡੀਕ ਕਰੋ...",
  welcomeBack: "ਵਾਪਸ ਜੀ ਆਇਆਂ ਨੂੰ!",
  adminAccessOnly: "ਸਿਰਫ਼ ਐਡਮਿਨ ਪਹੁੰਚ",
  restrictedArea: "ਇਹ ਖੇਤਰ ਸਿਰਫ਼ ਅਧਿਕਾਰਤ ਸਰਕਾਰੀ ਪ੍ਰਸ਼ਾਸਕਾਂ ਲਈ ਸੀਮਤ ਹੈ।",
  authenticating: "ਪ੍ਰਮਾਣਿਤ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...",
  adminLogin: "ਐਡਮਿਨ ਲਾਗਇਨ",
  invalidCredentials: "ਅਵੈਧ ਪ੍ਰਮਾਣ ਪੱਤਰ",
  loginFailed: "ਲਾਗਇਨ ਅਸਫਲ",
  signupSuccess: "ਖਾਤਾ ਬਣਾਇਆ ਗਿਆ!",
  checkEmail: "ਆਪਣੀ ਈਮੇਲ ਦੀ ਜਾਂਚ ਕਰੋ",
  accountCreated: "ਖਾਤਾ ਬਣਾਇਆ ਗਿਆ! ਸਰਕਾਰੀ ਅਤੇ ਵਿਦਿਆਰਥੀ ਸਹਾਇਤਾ ਪਲੇਟਫਾਰਮ ਵਿੱਚ ਤੁਹਾਡਾ ਸਵਾਗਤ ਹੈ!",
  adminUsername: "ਐਡਮਿਨ ਯੂਜ਼ਰਨੇਮ",
  adminPassword: "ਐਡਮਿਨ ਪਾਸਵਰਡ",
  enterAdminUsername: "ਐਡਮਿਨ ਯੂਜ਼ਰਨੇਮ ਦਾਖਲ ਕਰੋ",
  enterAdminPassword: "ਐਡਮਿਨ ਪਾਸਵਰਡ ਦਾਖਲ ਕਰੋ",
  enterFullName: "ਆਪਣਾ ਪੂਰਾ ਨਾਮ ਦਾਖਲ ਕਰੋ",
  selectDistrictPlaceholder: "ਜ਼ਿਲ੍ਹਾ ਚੁਣੋ",
  selectTalukaPlaceholder: "ਤਹਿਸੀਲ ਚੁਣੋ",
  
  // Admin Panel Keys (NEW - Task 4.3)
  totalUsers: "ਕੁੱਲ ਉਪਭੋਗਤਾ",
  todayActivity: "ਅੱਜ ਦੀਆਂ ਅਰਜ਼ੀਆਂ",
  pendingReviews: "ਬਕਾਇਆ ਅਰਜ਼ੀਆਂ",
  userManagement: "ਉਪਭੋਗਤਾ ਪ੍ਰਬੰਧਨ",
  applicationManagement: "ਅਰਜ਼ੀ ਪ੍ਰਬੰਧਨ",
  schemeManagement: "ਸਕੀਮ ਪ੍ਰਬੰਧਨ",
  viewDetails: "ਵੇਰਵੇ ਦੇਖੋ",
  deleteUser: "ਉਪਭੋਗਤਾ ਮਿਟਾਓ",
  statistics: "ਅੰਕੜੇ",
  recentActivity: "ਹਾਲੀਆ ਗਤੀਵਿਧੀ",
  quickActions: "ਤੇਜ਼ ਕਾਰਵਾਈਆਂ",
  reviewApplications: "ਅਰਜ਼ੀਆਂ ਦੀ ਸਮੀਖਿਆ ਕਰੋ",
  addNewScheme: "ਨਵੀਂ ਸਕੀਮ ਸ਼ਾਮਲ ਕਰੋ",
  viewReports: "ਰਿਪੋਰਟਾਂ ਦੇਖੋ",
  adminDashboard: "ਐਡਮਿਨ ਡੈਸ਼ਬੋਰਡ",
  comprehensiveManagement: "ਸਕੀਮਾਂ ਅਤੇ ਅਰਜ਼ੀਆਂ ਦਾ ਵਿਆਪਕ ਪ੍ਰਬੰਧਨ",
  live: "ਲਾਈਵ",
  logout: "ਲਾਗਆਊਟ",
  allApplications: "ਸਾਰੀਆਂ ਅਰਜ਼ੀਆਂ",
  total: "ਕੁੱਲ",
  noApplicationsFound: "ਕੋਈ ਅਰਜ਼ੀਆਂ ਨਹੀਂ ਮਿਲੀਆਂ",
  needsAttention: "ਧਿਆਨ ਦੀ ਲੋੜ ਹੈ",
  registeredUsers: "ਰਜਿਸਟਰਡ ਉਪਭੋਗਤਾ",
  allTime: "ਸਾਰਾ ਸਮਾਂ",
  receivedToday: "ਅੱਜ ਪ੍ਰਾਪਤ ਹੋਇਆ",
  manageAllSchemes: "ਸਾਰੀਆਂ ਸਰਕਾਰੀ ਸਕੀਮਾਂ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ",
  allCategories: "ਸਾਰੀਆਂ ਸ਼੍ਰੇਣੀਆਂ",
  allStates: "ਸਾਰੇ ਰਾਜ",
  export: "ਨਿਰਯਾਤ",
  import: "ਆਯਾਤ",
  noSchemesFoundFilter: "ਕੋਈ ਸਕੀਮਾਂ ਨਹੀਂ ਮਿਲੀਆਂ",
  adjustFilters: "ਫਿਲਟਰ ਐਡਜਸਟ ਕਰੋ ਜਾਂ ਨਵੀਂ ਸਕੀਮ ਸ਼ਾਮਲ ਕਰੋ",
  manageAllApplications: "ਸਾਰੀਆਂ ਉਪਭੋਗਤਾ ਅਰਜ਼ੀਆਂ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ",
  refresh: "ਤਾਜ਼ਾ ਕਰੋ",
  needDocs: "ਦਸਤਾਵੇਜ਼ਾਂ ਦੀ ਲੋੜ ਹੈ",
  users: "ਉਪਭੋਗਤਾ",
  andMoreUsers: "ਅਤੇ {count} ਹੋਰ ਉਪਭੋਗਤਾ...",
  noDistrict: "ਕੋਈ ਜ਼ਿਲ੍ਹਾ ਨਹੀਂ",
  categoryDistribution: "ਸ਼੍ਰੇਣੀ ਵੰਡ",
  applicationStatusLabel: "ਅਰਜ਼ੀ ਸਥਿਤੀ",
  systemSettings: "ਸਿਸਟਮ ਸੈਟਿੰਗਾਂ",
  platformConfiguration: "ਪਲੇਟਫਾਰਮ ਸੰਰਚਨਾ",
  defaultLanguage: "ਡਿਫਾਲਟ ਭਾਸ਼ਾ",
  maxUploadSize: "ਅਧਿਕਤਮ ਅੱਪਲੋਡ ਆਕਾਰ",
  securitySettings: "ਸੁਰੱਖਿਆ ਸੈਟਿੰਗਾਂ",
  twoFactorAuth: "ਦੋ-ਕਾਰਕ ਪ੍ਰਮਾਣਿਕਤਾ",
  enableForSecurity: "ਵਾਧੂ ਸੁਰੱਖਿਆ ਲਈ ਸਮਰੱਥ ਕਰੋ",
  enable: "ਸਮਰੱਥ ਕਰੋ",
  sessionTimeout: "ਸੈਸ਼ਨ ਟਾਈਮਆਊਟ",
  autoLogout: "ਨਿਸ਼ਕਿਰਿਆਤਾ ਤੋਂ ਬਾਅਦ ਸਵੈਚਲਿਤ ਲਾਗਆਊਟ",
  saveSettings: "ਸੈਟਿੰਗਾਂ ਸੁਰੱਖਿਅਤ ਕਰੋ",
  analytics: "ਵਿਸ਼ਲੇਸ਼ਣ",
  settings: "ਸੈਟਿੰਗਾਂ",
  
  // Common UI Keys (NEW - Task 4.3)
  save: "ਸੁਰੱਖਿਅਤ ਕਰੋ",
  cancel: "ਰੱਦ ਕਰੋ",
  edit: "ਸੰਪਾਦਿਤ ਕਰੋ",
  delete: "ਮਿਟਾਓ",
  confirm: "ਪੁਸ਼ਟੀ ਕਰੋ",
  back: "ਪਿੱਛੇ",
  next: "ਅੱਗੇ",
  previous: "ਪਿਛਲਾ",
  close: "ਬੰਦ ਕਰੋ",
  open: "ਖੋਲ੍ਹੋ",
  yes: "ਹਾਂ",
  no: "ਨਹੀਂ",
  ok: "ਠੀਕ ਹੈ",
  error: "ਗਲਤੀ",
  success: "ਸਫਲਤਾ",
  warning: "ਚੇਤਾਵਨੀ",
  info: "ਜਾਣਕਾਰੀ",
  processing: "ਪ੍ਰਕਿਰਿਆ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ...",
  
  // Services & About Page Keys (NEW - Task 4.3)
  allServices: "ਸਾਰੀਆਂ ਸੇਵਾਵਾਂ",
  serviceCategories: "ਸੇਵਾ ਸ਼੍ਰੇਣੀਆਂ",
  popularServices: "ਪ੍ਰਸਿੱਧ ਸੇਵਾਵਾਂ",
  mission: "ਮਿਸ਼ਨ",
  vision: "ਦ੍ਰਿਸ਼ਟੀ",
  features: "ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ",
  howItWorks: "ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ",
  
  // Contact Page Keys (NEW - Task 4.3)
  getInTouch: "ਸੰਪਰਕ ਵਿੱਚ ਰਹੋ",
  sendMessage: "ਸੰਦੇਸ਼ ਭੇਜੋ",
  yourName: "ਤੁਹਾਡਾ ਨਾਮ",
  yourEmail: "ਤੁਹਾਡੀ ਈਮੇਲ",
  yourMessage: "ਤੁਹਾਡਾ ਸੰਦੇਸ਼",
  messageSent: "ਸੰਦੇਸ਼ ਭੇਜਿਆ ਗਿਆ",
  
  // AI Assistant Keys (NEW - Task 4.3)
  aiWelcome: "ਸਵਾਗਤ ਹੈ! ਸਰਕਾਰੀ ਸਕੀਮਾਂ ਅਤੇ ਸੇਵਾਵਾਂ ਲੱਭਣ ਵਿੱਚ ਤੁਹਾਡੀ ਮਦਦ ਕਰਨ ਲਈ ਮੈਂ ਇੱਥੇ ਹਾਂ। ਅੱਜ ਮੈਂ ਤੁਹਾਡੀ ਕਿਵੇਂ ਮਦਦ ਕਰ ਸਕਦਾ ਹਾਂ?",
  aiHelp: "ਸਕੀਮਾਂ ਲੱਭਣ, ਯੋਗਤਾ ਦੀ ਜਾਂਚ ਕਰਨ ਅਤੇ ਸਰਕਾਰੀ ਸੇਵਾਵਾਂ ਬਾਰੇ ਸਵਾਲਾਂ ਦੇ ਜਵਾਬ ਦੇਣ ਵਿੱਚ ਮੈਂ ਤੁਹਾਡੀ ਮਦਦ ਕਰ ਸਕਦਾ ਹਾਂ।",
  aiCommands: "ਉਪਲਬਧ ਕਮਾਂਡਾਂ: /schemes, /eligibility, /apply, /track, /help",
  askQuestion: "ਇੱਕ ਸਵਾਲ ਪੁੱਛੋ",
  typeMessage: "ਆਪਣਾ ਸੰਦੇਸ਼ ਟਾਈਪ ਕਰੋ",
  
  // Theme Keys (NEW)
  toggleTheme: "ਥੀਮ ਟੌਗਲ ਕਰੋ",
  lightMode: "ਲਾਈਟ",
  darkMode: "ਡਾਰਕ",
  systemMode: "ਸਿਸਟਮ",
};

// Odia translations (comprehensive)
const odiaStrings: Record<string, string> = {
  ...englishStrings,
  home: "ଘର",
  services: "ସେବାଗୁଡ଼ିକ",
  about: "ବିଷୟରେ",
  contact: "ଯୋଗାଯୋଗ",
  appName: "ସରକାରୀ ଓ ଛାତ୍ର ସହାୟତା",
  tagline: "ଛାତ୍ର ଏବଂ ନାଗରିକମାନଙ୍କ ପାଇଁ ଏକୀକୃତ ସହାୟତା",
  students: "ଛାତ୍ରଛାତ୍ରୀ",
  citizens: "ନାଗରିକ",
  schemeApplicants: "ଯୋଜନା ଆବେଦନକାରୀ",
  govInitiative: "ଭାରତ ସରକାରଙ୍କ ପଦକ୍ଷେପ",
  govAndStudent: "ସରକାରୀ ଓ ଛାତ୍ର",
  helpPlatform: "ସହାୟତା ପ୍ଲାଟଫର୍ମ",
  oneStopAssistance: "ଭାରତର ଛାତ୍ର ଏବଂ ନାଗରିକମାନଙ୍କ ପାଇଁ ଏକୀକୃତ ସହାୟତା",
  exploreAllSchemes: "ସମସ୍ତ ଯୋଜନା ଅନ୍ବେଷଣ କରନ୍ତୁ",
  whoAreYou: "ଆପଣ କିଏ?",
  viewSchemes: "ଯୋଜନାଗୁଡ଼ିକ ଦେଖନ୍ତୁ",
  search: "ଖୋଜନ୍ତୁ",
  health: "ସ୍ୱାସ୍ଥ୍ୟ",
  education: "ଶିକ୍ଷା",
  agriculture: "କୃଷି",
  scholarship: "ଛାତ୍ରବୃତ୍ତି",
  welfare: "କଲ୍ୟାଣ",
  employment: "ନିଯୁକ୍ତି",
  schemes: "ଯୋଜନାଗୁଡ଼ିକ",
  apply: "ଆବେଦନ କରନ୍ତୁ",
  eligibility: "ଯୋଗ୍ୟତା",
  pending: "ବିଚାରାଧୀନ",
  approved: "ଅନୁମୋଦିତ",
  rejected: "ପ୍ରତ୍ୟାଖ୍ୟାନ",
  contactTitle: "ଆମ ସହିତ ଯୋଗାଯୋଗ କରନ୍ତୁ",
  name: "ନାମ",
  message: "ବାର୍ତ୍ତା",
  submit: "ଦାଖଲ କରନ୍ତୁ",
  aboutTitle: "ସରକାରୀ ଓ ଛାତ୍ର ସହାୟତା ପ୍ଲାଟଫର୍ମ ବିଷୟରେ",
  aboutBody: "ଏହି ପ୍ଲାଟଫର୍ମ ଭାରତର ଛାତ୍ର ଏବଂ ନାଗରିକମାନଙ୍କୁ ସରକାରୀ ଯୋଜନା, ଛାତ୍ରବୃତ୍ତି ଏବଂ ସେବା ଖୋଜିବାରେ ସାହାଯ୍ୟ କରେ।",
  
  // Authentication
  sign_in: "ସାଇନ୍ ଇନ୍",
  sign_out: "ସାଇନ୍ ଆଉଟ୍",
  dashboard: "ଡ୍ୟାସବୋର୍ଡ",
  
  // Auth Page Keys (NEW - Task 5.1)
  login: "ଲଗଇନ୍",
  signup: "ସାଇନ୍ ଅପ୍",
  admin: "ଆଡମିନ୍",
  email: "ଇମେଲ୍",
  password: "ପାସୱାର୍ଡ",
  displayName: "ପ୍ରଦର୍ଶନ ନାମ",
  district: "ଜିଲ୍ଲା",
  taluka: "ତାଲୁକା",
  createAccount: "ଖାତା ସୃଷ୍ଟି କରନ୍ତୁ",
  pleaseWait: "ଦୟାକରି ଅପେକ୍ଷା କରନ୍ତୁ...",
  welcomeBack: "ପୁନର୍ବାର ସ୍ୱାଗତ!",
  adminAccessOnly: "କେବଳ ଆଡମିନ୍ ପ୍ରବେଶ",
  restrictedArea: "ଏହି କ୍ଷେତ୍ର କେବଳ ଅଧିକୃତ ସରକାରୀ ପ୍ରଶାସକମାନଙ୍କ ପାଇଁ ସୀମିତ।",
  authenticating: "ପ୍ରମାଣୀକରଣ କରାଯାଉଛି...",
  adminLogin: "ଆଡମିନ୍ ଲଗଇନ୍",
  invalidCredentials: "ଅବୈଧ ପ୍ରମାଣପତ୍ର",
  loginFailed: "ଲଗଇନ୍ ବିଫଳ",
  signupSuccess: "ଖାତା ସୃଷ୍ଟି ହୋଇଛି!",
  checkEmail: "ଆପଣଙ୍କ ଇମେଲ୍ ଯାଞ୍ଚ କରନ୍ତୁ",
  accountCreated: "ଖାତା ସୃଷ୍ଟି ହୋଇଛି! ସରକାରୀ ଓ ଛାତ୍ର ସହାୟତା ପ୍ଲାଟଫର୍ମକୁ ସ୍ୱାଗତ!",
  adminUsername: "ଆଡମିନ୍ ଉପଯୋଗକର୍ତ୍ତା ନାମ",
  adminPassword: "ଆଡମିନ୍ ପାସୱାର୍ଡ",
  enterAdminUsername: "ଆଡମିନ୍ ଉପଯୋଗକର୍ତ୍ତା ନାମ ପ୍ରବେଶ କରନ୍ତୁ",
  enterAdminPassword: "ଆଡମିନ୍ ପାସୱାର୍ଡ ପ୍ରବେଶ କରନ୍ତୁ",
  enterFullName: "ଆପଣଙ୍କ ସମ୍ପୂର୍ଣ୍ଣ ନାମ ପ୍ରବେଶ କରନ୍ତୁ",
  selectDistrictPlaceholder: "ଜିଲ୍ଲା ଚୟନ କରନ୍ତୁ",
  selectTalukaPlaceholder: "ତାଲୁକା ଚୟନ କରନ୍ତୁ",
  
  // Admin Panel Keys (NEW - Task 5.1)
  totalUsers: "ମୋଟ ଉପଯୋଗକର୍ତ୍ତା",
  todayActivity: "ଆଜିର ଆବେଦନ",
  pendingReviews: "ବିଚାରାଧୀନ ଆବେଦନ",
  userManagement: "ଉପଯୋଗକର୍ତ୍ତା ପରିଚାଳନା",
  applicationManagement: "ଆବେଦନ ପରିଚାଳନା",
  schemeManagement: "ଯୋଜନା ପରିଚାଳନା",
  viewDetails: "ବିବରଣୀ ଦେଖନ୍ତୁ",
  deleteUser: "ଉପଯୋଗକର୍ତ୍ତା ବିଲୋପ କରନ୍ତୁ",
  statistics: "ପରିସଂଖ୍ୟାନ",
  recentActivity: "ସାମ୍ପ୍ରତିକ କାର୍ଯ୍ୟକଳାପ",
  quickActions: "ଦ୍ରୁତ କାର୍ଯ୍ୟ",
  reviewApplications: "ଆବେଦନ ସମୀକ୍ଷା କରନ୍ତୁ",
  addNewScheme: "ନୂତନ ଯୋଜନା ଯୋଗ କରନ୍ତୁ",
  viewReports: "ରିପୋର୍ଟ ଦେଖନ୍ତୁ",
  adminDashboard: "ଆଡମିନ୍ ଡ୍ୟାସବୋର୍ଡ",
  comprehensiveManagement: "ଯୋଜନା ଏବଂ ଆବେଦନର ବ୍ୟାପକ ପରିଚାଳନା",
  live: "ଲାଇଭ୍",
  logout: "ଲଗଆଉଟ୍",
  allApplications: "ସମସ୍ତ ଆବେଦନ",
  total: "ମୋଟ",
  noApplicationsFound: "କୌଣସି ଆବେଦନ ମିଳିଲା ନାହିଁ",
  needsAttention: "ଧ୍ୟାନ ଆବଶ୍ୟକ",
  registeredUsers: "ପଞ୍ଜୀକୃତ ଉପଯୋଗକର୍ତ୍ତା",
  allTime: "ସମସ୍ତ ସମୟ",
  receivedToday: "ଆଜି ପ୍ରାପ୍ତ",
  manageAllSchemes: "ସମସ୍ତ ସରକାରୀ ଯୋଜନା ପରିଚାଳନା କରନ୍ତୁ",
  allCategories: "ସମସ୍ତ ବର୍ଗ",
  allStates: "ସମସ୍ତ ରାଜ୍ୟ",
  export: "ରପ୍ତାନି",
  import: "ଆମଦାନୀ",
  noSchemesFoundFilter: "କୌଣସି ଯୋଜନା ମିଳିଲା ନାହିଁ",
  adjustFilters: "ଫିଲ୍ଟର ସଜାଡନ୍ତୁ କିମ୍ବା ନୂତନ ଯୋଜନା ଯୋଗ କରନ୍ତୁ",
  manageAllApplications: "ସମସ୍ତ ଉପଯୋଗକର୍ତ୍ତା ଆବେଦନ ପରିଚାଳନା କରନ୍ତୁ",
  refresh: "ସତେଜ କରନ୍ତୁ",
  needDocs: "ଦଲିଲ ଆବଶ୍ୟକ",
  users: "ଉପଯୋଗକର୍ତ୍ତା",
  andMoreUsers: "ଏବଂ {count} ଅଧିକ ଉପଯୋଗକର୍ତ୍ତା...",
  noDistrict: "କୌଣସି ଜିଲ୍ଲା ନାହିଁ",
  categoryDistribution: "ବର୍ଗ ବଣ୍ଟନ",
  applicationStatusLabel: "ଆବେଦନ ସ୍ଥିତି",
  systemSettings: "ସିଷ୍ଟମ୍ ସେଟିଂସ୍",
  platformConfiguration: "ପ୍ଲାଟଫର୍ମ ବିନ୍ୟାସ",
  defaultLanguage: "ଡିଫଲ୍ଟ ଭାଷା",
  maxUploadSize: "ସର୍ବାଧିକ ଅପଲୋଡ୍ ଆକାର",
  securitySettings: "ସୁରକ୍ଷା ସେଟିଂସ୍",
  twoFactorAuth: "ଦୁଇ-ଫ୍ୟାକ୍ଟର ପ୍ରମାଣୀକରଣ",
  enableForSecurity: "ଅତିରିକ୍ତ ସୁରକ୍ଷା ପାଇଁ ସକ୍ଷମ କରନ୍ତୁ",
  enable: "ସକ୍ଷମ କରନ୍ତୁ",
  sessionTimeout: "ସେସନ୍ ଟାଇମଆଉଟ୍",
  autoLogout: "ନିଷ୍କ୍ରିୟତା ପରେ ସ୍ୱୟଂଚାଳିତ ଲଗଆଉଟ୍",
  saveSettings: "ସେଟିଂସ୍ ସଂରକ୍ଷଣ କରନ୍ତୁ",
  analytics: "ବିଶ୍ଳେଷଣ",
  settings: "ସେଟିଂସ୍",
  
  // Common UI Keys (NEW - Task 5.1)
  save: "ସଂରକ୍ଷଣ କରନ୍ତୁ",
  cancel: "ବାତିଲ କରନ୍ତୁ",
  edit: "ସମ୍ପାଦନା କରନ୍ତୁ",
  delete: "ବିଲୋପ କରନ୍ତୁ",
  confirm: "ନିଶ୍ଚିତ କରନ୍ତୁ",
  back: "ପଛକୁ",
  next: "ପରବର୍ତ୍ତୀ",
  previous: "ପୂର୍ବବର୍ତ୍ତୀ",
  close: "ବନ୍ଦ କରନ୍ତୁ",
  open: "ଖୋଲନ୍ତୁ",
  yes: "ହଁ",
  no: "ନା",
  ok: "ଠିକ ଅଛି",
  error: "ତ୍ରୁଟି",
  success: "ସଫଳତା",
  warning: "ଚେତାବନୀ",
  info: "ସୂଚନା",
  processing: "ପ୍ରକ୍ରିୟାକରଣ...",
  
  // Services & About Page Keys (NEW - Task 5.1)
  allServices: "ସମସ୍ତ ସେବା",
  serviceCategories: "ସେବା ବର୍ଗ",
  popularServices: "ଲୋକପ୍ରିୟ ସେବା",
  mission: "ମିଶନ୍",
  vision: "ଦୃଷ୍ଟିକୋଣ",
  features: "ବୈଶିଷ୍ଟ୍ୟ",
  howItWorks: "ଏହା କିପରି କାମ କରେ",
  
  // Contact Page Keys (NEW - Task 5.1)
  getInTouch: "ଯୋଗାଯୋଗରେ ରୁହନ୍ତୁ",
  sendMessage: "ବାର୍ତ୍ତା ପଠାନ୍ତୁ",
  yourName: "ଆପଣଙ୍କ ନାମ",
  yourEmail: "ଆପଣଙ୍କ ଇମେଲ୍",
  yourMessage: "ଆପଣଙ୍କ ବାର୍ତ୍ତା",
  messageSent: "ବାର୍ତ୍ତା ପଠାଯାଇଛି",
  
  // AI Assistant Keys (NEW - Task 5.1)
  aiWelcome: "ସ୍ୱାଗତ! ସରକାରୀ ଯୋଜନା ଏବଂ ସେବା ଖୋଜିବାରେ ଆପଣଙ୍କୁ ସାହାଯ୍ୟ କରିବାକୁ ମୁଁ ଏଠାରେ ଅଛି। ଆଜି ମୁଁ ଆପଣଙ୍କୁ କିପରି ସାହାଯ୍ୟ କରିପାରିବି?",
  aiHelp: "ଯୋଜନା ଖୋଜିବା, ଯୋଗ୍ୟତା ଯାଞ୍ଚ କରିବା ଏବଂ ସରକାରୀ ସେବା ବିଷୟରେ ପ୍ରଶ୍ନର ଉତ୍ତର ଦେବାରେ ମୁଁ ଆପଣଙ୍କୁ ସାହାଯ୍ୟ କରିପାରିବି।",
  aiCommands: "ଉପଲବ୍ଧ କମାଣ୍ଡ: /schemes, /eligibility, /apply, /track, /help",
  askQuestion: "ଏକ ପ୍ରଶ୍ନ ପଚାରନ୍ତୁ",
  typeMessage: "ଆପଣଙ୍କ ବାର୍ତ୍ତା ଟାଇପ୍ କରନ୍ତୁ",
  
  // Theme Keys (NEW)
  toggleTheme: "ଥିମ୍ ଟୋଗଲ୍ କରନ୍ତୁ",
  lightMode: "ଲାଇଟ୍",
  darkMode: "ଡାର୍କ",
  systemMode: "ସିଷ୍ଟମ୍",
};

// Assamese translations (comprehensive)
const assameseStrings: Record<string, string> = {
  ...englishStrings,
  home: "ঘৰ",
  services: "সেৱাসমূহ",
  about: "বিষয়ে",
  contact: "যোগাযোগ",
  appName: "চৰকাৰী আৰু ছাত্ৰ সহায়",
  tagline: "ছাত্ৰ আৰু নাগৰিকসকলৰ বাবে একীভূত সহায়",
  students: "ছাত্ৰ-ছাত্ৰী",
  citizens: "নাগৰিক",
  schemeApplicants: "আঁচনি আবেদনকাৰী",
  govInitiative: "ভাৰত চৰকাৰৰ পদক্ষেপ",
  govAndStudent: "চৰকাৰী আৰু ছাত্ৰ",
  helpPlatform: "সহায় মঞ্চ",
  oneStopAssistance: "ভাৰতৰ ছাত্ৰ আৰু নাগৰিকসকলৰ বাবে একীভূত সহায়",
  exploreAllSchemes: "সকলো আঁচনি অন্বেষণ কৰক",
  whoAreYou: "আপুনি কোন?",
  viewSchemes: "আঁচনিসমূহ চাওক",
  search: "বিচাৰক",
  health: "স্বাস্থ্য",
  education: "শিক্ষা",
  agriculture: "কৃষি",
  scholarship: "বৃত্তি",
  welfare: "কল্যাণ",
  employment: "নিয়োগ",
  schemes: "আঁচনিসমূহ",
  apply: "আবেদন কৰক",
  eligibility: "যোগ্যতা",
  pending: "বিচাৰাধীন",
  approved: "অনুমোদিত",
  rejected: "প্ৰত্যাখ্যান",
  contactTitle: "আমাৰ সৈতে যোগাযোগ কৰক",
  name: "নাম",
  message: "বাৰ্তা",
  submit: "দাখিল কৰক",
  aboutTitle: "চৰকাৰী আৰু ছাত্ৰ সহায় মঞ্চৰ বিষয়ে",
  aboutBody: "এই মঞ্চই ভাৰতৰ ছাত্ৰ আৰু নাগৰিকসকলক চৰকাৰী আঁচনি, বৃত্তি আৰু সেৱা বিচাৰি পোৱাত সহায় কৰে।",
  
  // Authentication
  sign_in: "ছাইন ইন",
  sign_out: "ছাইন আউট",
  dashboard: "ডেশ্বব'ৰ্ড",
  
  // Auth Page Keys (NEW - Task 5.2)
  login: "লগইন",
  signup: "ছাইন আপ",
  admin: "প্ৰশাসক",
  email: "ইমেইল",
  password: "পাছৱৰ্ড",
  displayName: "প্ৰদৰ্শন নাম",
  district: "জিলা",
  taluka: "তালুকা",
  createAccount: "একাউণ্ট সৃষ্টি কৰক",
  pleaseWait: "অনুগ্ৰহ কৰি অপেক্ষা কৰক...",
  welcomeBack: "পুনৰ স্বাগতম!",
  adminAccessOnly: "কেৱল প্ৰশাসক প্ৰৱেশ",
  restrictedArea: "এই অঞ্চল কেৱল অনুমোদিত চৰকাৰী প্ৰশাসকসকলৰ বাবে সীমাবদ্ধ।",
  authenticating: "প্ৰমাণীকৰণ কৰা হৈছে...",
  adminLogin: "প্ৰশাসক লগইন",
  invalidCredentials: "অবৈধ প্ৰমাণপত্ৰ",
  loginFailed: "লগইন বিফল",
  signupSuccess: "একাউণ্ট সৃষ্টি হৈছে!",
  checkEmail: "আপোনাৰ ইমেইল পৰীক্ষা কৰক",
  accountCreated: "একাউণ্ট সৃষ্টি হৈছে! চৰকাৰী আৰু ছাত্ৰ সহায় মঞ্চলৈ স্বাগতম!",
  adminUsername: "প্ৰশাসক ব্যৱহাৰকাৰী নাম",
  adminPassword: "প্ৰশাসক পাছৱৰ্ড",
  enterAdminUsername: "প্ৰশাসক ব্যৱহাৰকাৰী নাম প্ৰবিষ্ট কৰক",
  enterAdminPassword: "প্ৰশাসক পাছৱৰ্ড প্ৰবিষ্ট কৰক",
  enterFullName: "আপোনাৰ সম্পূৰ্ণ নাম প্ৰবিষ্ট কৰক",
  selectDistrictPlaceholder: "জিলা নিৰ্বাচন কৰক",
  selectTalukaPlaceholder: "তালুকা নিৰ্বাচন কৰক",
  
  // Admin Panel Keys (NEW - Task 5.2)
  totalUsers: "মুঠ ব্যৱহাৰকাৰী",
  todayActivity: "আজিৰ আবেদন",
  pendingReviews: "বিচাৰাধীন আবেদন",
  userManagement: "ব্যৱহাৰকাৰী পৰিচালনা",
  applicationManagement: "আবেদন পৰিচালনা",
  schemeManagement: "আঁচনি পৰিচালনা",
  viewDetails: "বিৱৰণ চাওক",
  deleteUser: "ব্যৱহাৰকাৰী মচক",
  statistics: "পৰিসংখ্যা",
  recentActivity: "শেহতীয়া কাৰ্যকলাপ",
  quickActions: "দ্ৰুত কাৰ্য",
  reviewApplications: "আবেদন পৰ্যালোচনা কৰক",
  addNewScheme: "নতুন আঁচনি যোগ কৰক",
  viewReports: "প্ৰতিবেদন চাওক",
  adminDashboard: "প্ৰশাসক ডেশ্বব'ৰ্ড",
  comprehensiveManagement: "আঁচনি আৰু আবেদনৰ ব্যাপক পৰিচালনা",
  live: "লাইভ",
  logout: "লগআউট",
  allApplications: "সকলো আবেদন",
  total: "মুঠ",
  noApplicationsFound: "কোনো আবেদন পোৱা নগ'ল",
  needsAttention: "মনোযোগৰ প্ৰয়োজন",
  registeredUsers: "পঞ্জীয়নভুক্ত ব্যৱহাৰকাৰী",
  allTime: "সকলো সময়",
  receivedToday: "আজি প্ৰাপ্ত",
  manageAllSchemes: "সকলো চৰকাৰী আঁচনি পৰিচালনা কৰক",
  allCategories: "সকলো শ্ৰেণী",
  allStates: "সকলো ৰাজ্য",
  export: "ৰপ্তানি",
  import: "আমদানি",
  noSchemesFoundFilter: "কোনো আঁচনি পোৱা নগ'ল",
  adjustFilters: "ফিল্টাৰ সমন্বয় কৰক বা নতুন আঁচনি যোগ কৰক",
  manageAllApplications: "সকলো ব্যৱহাৰকাৰী আবেদন পৰিচালনা কৰক",
  refresh: "সতেজ কৰক",
  needDocs: "নথি-পত্ৰ প্ৰয়োজন",
  users: "ব্যৱহাৰকাৰী",
  andMoreUsers: "আৰু {count} অধিক ব্যৱহাৰকাৰী...",
  noDistrict: "কোনো জিলা নাই",
  categoryDistribution: "শ্ৰেণী বিতৰণ",
  applicationStatusLabel: "আবেদন স্থিতি",
  systemSettings: "ছিষ্টেম ছেটিংছ",
  platformConfiguration: "মঞ্চ বিন্যাস",
  defaultLanguage: "ডিফল্ট ভাষা",
  maxUploadSize: "সৰ্বোচ্চ আপলোড আকাৰ",
  securitySettings: "সুৰক্ষা ছেটিংছ",
  twoFactorAuth: "দুই-কাৰক প্ৰমাণীকৰণ",
  enableForSecurity: "অতিৰিক্ত সুৰক্ষাৰ বাবে সক্ষম কৰক",
  enable: "সক্ষম কৰক",
  sessionTimeout: "ছেছন টাইমআউট",
  autoLogout: "নিষ্ক্ৰিয়তাৰ পিছত স্বয়ংক্ৰিয় লগআউট",
  saveSettings: "ছেটিংছ সংৰক্ষণ কৰক",
  analytics: "বিশ্লেষণ",
  settings: "ছেটিংছ",
  
  // Common UI Keys (NEW - Task 5.2)
  save: "সংৰক্ষণ কৰক",
  cancel: "বাতিল কৰক",
  edit: "সম্পাদনা কৰক",
  delete: "মচক",
  confirm: "নিশ্চিত কৰক",
  back: "পিছলৈ",
  next: "পৰৱৰ্তী",
  previous: "পূৰ্ববৰ্তী",
  close: "বন্ধ কৰক",
  open: "খোলক",
  yes: "হয়",
  no: "নহয়",
  ok: "ঠিক আছে",
  error: "ত্ৰুটি",
  success: "সফলতা",
  warning: "সতৰ্কবাণী",
  info: "তথ্য",
  processing: "প্ৰক্ৰিয়াকৰণ...",
  
  // Services & About Page Keys (NEW - Task 5.2)
  allServices: "সকলো সেৱা",
  serviceCategories: "সেৱা শ্ৰেণী",
  popularServices: "জনপ্ৰিয় সেৱা",
  mission: "মিছন",
  vision: "দৃষ্টিভংগী",
  features: "বৈশিষ্ট্য",
  howItWorks: "ই কেনেকৈ কাম কৰে",
  
  // Contact Page Keys (NEW - Task 5.2)
  getInTouch: "যোগাযোগত থাকক",
  sendMessage: "বাৰ্তা প্ৰেৰণ কৰক",
  yourName: "আপোনাৰ নাম",
  yourEmail: "আপোনাৰ ইমেইল",
  yourMessage: "আপোনাৰ বাৰ্তা",
  messageSent: "বাৰ্তা প্ৰেৰণ কৰা হৈছে",
  
  // AI Assistant Keys (NEW - Task 5.2)
  aiWelcome: "স্বাগতম! চৰকাৰী আঁচনি আৰু সেৱা বিচাৰি পোৱাত আপোনাক সহায় কৰিবলৈ মই ইয়াত আছো। আজি মই আপোনাক কেনেকৈ সহায় কৰিব পাৰো?",
  aiHelp: "আঁচনি বিচাৰি উলিওৱা, যোগ্যতা পৰীক্ষা কৰা আৰু চৰকাৰী সেৱাৰ বিষয়ে প্ৰশ্নৰ উত্তৰ দিয়াত মই আপোনাক সহায় কৰিব পাৰো।",
  aiCommands: "উপলব্ধ আদেশ: /schemes, /eligibility, /apply, /track, /help",
  askQuestion: "এটা প্ৰশ্ন সোধক",
  typeMessage: "আপোনাৰ বাৰ্তা টাইপ কৰক",
  
  // Theme Keys (NEW)
  toggleTheme: "থিম টগল কৰক",
  lightMode: "লাইট",
  darkMode: "ডাৰ্ক",
  systemMode: "চিষ্টেম",
};


// Combine all strings
const strings: Record<Lang, Record<string, string>> = {
  en: englishStrings,
  hi: hindiStrings,
  mr: marathiStrings,
  bn: bengaliStrings,
  ta: tamilStrings,
  te: teluguStrings,
  gu: gujaratiStrings,
  kn: kannadaStrings,
  ml: malayalamStrings,
  pa: punjabiStrings,
  or: odiaStrings,
  as: assameseStrings,
};

// Export for testing purposes
export { strings, englishStrings };

// Language metadata
const languageMetadata = [
  { code: 'en' as Lang, name: 'English', nativeName: 'English' },
  { code: 'hi' as Lang, name: 'Hindi', nativeName: 'हिंदी' },
  { code: 'mr' as Lang, name: 'Marathi', nativeName: 'मराठी' },
  { code: 'bn' as Lang, name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'ta' as Lang, name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te' as Lang, name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'gu' as Lang, name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'kn' as Lang, name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ml' as Lang, name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'pa' as Lang, name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'or' as Lang, name: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'as' as Lang, name: 'Assamese', nativeName: 'অসমীয়া' },
];

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const stored = localStorage.getItem("lang");
    return (stored as Lang) || "en";
  });

  useEffect(() => {
    localStorage.setItem("lang", lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const toggle = () => {
    setLangState((prev) => {
      if (prev === "en") return "hi";
      if (prev === "hi") return "mr";
      return "en";
    });
  };

  const setLang = (l: Lang) => setLangState(l);

  const getLanguageName = () => {
    const langData = languageMetadata.find(l => l.code === lang);
    return langData?.nativeName || 'English';
  };

  const getAllLanguages = () => languageMetadata;

  const t = useMemo(
    () => (key: string) => {
      // Try the requested language first
      if (strings[lang] && strings[lang][key]) {
        return strings[lang][key];
      }
      // Fall back to English
      if (strings.en && strings.en[key]) {
        return strings.en[key];
      }
      // Return the key itself as last resort
      return key;
    },
    [lang]
  );

  return (
    <LanguageContext.Provider value={{ lang, toggle, setLang, t, getLanguageName, getAllLanguages }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLang must be used within a LanguageProvider");
  }
  return context;
}
